
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_5/gen_5_cand_95_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_5/gen_5_cand_95_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 09:55:16.980515

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.08 s.
Making connections...
  Number of connections on node 0: 244 
  Done; cell connection time = 2.43 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.14 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 44.31 s; real-time ratio: 0.11.

Gathering data...
  Done; gather time = 0.14 s.

Analyzing...
  Cells: 400
  Connections: 644 (1.61 per cell)
  Spikes: 50372 (25.19 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 44.31 s
   E : 36.048 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_5/gen_5_cand_95_data.json ... 
Finished saving!
  Done; saving time = 0.67 s.
  Done; plotting time = 0.00 s

Total time = 47.96 s
first instance of v_init
first instance of tstop
