
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_5/gen_5_cand_88_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_5/gen_5_cand_88_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 09:53:52.335769

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.07 s.
Making connections...
  Number of connections on node 0: 38649 
  Done; cell connection time = 11.14 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.08 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 629.28 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.01 s.

Analyzing...
  Cells: 400
  Connections: 39049 (97.62 per cell)
  Spikes: 2498 (1.25 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 629.28 s
   E : 0.075 Hz
   I : 2.630 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_5/gen_5_cand_88_data.json ... 
Finished saving!
  Done; saving time = 2.36 s.
  Done; plotting time = 0.00 s

Total time = 644.97 s
first instance of v_init
first instance of tstop
