
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_6/gen_6_cand_74_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_6/gen_6_cand_74_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/240430_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 17:05:32.194331

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.32 s.
Making connections...
  Number of connections on node 0: 7455 
  Done; cell connection time = 13.62 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 534.28 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 1.42 s.

Analyzing...
  Cells: 400
  Connections: 7455 (18.64 per cell)
  Spikes: 3451 (0.86 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 534.28 s
   E : 0.000 Hz
   I : 19.741 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_6/gen_6_cand_74_data.json ... 
Finished saving!
  Done; saving time = 2.97 s.
  Done; plotting time = 0.00 s

Total time = 552.68 s
