
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_5/gen_5_cand_71_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_5/gen_5_cand_71_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 09:55:01.071983

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.53 s.
Making connections...
  Number of connections on node 0: 2595 
  Done; cell connection time = 25.82 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 1.01 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 604.51 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 3.60 s.

Analyzing...
  Cells: 400
  Connections: 2995 (7.49 per cell)
  Spikes: 467 (0.23 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 604.51 s
   E : 0.000 Hz
   I : 0.852 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_5/gen_5_cand_71_data.json ... 
Finished saving!
  Done; saving time = 3.69 s.
  Done; plotting time = 0.00 s

Total time = 639.17 s
first instance of v_init
first instance of tstop
