
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_1/gen_1_cand_21_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_1/gen_1_cand_21_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 05:21:11.438386

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.46 s.
Making connections...
  Number of connections on node 0: 227 
  Done; cell connection time = 15.06 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.65 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 237.89 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 0.77 s.

Analyzing...
  Cells: 400
  Connections: 627 (1.57 per cell)
  Spikes: 809 (0.40 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 237.89 s
   E : 0.778 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_1/gen_1_cand_21_data.json ... 
Finished saving!
  Done; saving time = 1.88 s.
  Done; plotting time = 0.00 s

Total time = 256.76 s
first instance of v_init
first instance of tstop
