
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_1/gen_1_cand_95_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_1/gen_1_cand_95_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 05:21:11.565409

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.42 s.
Making connections...
  Number of connections on node 0: 8793 
  Done; cell connection time = 30.43 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.65 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1098.30 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 8.19 s.

Analyzing...
  Cells: 400
  Connections: 9193 (22.98 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1098.30 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_1/gen_1_cand_95_data.json ... 
Finished saving!
  Done; saving time = 11.37 s.
  Done; plotting time = 0.00 s

Total time = 1149.45 s
first instance of v_init
first instance of tstop
