
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_1/gen_1_cand_98_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_1/gen_1_cand_98_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 05:17:16.973015

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.06 s.
Making connections...
  Number of connections on node 0: 11330 
  Done; cell connection time = 4.61 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.09 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 292.32 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 1.94 s.

Analyzing...
  Cells: 400
  Connections: 11730 (29.32 per cell)
  Spikes: 20056 (10.03 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 292.32 s
   E : 18.417 Hz
   I : 3.019 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_1/gen_1_cand_98_data.json ... 
Finished saving!
  Done; saving time = 2.95 s.
  Done; plotting time = 0.00 s

Total time = 302.03 s
first instance of v_init
first instance of tstop
