
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/gen_0/gen_0_cand_1_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/gen_0/gen_0_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/240506_Run1_overnightRun_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/netParams_popParams.json ... 
ADLFKJAS;DLFKJ

Start time:  2024-05-06 01:58:47.350699

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.73 s.
Making connections...
  Number of connections on node 0: 23721 
  Done; cell connection time = 173.88 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 12000.0 ms...
  Done; run time = 20397.09 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 32.62 s.

Analyzing...
  Cells: 400
  Connections: 23721 (59.30 per cell)
  Spikes: 53027 (11.05 Hz)
  Simulated time: 12.0 s; 1 workers
  Run time: 20397.09 s
   E : 2.456 Hz
   I : 15.435 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/gen_0/gen_0_cand_1_data.json ... 
Finished saving!
  Done; saving time = 51.64 s.
  Done; plotting time = 0.00 s

Total time = 20656.59 s
first instance of v_init
first instance of tstop
