
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/240506_Run1_overnightRun_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/netParams_popParams.json ... 
ADLFKJAS;DLFKJ

Start time:  2024-05-06 01:58:10.981092

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.11 s.
Making connections...
  Number of connections on node 0: 10103 
  Done; cell connection time = 3.50 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 12000.0 ms...
  Done; run time = 271.81 s; real-time ratio: 0.04.

Gathering data...
  Done; gather time = 0.52 s.

Analyzing...
  Cells: 400
  Connections: 10103 (25.26 per cell)
  Spikes: 85569 (17.83 Hz)
  Simulated time: 12.0 s; 1 workers
  Run time: 271.81 s
   E : 1.667 Hz
   I : 23.324 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/gen_0/gen_0_cand_2_data.json ... 
Finished saving!
  Done; saving time = 1.80 s.
  Done; plotting time = 0.00 s

Total time = 277.76 s
first instance of v_init
first instance of tstop
