
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/gen_0/gen_0_cand_3_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/gen_0/gen_0_cand_3_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/240506_Run1_overnightRun_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/netParams_popParams.json ... 
ADLFKJAS;DLFKJ

Start time:  2024-05-06 01:58:58.351120

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.50 s.
Making connections...
  Number of connections on node 0: 18618 
  Done; cell connection time = 179.69 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 12000.0 ms...
  Done; run time = 16937.41 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 35.43 s.

Analyzing...
  Cells: 400
  Connections: 18618 (46.55 per cell)
  Spikes: 61992 (12.91 Hz)
  Simulated time: 12.0 s; 1 workers
  Run time: 16937.41 s
   E : 0.885 Hz
   I : 18.417 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/gen_0/gen_0_cand_3_data.json ... 
Finished saving!
  Done; saving time = 61.64 s.
  Done; plotting time = 0.00 s

Total time = 17217.89 s
first instance of v_init
first instance of tstop
