
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/gen_0/gen_0_cand_50_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/gen_0/gen_0_cand_50_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/240506_Run1_overnightRun_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/netParams_popParams.json ... 
ADLFKJAS;DLFKJ

Start time:  2024-05-06 01:59:32.403632

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 3.89 s.
Making connections...
  Number of connections on node 0: 24824 
  Done; cell connection time = 225.08 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 12000.0 ms...
  Done; run time = 15066.67 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 43.28 s.

Analyzing...
  Cells: 400
  Connections: 24824 (62.06 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 12.0 s; 1 workers
  Run time: 15066.67 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/gen_0/gen_0_cand_50_data.json ... 
Finished saving!
  Done; saving time = 68.55 s.
  Done; plotting time = 0.00 s

Total time = 15407.86 s
first instance of v_init
first instance of tstop
