
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_15/gen_15_cand_63_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_15/gen_15_cand_63_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/240430_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 22:35:16.931332

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.50 s.
Making connections...
  Number of connections on node 0: 38257 
  Done; cell connection time = 30.73 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 1566.58 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 1.72 s.

Analyzing...
  Cells: 400
  Connections: 38257 (95.64 per cell)
  Spikes: 35821 (8.96 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 1566.58 s
   E : 0.063 Hz
   I : 37.028 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_15/gen_15_cand_63_data.json ... 
Finished saving!
  Done; saving time = 2.40 s.
  Done; plotting time = 0.00 s

Total time = 1601.95 s
