
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_15/gen_15_cand_91_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_15/gen_15_cand_91_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/240430_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 22:35:21.671654

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.30 s.
Making connections...
  Number of connections on node 0: 443 
  Done; cell connection time = 3.15 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 160.66 s; real-time ratio: 0.06.

Gathering data...
  Done; gather time = 0.35 s.

Analyzing...
  Cells: 400
  Connections: 443 (1.11 per cell)
  Spikes: 95370 (23.84 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 160.66 s
   E : 32.202 Hz
   I : 1.046 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_15/gen_15_cand_91_data.json ... 
Finished saving!
  Done; saving time = 3.12 s.
  Done; plotting time = 0.00 s

Total time = 167.77 s
