
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run24_debug_run/gen_0/gen_0_cand_1_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run24_debug_run/gen_0/gen_0_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run24_debug_run/240417_Run24_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run24_debug_run/netParams_popParams.json ... 

Start time:  2024-04-17 23:20:09.668741

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.04 s.
Making connections...
  Number of connections on node 0: 26473 
  Done; cell connection time = 3.70 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.03 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 78.36 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 0.92 s.

Analyzing...
  Cells: 400
  Connections: 26873 (67.18 per cell)
  Spikes: 1652 (4.13 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 78.36 s
   E : 5.714 Hz
   I : 1.852 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run24_debug_run/gen_0/gen_0_cand_1_data.json ... 
Finished saving!
  Done; saving time = 1.01 s.
  Done; plotting time = 0.00 s

Total time = 84.08 s
