/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC
Current gen: 0
Incoming gen: 0
Arguments have been appended to commands.txt
Initiating Rank: 1
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 1: 3 
  Number of connections on node 1: 93 
  Number of stims on node 1: 0 
Recording 0 traces of 0 types on node 1
Initiating Rank: 3
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 3: 3 
  Number of connections on node 3: 118 
  Number of stims on node 3: 0 
Recording 0 traces of 0 types on node 3
Initiating Rank: 5
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 5: 3 
  Number of connections on node 5: 114 
  Number of stims on node 5: 0 
Recording 0 traces of 0 types on node 5
Initiating Rank: 7
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 7: 3 
  Number of connections on node 7: 140 
  Number of stims on node 7: 0 
Recording 0 traces of 0 types on node 7
Initiating Rank: 9
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 9: 3 
  Number of connections on node 9: 139 
  Number of stims on node 9: 0 
Recording 1 traces of 1 types on node 9
Initiating Rank: 11
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 11: 3 
  Number of connections on node 11: 94 
  Number of stims on node 11: 0 
Recording 0 traces of 0 types on node 11
Initiating Rank: 13
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 13: 3 
  Number of connections on node 13: 100 
  Number of stims on node 13: 0 
Recording 1 traces of 1 types on node 13
Initiating Rank: 15
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 15: 3 
  Number of connections on node 15: 123 
  Number of stims on node 15: 0 
Recording 0 traces of 0 types on node 15
Initiating Rank: 17
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 17: 3 
  Number of connections on node 17: 120 
  Number of stims on node 17: 0 
Recording 0 traces of 0 types on node 17
Initiating Rank: 19
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 19: 3 
  Number of connections on node 19: 105 
  Number of stims on node 19: 0 
Recording 0 traces of 0 types on node 19
Initiating Rank: 21
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 21: 3 
  Number of connections on node 21: 111 
  Number of stims on node 21: 0 
Recording 0 traces of 0 types on node 21
Initiating Rank: 23
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 23: 3 
  Number of connections on node 23: 107 
  Number of stims on node 23: 0 
Recording 0 traces of 0 types on node 23
Initiating Rank: 25
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 25: 3 
  Number of connections on node 25: 102 
  Number of stims on node 25: 0 
Recording 0 traces of 0 types on node 25
Initiating Rank: 27
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 27: 3 
  Number of connections on node 27: 102 
  Number of stims on node 27: 0 
Recording 0 traces of 0 types on node 27
Initiating Rank: 31
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 31: 3 
  Number of connections on node 31: 105 
  Number of stims on node 31: 0 
Recording 0 traces of 0 types on node 31
Initiating Rank: 32
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 32: 3 
  Number of connections on node 32: 138 
  Number of stims on node 32: 0 
Recording 0 traces of 0 types on node 32
Initiating Rank: 33
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 33: 3 
  Number of connections on node 33: 118 
  Number of stims on node 33: 0 
Recording 0 traces of 0 types on node 33
Initiating Rank: 34
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 34: 3 
  Number of connections on node 34: 119 
  Number of stims on node 34: 0 
Recording 0 traces of 0 types on node 34
Initiating Rank: 35
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 35: 3 
  Number of connections on node 35: 130 
  Number of stims on node 35: 0 
Recording 0 traces of 0 types on node 35
Initiating Rank: 36
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 36: 3 
  Number of connections on node 36: 119 
  Number of stims on node 36: 0 
Recording 0 traces of 0 types on node 36
Initiating Rank: 37
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 37: 3 
  Number of connections on node 37: 122 
  Number of stims on node 37: 0 
Recording 0 traces of 0 types on node 37
Initiating Rank: 38
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 38: 3 
  Number of connections on node 38: 134 
  Number of stims on node 38: 0 
Recording 0 traces of 0 types on node 38
Initiating Rank: 39
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 39: 3 
  Number of connections on node 39: 102 
  Number of stims on node 39: 0 
Recording 0 traces of 0 types on node 39
Initiating Rank: 40
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 40: 3 
  Number of connections on node 40: 141 
  Number of stims on node 40: 0 
Recording 0 traces of 0 types on node 40
Initiating Rank: 41
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 41: 3 
  Number of connections on node 41: 123 
  Number of stims on node 41: 0 
Recording 0 traces of 0 types on node 41
Initiating Rank: 42
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 42: 3 
  Number of connections on node 42: 117 
  Number of stims on node 42: 0 
Recording 0 traces of 0 types on node 42
Initiating Rank: 43
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 43: 3 
  Number of connections on node 43: 130 
  Number of stims on node 43: 0 
Recording 0 traces of 0 types on node 43
Initiating Rank: 44
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 44: 3 
  Number of connections on node 44: 109 
  Number of stims on node 44: 0 
Recording 0 traces of 0 types on node 44
Initiating Rank: 45
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 45: 3 
  Number of connections on node 45: 133 
  Number of stims on node 45: 0 
Recording 0 traces of 0 types on node 45
Initiating Rank: 46
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 46: 3 
  Number of connections on node 46: 112 
  Number of stims on node 46: 0 
Recording 0 traces of 0 types on node 46
Initiating Rank: 47
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 47: 2 
  Number of connections on node 47: 61 
  Number of stims on node 47: 0 
Recording 0 traces of 0 types on node 47
Initiating Rank: 2
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 2: 3 
  Number of connections on node 2: 121 
  Number of stims on node 2: 0 
Recording 0 traces of 0 types on node 2
Initiating Rank: 4
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 4: 3 
  Number of connections on node 4: 96 
  Number of stims on node 4: 0 
Recording 0 traces of 0 types on node 4
Initiating Rank: 6
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 6: 3 
  Number of connections on node 6: 108 
  Number of stims on node 6: 0 
Recording 0 traces of 0 types on node 6
Initiating Rank: 8
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 8: 3 
  Number of connections on node 8: 139 
  Number of stims on node 8: 0 
Recording 1 traces of 1 types on node 8
Initiating Rank: 10
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 10: 3 
  Number of connections on node 10: 105 
  Number of stims on node 10: 0 
Recording 0 traces of 0 types on node 10
Initiating Rank: 12
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 12: 3 
  Number of connections on node 12: 132 
  Number of stims on node 12: 0 
Recording 0 traces of 0 types on node 12
Initiating Rank: 14
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 14: 3 
  Number of connections on node 14: 143 
  Number of stims on node 14: 0 
Recording 0 traces of 0 types on node 14
Initiating Rank: 16
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 16: 3 
  Number of connections on node 16: 114 
  Number of stims on node 16: 0 
Recording 0 traces of 0 types on node 16
Initiating Rank: 18
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 18: 3 
  Number of connections on node 18: 132 
  Number of stims on node 18: 0 
Recording 0 traces of 0 types on node 18
Initiating Rank: 20
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 20: 3 
  Number of connections on node 20: 118 
  Number of stims on node 20: 0 
Recording 1 traces of 1 types on node 20
Initiating Rank: 22
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 22: 3 
  Number of connections on node 22: 125 
  Number of stims on node 22: 0 
Recording 0 traces of 0 types on node 22
Initiating Rank: 24
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 24: 3 
  Number of connections on node 24: 128 
  Number of stims on node 24: 0 
Recording 0 traces of 0 types on node 24
Initiating Rank: 26
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 26: 3 
  Number of connections on node 26: 120 
  Number of stims on node 26: 0 
Recording 0 traces of 0 types on node 26
Initiating Rank: 28
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 28: 3 
  Number of connections on node 28: 122 
  Number of stims on node 28: 0 
Recording 0 traces of 0 types on node 28
Initiating Rank: 29
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 29: 3 
  Number of connections on node 29: 128 
  Number of stims on node 29: 0 
Recording 0 traces of 0 types on node 29
Initiating Rank: 30
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 30: 3 
  Number of connections on node 30: 129 
  Number of stims on node 30: 0 
Recording 0 traces of 0 types on node 30
Initiating Rank: 0
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 

Start time:  2024-06-04 18:19:20.173952

Creating network of 2 cell populations on 48 hosts...
  Number of cells on node 0: 3 
  Done; cell creation time = 0.00 s.
Making connections...
  Number of connections on node 0: 99 
  Done; cell connection time = 0.14 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 330000.0 ms...
  Done; run time = 63.50 s; real-time ratio: 5.20.

Gathering data...
  Done; gather time = 1.54 s.

Analyzing...
  Cells: 143
  Connections: 5640 (39.44 per cell)
  Spikes: 3 (0.00 Hz)
  Simulated time: 330.0 s; 48 workers
  Run time: 63.50 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_0/gen_0_cand_126_data.json ... 
Finished saving!
  Done; saving time = 17.64 s.
  Done; plotting time = 0.00 s

Total time = 83.11 s
numprocs=48
