
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/gen_0/gen_0_cand_88_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/gen_0/gen_0_cand_88_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/240424_Run9_scaling_up_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/netParams_popParams.json ... 

Start time:  2024-04-24 23:17:55.129658

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.23 s.
Making connections...
  Number of connections on node 0: 1228 
  Done; cell connection time = 3.21 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.08 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 59.91 s; real-time ratio: 0.08.

Gathering data...
  Done; gather time = 0.23 s.

Analyzing...
  Cells: 400
  Connections: 1628 (4.07 per cell)
  Spikes: 134506 (67.25 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 59.91 s
   E : 89.964 Hz
   I : 9.065 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/gen_0/gen_0_cand_88_data.json ... 
Finished saving!
  Done; saving time = 2.26 s.
  Done; plotting time = 0.00 s

Total time = 66.16 s
first instance of v_init
first instance of tstop
