
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_debug_node_run/gen_2/gen_2_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_debug_node_run/gen_2/gen_2_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_debug_node_run/240429_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 03:55:13.034037

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.74 s.
Making connections...
  Number of connections on node 0: 9045 
  Done; cell connection time = 96.18 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 4419.75 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 8.30 s.

Analyzing...
  Cells: 400
  Connections: 9045 (22.61 per cell)
  Spikes: 5396 (1.35 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 4419.75 s
   E : 0.012 Hz
   I : 3.343 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_debug_node_run/gen_2/gen_2_cand_16_data.json ... 
Finished saving!
  Done; saving time = 15.29 s.
  Done; plotting time = 0.00 s

Total time = 4541.50 s
