
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run16_debug_node_run/gen_3/gen_3_cand_43_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run16_debug_node_run/gen_3/gen_3_cand_43_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run16_debug_node_run/240505_Run16_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run16_debug_node_run/netParams_popParams.json ... 
ADLFKJAS;DLFKJ

Start time:  2024-05-05 15:25:41.721449

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 8.79 s.
Making connections...
  Number of connections on node 0: 1433 
  Done; cell connection time = 136.10 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 15000.0 ms...
  Done; run time = 5960.86 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 8.14 s.

Analyzing...
  Cells: 400
  Connections: 1433 (3.58 per cell)
  Spikes: 130426 (21.74 Hz)
  Simulated time: 15.0 s; 1 workers
  Run time: 5960.86 s
   E : 25.198 Hz
   I : 22.315 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run16_debug_node_run/gen_3/gen_3_cand_43_data.json ... 
Finished saving!
  Done; saving time = 69.24 s.
  Done; plotting time = 0.00 s

Total time = 6186.13 s
first instance of v_init
first instance of tstop
