
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run5_debug_run/gen_0/gen_0_cand_1_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run5_debug_run/gen_0/gen_0_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run5_debug_run/240426_Run5_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run5_debug_run/netParams_popParams.json ... 

Start time:  2024-04-26 10:50:07.080756

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.12 s.
Making connections...
  Number of connections on node 0: 24138 
  Done; cell connection time = 5.47 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.04 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 277.33 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 0.76 s.

Analyzing...
  Cells: 400
  Connections: 24538 (61.34 per cell)
  Spikes: 65748 (32.87 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 277.33 s
   E : 67.302 Hz
   I : 8.380 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run5_debug_run/gen_0/gen_0_cand_1_data.json ... 
Finished saving!
  Done; saving time = 0.86 s.
  Done; plotting time = 0.00 s

Total time = 284.62 s
