
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_6/gen_6_cand_78_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_6/gen_6_cand_78_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 08:45:28.272113

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 4.55 s.
Making connections...
  Number of connections on node 0: 1899 
  Done; cell connection time = 145.84 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 4.36 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 2286.07 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 9.19 s.

Analyzing...
  Cells: 400
  Connections: 2299 (5.75 per cell)
  Spikes: 149 (0.07 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 2286.07 s
   E : 0.000 Hz
   I : 0.398 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_6/gen_6_cand_78_data.json ... 
Finished saving!
  Done; saving time = 10.33 s.
  Done; plotting time = 0.00 s

Total time = 2460.58 s
first instance of v_init
first instance of tstop
