
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_6/gen_6_cand_17_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_6/gen_6_cand_17_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 08:43:45.351365

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.96 s.
Making connections...
  Number of connections on node 0: 259 
  Done; cell connection time = 79.53 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 3.00 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1043.53 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 3.50 s.

Analyzing...
  Cells: 400
  Connections: 659 (1.65 per cell)
  Spikes: 3865 (1.93 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1043.53 s
   E : 0.000 Hz
   I : 6.194 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_6/gen_6_cand_17_data.json ... 
Finished saving!
  Done; saving time = 7.76 s.
  Done; plotting time = 0.00 s

Total time = 1140.53 s
first instance of v_init
first instance of tstop
