Initiating Rank: 2
TEST CWD: /workspaces/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /workspaces/2DNetworkSimulations/NERSC/output/240519_Run4_more_docker_testing/gen_0/gen_0_cand_1_cfg.json
Loading file /workspaces/2DNetworkSimulations/NERSC/output/240519_Run4_more_docker_testing/gen_0/gen_0_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /workspaces/2DNetworkSimulations/NERSC/output/240519_Run4_more_docker_testing/240519_Run4_more_docker_testing_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /workspaces/2DNetworkSimulations/NERSC/output/240519_Run4_more_docker_testing/netParams_popParams.json ... 

Start time:  2024-05-19 22:59:37.153076

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.06 s.
Making connections...
  Number of connections on node 0: 21625 
  Done; cell connection time = 5.87 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 33.42 s; real-time ratio: 0.03.

Gathering data...
  Done; gather time = 1.00 s.

Analyzing...
  Cells: 400
  Connections: 21625 (54.06 per cell)
  Spikes: 22727 (56.82 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 33.42 s
   E : 84.222 Hz
   I : 0.000 Hz
Saving output as /workspaces/2DNetworkSimulations/NERSC/output/240519_Run4_more_docker_testing/gen_0/gen_0_cand_1_data.json ... 
Finished saving!
  Done; saving time = 1.05 s.
  Done; plotting time = 0.00 s

Total time = 41.44 s
