
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240418_Run1_debug_run/gen_0/gen_0_cand_0_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240418_Run1_debug_run/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240418_Run1_debug_run/240418_Run1_debug_run_netParams.py
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240418_Run1_debug_run/netParams_popParams.json ... 

Start time:  2024-04-18 00:03:05.789725

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.08 s.
Making connections...
  Number of connections on node 0: 16258 
  Done; cell connection time = 5.91 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.12 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 49.42 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 0.69 s.

Analyzing...
  Cells: 400
  Connections: 16658 (41.65 per cell)
  Spikes: 2663 (6.66 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 49.42 s
   E : 10.417 Hz
   I : 0.009 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240418_Run1_debug_run/gen_0/gen_0_cand_0_data.json ... 
Finished saving!
  Done; saving time = 0.68 s.
  Done; plotting time = 0.00 s

Total time = 56.92 s
