
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240418_Run1_debug_run/gen_0/gen_0_cand_3_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240418_Run1_debug_run/gen_0/gen_0_cand_3_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240418_Run1_debug_run/240418_Run1_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240418_Run1_debug_run/netParams_popParams.json ... 

Start time:  2024-04-18 00:03:09.020104

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.06 s.
Making connections...
  Number of connections on node 0: 4323 
  Done; cell connection time = 3.91 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.09 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 16.04 s; real-time ratio: 0.06.

Gathering data...
  Done; gather time = 0.24 s.

Analyzing...
  Cells: 400
  Connections: 4723 (11.81 per cell)
  Spikes: 10219 (25.55 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 16.04 s
   E : 35.611 Hz
   I : 11.241 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240418_Run1_debug_run/gen_0/gen_0_cand_3_data.json ... 
Finished saving!
  Done; saving time = 0.40 s.
  Done; plotting time = 0.00 s

Total time = 20.77 s
