
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_5/gen_5_cand_43_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_5/gen_5_cand_43_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 09:54:43.464084

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.19 s.
Making connections...
  Number of connections on node 0: 540 
  Done; cell connection time = 6.61 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.24 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 143.85 s; real-time ratio: 0.03.

Gathering data...
  Done; gather time = 0.58 s.

Analyzing...
  Cells: 400
  Connections: 940 (2.35 per cell)
  Spikes: 22636 (11.32 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 143.85 s
   E : 11.901 Hz
   I : 9.907 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_5/gen_5_cand_43_data.json ... 
Finished saving!
  Done; saving time = 1.62 s.
  Done; plotting time = 0.00 s

Total time = 153.74 s
first instance of v_init
first instance of tstop
