
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_2/gen_2_cand_24_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_2/gen_2_cand_24_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 06:47:29.768585

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.62 s.
Making connections...
  Number of connections on node 0: 718 
  Done; cell connection time = 23.44 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 1.08 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 697.86 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 3.14 s.

Analyzing...
  Cells: 400
  Connections: 1118 (2.79 per cell)
  Spikes: 194 (0.10 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 697.86 s
   E : 0.000 Hz
   I : 0.454 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_2/gen_2_cand_24_data.json ... 
Finished saving!
  Done; saving time = 5.62 s.
  Done; plotting time = 0.00 s

Total time = 731.76 s
first instance of v_init
first instance of tstop
