
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_2/gen_2_cand_9_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_2/gen_2_cand_9_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 06:36:24.700896

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.41 s.
Making connections...
  Number of connections on node 0: 6970 
  Done; cell connection time = 25.16 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.66 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1252.33 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 8.76 s.

Analyzing...
  Cells: 400
  Connections: 7370 (18.43 per cell)
  Spikes: 28912 (14.46 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1252.33 s
   E : 2.171 Hz
   I : 3.972 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_2/gen_2_cand_9_data.json ... 
Finished saving!
  Done; saving time = 14.14 s.
  Done; plotting time = 0.00 s

Total time = 1301.83 s
first instance of v_init
first instance of tstop
