
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_2/gen_2_cand_43_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_2/gen_2_cand_43_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 06:34:28.080972

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.23 s.
Making connections...
  Number of connections on node 0: 9523 
  Done; cell connection time = 13.39 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.24 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1688.42 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 11.22 s.

Analyzing...
  Cells: 400
  Connections: 9923 (24.81 per cell)
  Spikes: 125066 (62.53 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1688.42 s
   E : 71.310 Hz
   I : 32.037 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_2/gen_2_cand_43_data.json ... 
Finished saving!
  Done; saving time = 23.02 s.
  Done; plotting time = 0.00 s

Total time = 1737.84 s
first instance of v_init
first instance of tstop
