Initiating Rank: 3
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 3: 25 
  Number of connections on node 3: 2164 
  Number of stims on node 3: 0 
Recording 0 traces of 0 types on node 3
Initiating Rank: 7
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 7: 25 
  Number of connections on node 7: 2111 
  Number of stims on node 7: 0 
Initiating Rank: 9
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 9: 25 
  Number of connections on node 9: 2140 
  Number of stims on node 9: 0 
Recording 0 traces of 0 types on node 7
Recording 0 traces of 0 types on node 9
Initiating Rank: 5
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 5: 25 
  Number of connections on node 5: 2174 
  Number of stims on node 5: 0 
Initiating Rank: 11
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 11: 25 
  Number of connections on node 11: 2276 
  Number of stims on node 11: 0 
Recording 0 traces of 0 types on node 5
Recording 0 traces of 0 types on node 11
Initiating Rank: 1
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 1: 25 
  Number of connections on node 1: 2176 
  Number of stims on node 1: 0 
Initiating Rank: 13
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 13: 25 
  Number of connections on node 13: 2264 
  Number of stims on node 13: 0 
Recording 0 traces of 0 types on node 1
Recording 0 traces of 0 types on node 13
Initiating Rank: 2
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 2: 25 
  Number of connections on node 2: 2128 
  Number of stims on node 2: 0 
Initiating Rank: 15
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 15: 25 
  Number of connections on node 15: 2095 
  Number of stims on node 15: 0 
Recording 0 traces of 0 types on node 2
Recording 0 traces of 0 types on node 15
Initiating Rank: 4
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 4: 25 
  Number of connections on node 4: 2116 
  Number of stims on node 4: 0 
Initiating Rank: 8
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 8: 25 
  Number of connections on node 8: 2194 
  Number of stims on node 8: 0 
Recording 0 traces of 0 types on node 4
Recording 1 traces of 1 types on node 8
Initiating Rank: 6
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 6: 25 
  Number of connections on node 6: 2209 
  Number of stims on node 6: 0 
Initiating Rank: 10
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 10: 25 
  Number of connections on node 10: 2359 
  Number of stims on node 10: 0 
Recording 0 traces of 0 types on node 6
Recording 0 traces of 0 types on node 10
Initiating Rank: 12
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 12: 25 
  Number of connections on node 12: 2300 
  Number of stims on node 12: 0 
Recording 0 traces of 0 types on node 12
Initiating Rank: 14
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 14: 25 
  Number of connections on node 14: 2153 
  Number of stims on node 14: 0 
Recording 0 traces of 0 types on node 14
Initiating Rank: 0
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 

Start time:  2024-05-22 16:56:05.190265

Creating network of 2 cell populations on 16 hosts...
  Number of cells on node 0: 25 
  Done; cell creation time = 0.00 s.
Making connections...
  Number of connections on node 0: 2199 
  Done; cell connection time = 1.15 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 1 traces of 1 types on node 0

Running simulation using NEURON for 15000.0 ms...
  Done; run time = 42.20 s; real-time ratio: 0.36.

Gathering data...
  Done; gather time = 0.62 s.

Analyzing...
  Cells: 400
  Connections: 35058 (87.64 per cell)
  Spikes: 49907 (8.32 Hz)
  Simulated time: 15.0 s; 16 workers
  Run time: 42.20 s
   E : 15.540 Hz
   I : 0.046 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_data.json ... 
Finished saving!
  Done; saving time = 1.41 s.
  Done; plotting time = 0.00 s

Total time = 45.60 s
numprocs=16
Initiating Rank: 1
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 1: 13 
  Number of connections on node 1: 940 
  Number of stims on node 1: 0 
Recording 0 traces of 0 types on node 1
Initiating Rank: 3
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 3: 13 
  Number of connections on node 3: 929 
  Number of stims on node 3: 0 
Initiating Rank: 8
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 8: 13 
  Number of connections on node 8: 946 
  Number of stims on node 8: 0 
Initiating Rank: 16
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 16: 12 
  Number of connections on node 16: 866 
  Number of stims on node 16: 0 
Initiating Rank: 25
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 25: 12 
  Number of connections on node 25: 794 
  Number of stims on node 25: 0 
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 8
Recording 0 traces of 0 types on node 16
Recording 0 traces of 0 types on node 25
Initiating Rank: 5
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 5: 13 
  Number of connections on node 5: 823 
  Number of stims on node 5: 0 
Initiating Rank: 9
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 9: 13 
  Number of connections on node 9: 893 
  Number of stims on node 9: 0 
Initiating Rank: 17
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 17: 12 
  Number of connections on node 17: 784 
  Number of stims on node 17: 0 
Initiating Rank: 27
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 27: 12 
  Number of connections on node 27: 832 
  Number of stims on node 27: 0 
Recording 0 traces of 0 types on node 5
Recording 0 traces of 0 types on node 9
Recording 0 traces of 0 types on node 17
Recording 0 traces of 0 types on node 27
Initiating Rank: 7
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 7: 13 
  Number of connections on node 7: 865 
  Number of stims on node 7: 0 
Initiating Rank: 10
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 10: 13 
  Number of connections on node 10: 937 
  Number of stims on node 10: 0 
Initiating Rank: 18
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 18: 12 
  Number of connections on node 18: 805 
  Number of stims on node 18: 0 
Initiating Rank: 28
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 28: 12 
  Number of connections on node 28: 880 
  Number of stims on node 28: 0 
Recording 0 traces of 0 types on node 7
Recording 0 traces of 0 types on node 10
Recording 1 traces of 1 types on node 18
Recording 0 traces of 0 types on node 28
Initiating Rank: 2
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 2: 13 
  Number of connections on node 2: 933 
  Number of stims on node 2: 0 
Initiating Rank: 11
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 11: 13 
  Number of connections on node 11: 925 
  Number of stims on node 11: 0 
Initiating Rank: 19
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 19: 12 
  Number of connections on node 19: 926 
  Number of stims on node 19: 0 
Initiating Rank: 29
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 29: 12 
  Number of connections on node 29: 831 
  Number of stims on node 29: 0 
Recording 2 traces of 1 types on node 2
Recording 0 traces of 0 types on node 11
Recording 0 traces of 0 types on node 19
Recording 0 traces of 0 types on node 29
Initiating Rank: 4
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 4: 13 
  Number of connections on node 4: 976 
  Number of stims on node 4: 0 
Initiating Rank: 12
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 12: 13 
  Number of connections on node 12: 920 
  Number of stims on node 12: 0 
Initiating Rank: 20
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 20: 12 
  Number of connections on node 20: 766 
  Number of stims on node 20: 0 
Initiating Rank: 30
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 30: 12 
  Number of connections on node 30: 801 
  Number of stims on node 30: 0 
Recording 0 traces of 0 types on node 4
Recording 0 traces of 0 types on node 12
Recording 0 traces of 0 types on node 20
Recording 0 traces of 0 types on node 30
Initiating Rank: 6
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 6: 13 
  Number of connections on node 6: 924 
  Number of stims on node 6: 0 
Initiating Rank: 13
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 13: 13 
  Number of connections on node 13: 922 
  Number of stims on node 13: 0 
Initiating Rank: 21
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 21: 12 
  Number of connections on node 21: 961 
  Number of stims on node 21: 0 
Initiating Rank: 31
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 31: 12 
  Number of connections on node 31: 807 
  Number of stims on node 31: 0 
Recording 0 traces of 0 types on node 6
Recording 1 traces of 1 types on node 13
Recording 0 traces of 0 types on node 21
Recording 0 traces of 0 types on node 31
Initiating Rank: 14
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 14: 13 
  Number of connections on node 14: 903 
  Number of stims on node 14: 0 
Initiating Rank: 23
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 23: 12 
  Number of connections on node 23: 822 
  Number of stims on node 23: 0 
Initiating Rank: 24
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 24: 12 
  Number of connections on node 24: 854 
  Number of stims on node 24: 0 
Recording 0 traces of 0 types on node 14
Recording 0 traces of 0 types on node 23
Recording 0 traces of 0 types on node 24
Initiating Rank: 15
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 15: 13 
  Number of connections on node 15: 845 
  Number of stims on node 15: 0 
Initiating Rank: 22
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 22: 12 
  Number of connections on node 22: 849 
  Number of stims on node 22: 0 
Initiating Rank: 26
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 26: 12 
  Number of connections on node 26: 863 
  Number of stims on node 26: 0 
Recording 0 traces of 0 types on node 15
Recording 0 traces of 0 types on node 22
Recording 0 traces of 0 types on node 26
Initiating Rank: 0
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 

Start time:  2024-05-23 00:58:29.153315

Creating network of 2 cell populations on 32 hosts...
  Number of cells on node 0: 13 
  Done; cell creation time = 0.00 s.
Making connections...
  Number of connections on node 0: 894 
  Done; cell connection time = 1.00 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 15000.0 ms...
  Done; run time = 19.85 s; real-time ratio: 0.76.

Gathering data...
  Done; gather time = 0.49 s.

Analyzing...
  Cells: 400
  Connections: 28016 (70.04 per cell)
  Spikes: 32387 (5.40 Hz)
  Simulated time: 15.0 s; 32 workers
  Run time: 19.85 s
   E : 12.492 Hz
   I : 4.898 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_30_data.json ... 
Finished saving!
  Done; saving time = 1.60 s.
  Done; plotting time = 0.00 s

Total time = 23.14 s
numprocs=32
