Initiating Rank: 1
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 1: 25 
  Number of connections on node 1: 2348 
  Number of stims on node 1: 0 
Recording 0 traces of 0 types on node 1
Initiating Rank: 3
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 3: 25 
  Number of connections on node 3: 2357 
  Number of stims on node 3: 0 
Initiating Rank: 9
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 9: 25 
  Number of connections on node 9: 2304 
  Number of stims on node 9: 0 
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 9
Initiating Rank: 5
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 5: 25 
  Number of connections on node 5: 2396 
  Number of stims on node 5: 0 
Initiating Rank: 11
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 11: 25 
  Number of connections on node 11: 2430 
  Number of stims on node 11: 0 
Recording 0 traces of 0 types on node 5
Recording 0 traces of 0 types on node 11
Initiating Rank: 7
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 7: 25 
  Number of connections on node 7: 2369 
  Number of stims on node 7: 0 
Initiating Rank: 13
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 13: 25 
  Number of connections on node 13: 2322 
  Number of stims on node 13: 0 
Recording 0 traces of 0 types on node 7
Recording 0 traces of 0 types on node 13
Initiating Rank: 2
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 2: 25 
  Number of connections on node 2: 2343 
  Number of stims on node 2: 0 
Initiating Rank: 15
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 15: 25 
  Number of connections on node 15: 2266 
  Number of stims on node 15: 0 
Recording 0 traces of 0 types on node 2
Recording 0 traces of 0 types on node 15
Initiating Rank: 6
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 6: 25 
  Number of connections on node 6: 2384 
  Number of stims on node 6: 0 
Initiating Rank: 8
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 8: 25 
  Number of connections on node 8: 2357 
  Number of stims on node 8: 0 
Recording 0 traces of 0 types on node 6
Recording 1 traces of 1 types on node 8
Initiating Rank: 4
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 4: 25 
  Number of connections on node 4: 2281 
  Number of stims on node 4: 0 
Initiating Rank: 10
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 10: 25 
  Number of connections on node 10: 2495 
  Number of stims on node 10: 0 
Recording 0 traces of 0 types on node 4
Recording 0 traces of 0 types on node 10
Initiating Rank: 12
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 12: 25 
  Number of connections on node 12: 2385 
  Number of stims on node 12: 0 
Recording 0 traces of 0 types on node 12
Initiating Rank: 14
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 14: 25 
  Number of connections on node 14: 2288 
  Number of stims on node 14: 0 
Recording 0 traces of 0 types on node 14
Initiating Rank: 0
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 

Start time:  2024-05-22 16:37:37.056587

Creating network of 2 cell populations on 16 hosts...
  Number of cells on node 0: 25 
  Done; cell creation time = 0.00 s.
Making connections...
  Number of connections on node 0: 2410 
  Done; cell connection time = 1.18 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 1 traces of 1 types on node 0

Running simulation using NEURON for 15000.0 ms...
  Done; run time = 53.18 s; real-time ratio: 0.28.

Gathering data...
  Done; gather time = 0.68 s.

Analyzing...
  Cells: 400
  Connections: 37735 (94.34 per cell)
  Spikes: 45125 (7.52 Hz)
  Simulated time: 15.0 s; 16 workers
  Run time: 53.18 s
   E : 20.028 Hz
   I : 1.546 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_data.json ... 
Finished saving!
  Done; saving time = 1.72 s.
  Done; plotting time = 0.00 s

Total time = 56.79 s
numprocs=16
Initiating Rank: 1
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 1: 13 
  Number of connections on node 1: 301 
  Number of stims on node 1: 0 
Recording 0 traces of 0 types on node 1
Initiating Rank: 8
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 8: 13 
  Number of connections on node 8: 269 
  Number of stims on node 8: 0 
Initiating Rank: 16
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 16: 12 
  Number of connections on node 16: 246 
  Number of stims on node 16: 0 
Initiating Rank: 24
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 24: 12 
  Number of connections on node 24: 253 
  Number of stims on node 24: 0 
Initiating Rank: 3
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 3: 13 
  Number of connections on node 3: 256 
  Number of stims on node 3: 0 
Recording 0 traces of 0 types on node 8
Recording 0 traces of 0 types on node 16
Recording 0 traces of 0 types on node 24
Recording 0 traces of 0 types on node 3
Initiating Rank: 9
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 9: 13 
  Number of connections on node 9: 273 
  Number of stims on node 9: 0 
Initiating Rank: 17
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 17: 12 
  Number of connections on node 17: 237 
  Number of stims on node 17: 0 
Initiating Rank: 25
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 25: 12 
  Number of connections on node 25: 227 
  Number of stims on node 25: 0 
Initiating Rank: 5
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 5: 13 
  Number of connections on node 5: 242 
  Number of stims on node 5: 0 
Recording 0 traces of 0 types on node 9
Recording 0 traces of 0 types on node 17
Recording 0 traces of 0 types on node 25
Recording 0 traces of 0 types on node 5
Initiating Rank: 10
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 10: 13 
  Number of connections on node 10: 293 
  Number of stims on node 10: 0 
Initiating Rank: 18
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 18: 12 
  Number of connections on node 18: 230 
  Number of stims on node 18: 0 
Initiating Rank: 26
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 26: 12 
  Number of connections on node 26: 265 
  Number of stims on node 26: 0 
Initiating Rank: 7
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 7: 13 
  Number of connections on node 7: 247 
  Number of stims on node 7: 0 
Recording 0 traces of 0 types on node 10
Recording 1 traces of 1 types on node 18
Recording 0 traces of 0 types on node 26
Recording 0 traces of 0 types on node 7
Initiating Rank: 11
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 11: 13 
  Number of connections on node 11: 289 
  Number of stims on node 11: 0 
Initiating Rank: 19
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 19: 12 
  Number of connections on node 19: 260 
  Number of stims on node 19: 0 
Initiating Rank: 27
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 27: 12 
  Number of connections on node 27: 244 
  Number of stims on node 27: 0 
Initiating Rank: 2
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 2: 13 
  Number of connections on node 2: 257 
  Number of stims on node 2: 0 
Recording 0 traces of 0 types on node 11
Recording 0 traces of 0 types on node 19
Recording 0 traces of 0 types on node 27
Recording 2 traces of 1 types on node 2
Initiating Rank: 12
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 12: 13 
  Number of connections on node 12: 269 
  Number of stims on node 12: 0 
Initiating Rank: 20
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 20: 12 
  Number of connections on node 20: 227 
  Number of stims on node 20: 0 
Initiating Rank: 28
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 28: 12 
  Number of connections on node 28: 275 
  Number of stims on node 28: 0 
Initiating Rank: 4
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 4: 13 
  Number of connections on node 4: 290 
  Number of stims on node 4: 0 
Recording 0 traces of 0 types on node 12
Recording 0 traces of 0 types on node 20
Recording 0 traces of 0 types on node 28
Recording 0 traces of 0 types on node 4
Initiating Rank: 13
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 13: 13 
  Number of connections on node 13: 277 
  Number of stims on node 13: 0 
Initiating Rank: 21
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 21: 12 
  Number of connections on node 21: 287 
  Number of stims on node 21: 0 
Initiating Rank: 29
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 29: 12 
  Number of connections on node 29: 237 
  Number of stims on node 29: 0 
Initiating Rank: 6
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 6: 13 
  Number of connections on node 6: 283 
  Number of stims on node 6: 0 
Recording 1 traces of 1 types on node 13
Recording 0 traces of 0 types on node 21
Recording 0 traces of 0 types on node 29
Recording 0 traces of 0 types on node 6
Initiating Rank: 14
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 14: 13 
  Number of connections on node 14: 261 
  Number of stims on node 14: 0 
Initiating Rank: 22
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 22: 12 
  Number of connections on node 22: 241 
  Number of stims on node 22: 0 
Initiating Rank: 30
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 30: 12 
  Number of connections on node 30: 235 
  Number of stims on node 30: 0 
Recording 0 traces of 0 types on node 14
Recording 0 traces of 0 types on node 22
Recording 0 traces of 0 types on node 30
Initiating Rank: 15
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 15: 13 
  Number of connections on node 15: 254 
  Number of stims on node 15: 0 
Initiating Rank: 23
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 23: 12 
  Number of connections on node 23: 243 
  Number of stims on node 23: 0 
Initiating Rank: 31
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 
  Number of cells on node 31: 12 
  Number of connections on node 31: 209 
  Number of stims on node 31: 0 
Recording 0 traces of 0 types on node 15
Recording 0 traces of 0 types on node 23
Recording 0 traces of 0 types on node 31
Initiating Rank: 0
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/240522_Run4_it_srun_sims_2nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/netParams_popParams.json ... 

Start time:  2024-05-22 22:02:26.040303

Creating network of 2 cell populations on 32 hosts...
  Number of cells on node 0: 13 
  Done; cell creation time = 0.00 s.
Making connections...
  Number of connections on node 0: 276 
  Done; cell connection time = 0.93 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 15000.0 ms...
  Done; run time = 5.61 s; real-time ratio: 2.68.

Gathering data...
  Done; gather time = 0.17 s.

Analyzing...
  Cells: 400
  Connections: 8253 (20.63 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 15.0 s; 32 workers
  Run time: 5.61 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240522_Run4_it_srun_sims_2nodes/gen_0/gen_0_cand_16_data.json ... 
Finished saving!
  Done; saving time = 1.07 s.
  Done; plotting time = 0.00 s

Total time = 7.92 s
numprocs=32
