
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/gen_2/gen_2_cand_89_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/gen_2/gen_2_cand_89_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/240506_Run1_overnightRun_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/netParams_popParams.json ... 
ADLFKJAS;DLFKJ

Start time:  2024-05-06 10:08:31.465499

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.90 s.
Making connections...
  Number of connections on node 0: 29082 
  Done; cell connection time = 47.94 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 12000.0 ms...
  Done; run time = 5087.51 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 4.18 s.

Analyzing...
  Cells: 400
  Connections: 29082 (72.70 per cell)
  Spikes: 142990 (29.79 Hz)
  Simulated time: 12.0 s; 1 workers
  Run time: 5087.51 s
   E : 77.325 Hz
   I : 14.065 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/gen_2/gen_2_cand_89_data.json ... 
Finished saving!
  Done; saving time = 6.71 s.
  Done; plotting time = 0.00 s

Total time = 5147.44 s
first instance of v_init
first instance of tstop
