
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/gen_2/gen_2_cand_55_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/gen_2/gen_2_cand_55_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/240506_Run1_overnightRun_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/netParams_popParams.json ... 
ADLFKJAS;DLFKJ

Start time:  2024-05-06 10:08:56.945065

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 4.86 s.
Making connections...
  Number of connections on node 0: 4585 
  Done; cell connection time = 93.78 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 12000.0 ms...
  Done; run time = 5080.06 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 8.42 s.

Analyzing...
  Cells: 400
  Connections: 4585 (11.46 per cell)
  Spikes: 209796 (43.71 Hz)
  Simulated time: 12.0 s; 1 workers
  Run time: 5080.06 s
   E : 49.639 Hz
   I : 8.648 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240506_Run1_overnightRun/gen_2/gen_2_cand_55_data.json ... 
Finished saving!
  Done; saving time = 42.49 s.
  Done; plotting time = 0.00 s

Total time = 5231.72 s
first instance of v_init
first instance of tstop
