
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/gen_0/gen_0_cand_122_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/gen_0/gen_0_cand_122_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/240424_Run9_scaling_up_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/netParams_popParams.json ... 

Start time:  2024-04-24 23:18:01.498670

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.17 s.
Making connections...
  Number of connections on node 0: 4710 
  Done; cell connection time = 7.57 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.19 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 99.33 s; real-time ratio: 0.05.

Gathering data...
  Done; gather time = 0.40 s.

Analyzing...
  Cells: 400
  Connections: 5110 (12.78 per cell)
  Spikes: 206 (0.10 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 99.33 s
   E : 0.000 Hz
   I : 0.426 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/gen_0/gen_0_cand_122_data.json ... 
Finished saving!
  Done; saving time = 1.31 s.
  Done; plotting time = 0.00 s

Total time = 108.97 s
first instance of v_init
first instance of tstop
