
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/gen_0/gen_0_cand_116_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/gen_0/gen_0_cand_116_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/240424_Run9_scaling_up_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/netParams_popParams.json ... 

Start time:  2024-04-24 23:18:00.178477

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.12 s.
Making connections...
  Number of connections on node 0: 2625 
  Done; cell connection time = 5.93 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.12 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 76.66 s; real-time ratio: 0.07.

Gathering data...
  Done; gather time = 0.61 s.

Analyzing...
  Cells: 400
  Connections: 3025 (7.56 per cell)
  Spikes: 81321 (40.66 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 76.66 s
   E : 62.877 Hz
   I : 2.306 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/gen_0/gen_0_cand_116_data.json ... 
Finished saving!
  Done; saving time = 1.36 s.
  Done; plotting time = 0.00 s

Total time = 84.85 s
first instance of v_init
first instance of tstop
