
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_7/gen_7_cand_56_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_7/gen_7_cand_56_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-27 01:31:51.335575

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.89 s.
Making connections...
  Number of connections on node 0: 5570 
  Done; cell connection time = 88.06 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1424.82 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 4.92 s.

Analyzing...
  Cells: 400
  Connections: 5570 (13.93 per cell)
  Spikes: 112829 (56.41 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1424.82 s
   E : 63.964 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_7/gen_7_cand_56_data.json ... 
Finished saving!
  Done; saving time = 15.23 s.
  Done; plotting time = 0.00 s

Total time = 1535.72 s
first instance of v_init
first instance of tstop
