Initiating Rank: 0
TEST CWD: /workspaces/2DNetworkSimulations

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /workspaces/2DNetworkSimulations/NERSC/output/240522_Run2_vscode_debug/gen_3/gen_3_cand_0_cfg.json
Loading file /workspaces/2DNetworkSimulations/NERSC/output/240522_Run2_vscode_debug/gen_3/gen_3_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /workspaces/2DNetworkSimulations/NERSC/output/240522_Run2_vscode_debug/240522_Run2_vscode_debug_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /workspaces/2DNetworkSimulations/NERSC/output/240522_Run2_vscode_debug/netParams_popParams.json ... 

Start time:  2024-05-22 21:56:35.378780

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.05 s.
Making connections...
  Number of connections on node 0: 74596 
  Done; cell connection time = 10.56 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
