Initiating Rank: 0
TEST CWD: /workspaces/2DNetworkSimulations

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /workspaces/2DNetworkSimulations/NERSC/output/240522_Run2_vscode_debug/gen_3/gen_3_cand_1_cfg.json
Loading file /workspaces/2DNetworkSimulations/NERSC/output/240522_Run2_vscode_debug/gen_3/gen_3_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /workspaces/2DNetworkSimulations/NERSC/output/240522_Run2_vscode_debug/240522_Run2_vscode_debug_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /workspaces/2DNetworkSimulations/NERSC/output/240522_Run2_vscode_debug/netParams_popParams.json ... 

Start time:  2024-05-22 21:56:36.369576

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.05 s.
Making connections...
  Number of connections on node 0: 30624 
  Done; cell connection time = 5.13 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 38.45 s; real-time ratio: 0.03.

Gathering data...
  Done; gather time = 1.70 s.

Analyzing...
  Cells: 400
  Connections: 30624 (76.56 per cell)
  Spikes: 6310 (15.78 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 38.45 s
   E : 22.095 Hz
   I : 0.000 Hz
Saving output as /workspaces/2DNetworkSimulations/NERSC/output/240522_Run2_vscode_debug/gen_3/gen_3_cand_1_data.json ... 
