
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_1/gen_1_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_1/gen_1_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 03:28:33.916057

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.70 s.
Making connections...
  Number of connections on node 0: 543 
  Done; cell connection time = 62.66 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 2.17 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 918.62 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.92 s.

Analyzing...
  Cells: 400
  Connections: 943 (2.36 per cell)
  Spikes: 56957 (28.48 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 918.62 s
   E : 24.706 Hz
   I : 5.417 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_1/gen_1_cand_73_data.json ... 
Finished saving!
  Done; saving time = 10.30 s.
  Done; plotting time = 0.00 s

Total time = 1001.32 s
first instance of v_init
first instance of tstop
