
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_1/gen_1_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_1/gen_1_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 03:29:07.571159

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 3.75 s.
Making connections...
  Number of connections on node 0: 3494 
  Done; cell connection time = 139.61 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 3.58 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 3073.97 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 10.61 s.

Analyzing...
  Cells: 400
  Connections: 3894 (9.73 per cell)
  Spikes: 132134 (66.07 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 3073.97 s
   E : 55.587 Hz
   I : 17.398 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_1/gen_1_cand_30_data.json ... 
Finished saving!
  Done; saving time = 31.64 s.
  Done; plotting time = 0.00 s

Total time = 3265.40 s
first instance of v_init
first instance of tstop
