
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_1/gen_1_cand_4_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_1/gen_1_cand_4_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 03:27:02.893876

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.13 s.
Making connections...
  Number of connections on node 0: 3462 
  Done; cell connection time = 72.52 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 3.55 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 3064.73 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 10.12 s.

Analyzing...
  Cells: 400
  Connections: 3862 (9.65 per cell)
  Spikes: 29090 (14.54 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 3064.73 s
   E : 2.456 Hz
   I : 11.481 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_1/gen_1_cand_4_data.json ... 
Finished saving!
  Done; saving time = 18.28 s.
  Done; plotting time = 0.00 s

Total time = 3170.66 s
first instance of v_init
first instance of tstop
