
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_1/gen_1_cand_65_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_1/gen_1_cand_65_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 03:29:16.765862

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 3.41 s.
Making connections...
  Number of connections on node 0: 1977 
  Done; cell connection time = 124.71 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 3.84 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 2409.11 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 11.10 s.

Analyzing...
  Cells: 400
  Connections: 2377 (5.94 per cell)
  Spikes: 10547 (5.27 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 2409.11 s
   E : 5.413 Hz
   I : 0.176 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_1/gen_1_cand_65_data.json ... 
Finished saving!
  Done; saving time = 13.39 s.
  Done; plotting time = 0.00 s

Total time = 2565.90 s
first instance of v_init
first instance of tstop
