
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_7/gen_7_cand_127_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_7/gen_7_cand_127_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 09:47:22.771184

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.09 s.
Making connections...
  Number of connections on node 0: 306 
  Done; cell connection time = 69.73 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 2.61 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 920.37 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.70 s.

Analyzing...
  Cells: 400
  Connections: 706 (1.76 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 920.37 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_7/gen_7_cand_127_data.json ... 
Finished saving!
  Done; saving time = 5.93 s.
  Done; plotting time = 0.00 s

Total time = 1003.43 s
first instance of v_init
first instance of tstop
