
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_5/gen_5_cand_31_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_5/gen_5_cand_31_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/240430_Run1_interactive_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 16:08:01.605388

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.42 s.
Making connections...
  Number of connections on node 0: 34494 
  Done; cell connection time = 22.60 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 1647.65 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.68 s.

Analyzing...
  Cells: 400
  Connections: 34494 (86.23 per cell)
  Spikes: 70103 (17.53 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 1647.65 s
   E : 63.607 Hz
   I : 0.019 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_5/gen_5_cand_31_data.json ... 
Finished saving!
  Done; saving time = 4.22 s.
  Done; plotting time = 0.00 s

Total time = 1677.71 s
