
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_5/gen_5_cand_74_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_5/gen_5_cand_74_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/240430_Run1_interactive_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 16:08:23.711255

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.36 s.
Making connections...
  Number of connections on node 0: 3267 
  Done; cell connection time = 6.89 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 345.34 s; real-time ratio: 0.03.

Gathering data...
  Done; gather time = 0.78 s.

Analyzing...
  Cells: 400
  Connections: 3267 (8.17 per cell)
  Spikes: 702 (0.18 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 345.34 s
   E : 1.063 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_5/gen_5_cand_74_data.json ... 
Finished saving!
  Done; saving time = 2.87 s.
  Done; plotting time = 0.00 s

Total time = 356.24 s
