
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_5/gen_5_cand_71_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_5/gen_5_cand_71_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/240430_Run1_interactive_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 16:08:23.859706

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.36 s.
Making connections...
  Number of connections on node 0: 29602 
  Done; cell connection time = 28.83 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 1443.75 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.22 s.

Analyzing...
  Cells: 400
  Connections: 29602 (74.00 per cell)
  Spikes: 2684 (0.67 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 1443.75 s
   E : 0.000 Hz
   I : 2.778 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_5/gen_5_cand_71_data.json ... 
Finished saving!
  Done; saving time = 3.02 s.
  Done; plotting time = 0.00 s

Total time = 1478.20 s
