Initiating Rank: 0
TEST CWD: /workspaces/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /workspaces/2DNetworkSimulations/NERSC/output/240519_Run3_vscode_debug/gen_3/gen_3_cand_1_cfg.json
Loading file /workspaces/2DNetworkSimulations/NERSC/output/240519_Run3_vscode_debug/gen_3/gen_3_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /workspaces/2DNetworkSimulations/NERSC/output/240519_Run3_vscode_debug/240519_Run3_vscode_debug_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /workspaces/2DNetworkSimulations/NERSC/output/240519_Run3_vscode_debug/netParams_popParams.json ... 

Start time:  2024-05-19 22:03:45.277182

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.04 s.
Making connections...
  Number of connections on node 0: 1403 
  Done; cell connection time = 1.17 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 3.26 s; real-time ratio: 0.31.

Gathering data...
  Done; gather time = 0.07 s.

Analyzing...
  Cells: 400
  Connections: 1403 (3.51 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 3.26 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /workspaces/2DNetworkSimulations/NERSC/output/240519_Run3_vscode_debug/gen_3/gen_3_cand_1_data.json ... 
Finished saving!
  Done; saving time = 0.12 s.
  Done; plotting time = 0.00 s

Total time = 4.66 s
