
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run10_testing_run_name/gen_2/gen_2_cand_0_cfg.json
Loading file /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run10_testing_run_name/gen_2/gen_2_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run10_testing_run_name/240414_Run10_testing_run_name_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run10_testing_run_name/netParams_popParams.json ... 
Duration: 1.0 seconds

Start time:  2024-04-14 01:11:03.356830

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.03 s.
Making connections...
  Number of connections on node 0: 266 
  Done; cell connection time = 0.85 s.
Adding stims...
  Number of stims on node 0: 800 
  Done; cell stims creation time = 0.06 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 3.32 s; real-time ratio: 0.30.

Gathering data...
  Done; gather time = 0.05 s.

Analyzing...
  Cells: 400
  Connections: 666 (1.67 per cell)
  Synaptic contacts: 1066 (2.67 per cell)
  Spikes: 17 (0.04 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 3.32 s
   E : 0.063 Hz
   I : 0.000 Hz
Saving output as /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run10_testing_run_name/gen_2/gen_2_cand_0_data.json ... 
Finished saving!
  Done; saving time = 0.10 s.
  Done; plotting time = 0.00 s

Total time = 4.41 s
