
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run1_testing_run_name/gen_0/gen_0_cand_3_cfg.json
Loading file /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run1_testing_run_name/gen_0/gen_0_cand_3_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run1_testing_run_name/240414_Run1_testing_run_name_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run1_testing_run_name/netParams_popParams.json ... 

Start time:  2024-04-14 00:41:47.534033

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.05 s.
Making connections...
  Number of connections on node 0: 14105 
  Done; cell connection time = 3.87 s.
Adding stims...
  Number of stims on node 0: 800 
  Done; cell stims creation time = 0.13 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 22.41 s; real-time ratio: 0.04.

Gathering data...
  Done; gather time = 0.27 s.

Analyzing...
  Cells: 400
  Connections: 14505 (36.26 per cell)
  Synaptic contacts: 14905 (37.26 per cell)
  Spikes: 2834 (7.08 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 22.41 s
   E : 3.493 Hz
   I : 2.911 Hz
Saving output as /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run1_testing_run_name/gen_0/gen_0_cand_3_data.json ... 
Finished saving!
  Done; saving time = 0.01 s.
  Done; plotting time = 0.00 s

Total time = 26.76 s
