FROM python:3.8

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        gfortran \
        wget \
        libtool \
        libx11-dev \
        bison \
        cmake \
        flex \
        git \
        libncurses-dev \
        libopenmpi-dev \
        libx11-dev \
        libxcomposite-dev \
        openmpi-bin \
        libreadline-dev \
        fontconfig && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /opt

# Install Python packages using pip
RUN pip install --no-cache-dir \
        scipy \
        numpy \
        cython \
        matplotlib \
        mpi4py \
        wheel \
        setuptools \
        setuptools_scm \
        scikit-build \
        packaging \
        'bokeh<3' \
        ipython \
        'cython<3' \
        'pytest<=8.1.1' \
        pytest-cov \
        find_libpython

# Install NEURON using pip
RUN pip install neuron 
RUN pip install netpyne 
RUN pip install inspyred

# Set necessary environment variables
ENV LD_LIBRARY_PATH=/opt/miniconda3/lib:$LD_LIBRARY_PATH

# Set necessary environment variables
ENV LD_LIBRARY_PATH=/opt/miniconda3/lib:$LD_LIBRARY_PATH

# Prepare a writable directory for Fontconfig cache
RUN mkdir /opt/fontconfig && \
    chmod 777 /opt/fontconfig

# Set environment variable for Fontconfig to use the new cache directory
ENV FONTCONFIG_PATH=/opt/fontconfig

WORKDIR /app

# Create a non-root user
RUN useradd -m myuser -d /opt/myuser

# Set HOME environment variable
ENV HOME=/opt/myuser

# Make the home directory writable
RUN chmod 777 /opt/myuser

# Switch to the non-root user
USER myuser

# Set the default command to run when the container starts
CMD ["python"]