# Use a base image
FROM ubuntu:20.04

WORKDIR /opt

# Set noninteractive installation mode and timezone
ENV DEBIAN_FRONTEND noninteractive
ENV TZ=America/Los_Angeles

# Install necessary packages
RUN apt-get update && \
    apt-get install -y \
        locales \
        wget \
        gcc \
        g++ \
        build-essential \
        libncurses-dev \
        python3 \
        python3-pip \
        libpython3-dev \
        openmpi-bin \
        openmpi-common \
        libopenmpi-dev \
        git \
        cmake \
        bison \
        libreadline-dev \
        flex && \
    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 && \
    pip3 install --upgrade pip && \
    pip3 install cython
#    && pip install -r requirements.txt \

# Install Slurm and additional packages
RUN apt-get update && \
    apt-get install -y \
        slurm-wlm \
        libpmi0 \
        libpmix-dev \
        libpmix2 \
        libopenmpi-dev \
        libopenmpi3

RUN apt install -y libx11-dev libxcomposite-dev

#Set MpiDefault to pmix
#RUN echo "MpiDefault=pmix" >> /etc/slurm/slurm.conf

# # Clone the NEURON repository
# RUN git clone https://github.com/neuronsimulator/nrn.git /opt/nrn && \
#     cd /opt/nrn && \
#     git checkout tags/8.2.4  # Adjust the tag as per your specific version requirement

# # Configure NEURON using CMake
# RUN mkdir /opt/nrn/build && cd /opt/nrn/build && \
#     cmake .. \
#     -DNRN_ENABLE_INTERVIEWS=OFF \
#     -DNRN_ENABLE_PYTHON=ON \
#     -DNRN_ENABLE_CORENEURON=ON \
#     -DPYTHON_EXECUTABLE="/usr/bin/python3" \
#     -DNRN_ENABLE_MPI=ON \
#     -DCMAKE_INSTALL_PREFIX="/opt/neuron"
#     #-DCMAKE_PREFIX_PATH="/usr/local/ncurses"

RUN pip3 install numpy
# RUN cd /opt/nrn \
#     && python3 setup.py install

RUN python3 -m pip install neuron

RUN python3 -m pip install \
    numpy matplotlib h5py ruamel.yaml jupyter jupyter_server scipy six bluepyopt \
    netpyne Pillow 'bokeh<3' contextlib2 cycler fonttools future jinja2 kiwisolver lfpykit \
    markupsafe matplotlib-scalebar meautility packaging pandas pyparsing pytz pyyaml schema tornado inspyred \
    wheel setuptools setuptools_scm scikit-build ipython packaging 'pytest<=8.1.1' pytest-cov find_libpython
    
#install mpi4py
RUN python3 -m pip install mpi4py

RUN chmod -R 755 /opt
RUN useradd -m mpiuser
USER mpiuser
WORKDIR /app

ENV LANG en_US.utf8
#ENV PATH $PATH:/opt/nrn/x86_64/bin

#RUN cat /etc/slurm/slurm.conf
# Set environment variables for Open MPI
#ENV OMPI_MCA_orte_rsh_agent=ssh
#ENV OMPI_MCA_plm_rsh_agent=ssh
#ENV OMPI_MCA_orte_base_help_aggregate=0

# Set default command
CMD ["bash"]