
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run26_debug_run/gen_0/gen_0_cand_5_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run26_debug_run/gen_0/gen_0_cand_5_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run26_debug_run/240417_Run26_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run26_debug_run/netParams_popParams.json ... 

Start time:  2024-04-17 23:26:13.642534

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.03 s.
Making connections...
  Number of connections on node 0: 30184 
  Done; cell connection time = 4.90 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.03 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 60.42 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 1.11 s.

Analyzing...
  Cells: 400
  Connections: 30584 (76.46 per cell)
  Spikes: 15112 (37.78 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 60.42 s
   E : 56.313 Hz
   I : 7.806 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run26_debug_run/gen_0/gen_0_cand_5_data.json ... 
Finished saving!
  Done; saving time = 1.81 s.
  Done; plotting time = 0.00 s

Total time = 68.49 s
