
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run26_debug_run/gen_0/gen_0_cand_4_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run26_debug_run/gen_0/gen_0_cand_4_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run26_debug_run/240417_Run26_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run26_debug_run/netParams_popParams.json ... 

Start time:  2024-04-17 23:26:12.658667

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.03 s.
Making connections...
  Number of connections on node 0: 4382 
  Done; cell connection time = 1.86 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.05 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 8.79 s; real-time ratio: 0.11.

Gathering data...
  Done; gather time = 0.13 s.

Analyzing...
  Cells: 400
  Connections: 4782 (11.96 per cell)
  Spikes: 9446 (23.61 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 8.79 s
   E : 37.278 Hz
   I : 0.000 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run26_debug_run/gen_0/gen_0_cand_4_data.json ... 
Finished saving!
  Done; saving time = 0.23 s.
  Done; plotting time = 0.00 s

Total time = 11.12 s
