
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run1_interactive_debug/gen_1/gen_1_cand_5_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run1_interactive_debug/gen_1/gen_1_cand_5_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run1_interactive_debug/240429_Run1_interactive_debug_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run1_interactive_debug/netParams_popParams.json ... 

Start time:  2024-04-29 00:19:18.958842

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.04 s.
Making connections...
  Number of connections on node 0: 50754 
  Done; cell connection time = 5.86 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 243.97 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 1.07 s.

Analyzing...
  Cells: 400
  Connections: 50754 (126.89 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 243.97 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run1_interactive_debug/gen_1/gen_1_cand_5_data.json ... 
Finished saving!
  Done; saving time = 1.61 s.
  Done; plotting time = 0.00 s

Total time = 252.56 s
first instance of v_init
first instance of tstop
