
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run9_debug_run/gen_0/gen_0_cand_3_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run9_debug_run/gen_0/gen_0_cand_3_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run9_debug_run/240426_Run9_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run9_debug_run/netParams_popParams.json ... 

Start time:  2024-04-26 11:26:52.095566

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.05 s.
Making connections...
  Number of connections on node 0: 16744 
  Done; cell connection time = 3.03 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.04 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 153.97 s; real-time ratio: 0.03.

Gathering data...
  Done; gather time = 0.56 s.

Analyzing...
  Cells: 400
  Connections: 17144 (42.86 per cell)
  Spikes: 758 (0.38 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 153.97 s
   E : 0.000 Hz
   I : 1.398 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run9_debug_run/gen_0/gen_0_cand_3_data.json ... 
Finished saving!
  Done; saving time = 0.58 s.
  Done; plotting time = 0.00 s

Total time = 158.24 s
