
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_3/gen_3_cand_46_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_3/gen_3_cand_46_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 21:20:39.304825

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.81 s.
Making connections...
  Number of connections on node 0: 655 
  Done; cell connection time = 54.86 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 776.71 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 1.95 s.

Analyzing...
  Cells: 400
  Connections: 655 (1.64 per cell)
  Spikes: 369 (0.18 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 776.71 s
   E : 0.000 Hz
   I : 0.519 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_3/gen_3_cand_46_data.json ... 
Finished saving!
  Done; saving time = 8.67 s.
  Done; plotting time = 0.00 s

Total time = 844.19 s
first instance of v_init
first instance of tstop
