
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_interactive_debug/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_interactive_debug/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_interactive_debug/240429_Run2_interactive_debug_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_interactive_debug/netParams_popParams.json ... 

Start time:  2024-04-29 00:39:36.508847

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.06 s.
Making connections...
  Number of connections on node 0: 31724 
  Done; cell connection time = 4.43 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 175.31 s; real-time ratio: 0.03.

Gathering data...
  Done; gather time = 0.77 s.

Analyzing...
  Cells: 400
  Connections: 31724 (79.31 per cell)
  Spikes: 36301 (18.15 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 175.31 s
   E : 53.563 Hz
   I : 2.917 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_interactive_debug/gen_0/gen_0_cand_2_data.json ... 
Finished saving!
  Done; saving time = 1.15 s.
  Done; plotting time = 0.00 s

Total time = 181.76 s
first instance of v_init
first instance of tstop
