
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_13/gen_13_cand_97_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_13/gen_13_cand_97_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/240430_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 21:19:57.393635

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.25 s.
Making connections...
  Number of connections on node 0: 7160 
  Done; cell connection time = 4.35 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 491.10 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 1.55 s.

Analyzing...
  Cells: 400
  Connections: 7160 (17.90 per cell)
  Spikes: 280 (0.07 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 491.10 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_13/gen_13_cand_97_data.json ... 
Finished saving!
  Done; saving time = 2.83 s.
  Done; plotting time = 0.00 s

Total time = 500.10 s
