Initiating Rank: 1
TEST CWD: /app/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /app/NERSC/output/240521_Run1_more_docker_testing/gen_0/gen_0_cand_3_cfg.json
Loading file /app/NERSC/output/240521_Run1_more_docker_testing/gen_0/gen_0_cand_3_cfg.json ... 
Loading simConfig...
Importing netParams from /app/NERSC/output/240521_Run1_more_docker_testing/240521_Run1_more_docker_testing_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /app/NERSC/output/240521_Run1_more_docker_testing/netParams_popParams.json ... 

Start time:  2024-05-21 06:35:35.113983

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.06 s.
Making connections...
  Number of connections on node 0: 9009 
  Done; cell connection time = 3.54 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 18.08 s; real-time ratio: 0.06.

Gathering data...
  Done; gather time = 0.31 s.

Analyzing...
  Cells: 400
  Connections: 9009 (22.52 per cell)
  Spikes: 708 (1.77 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 18.08 s
   E : 0.000 Hz
   I : 3.713 Hz
Saving output as /app/NERSC/output/240521_Run1_more_docker_testing/gen_0/gen_0_cand_3_data.json ... 
Finished saving!
  Done; saving time = 0.42 s.
  Done; plotting time = 0.00 s

Total time = 22.42 s
