
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240428_Run5_interactive_debug/gen_0/gen_0_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240428_Run5_interactive_debug/gen_0/gen_0_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240428_Run5_interactive_debug/240428_Run5_interactive_debug_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240428_Run5_interactive_debug/netParams_popParams.json ... 

Start time:  2024-04-28 23:55:24.676104

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.06 s.
Making connections...
  Number of connections on node 0: 18409 
  Done; cell connection time = 3.08 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 156.24 s; real-time ratio: 0.03.

Gathering data...
  Done; gather time = 1.01 s.

Analyzing...
  Cells: 400
  Connections: 18409 (46.02 per cell)
  Spikes: 3992 (2.00 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 156.24 s
   E : 0.000 Hz
   I : 16.194 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240428_Run5_interactive_debug/gen_0/gen_0_cand_16_data.json ... 
Finished saving!
  Done; saving time = 2.79 s.
  Done; plotting time = 0.00 s

Total time = 163.19 s
first instance of v_init
first instance of tstop
