
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240418_Run1_debug_run/gen_2/gen_2_cand_0_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240418_Run1_debug_run/gen_2/gen_2_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240418_Run1_debug_run/240418_Run1_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240418_Run1_debug_run/netParams_popParams.json ... 

Start time:  2024-04-18 00:07:13.545550

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.04 s.
Making connections...
  Number of connections on node 0: 28375 
  Done; cell connection time = 5.60 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.07 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 96.75 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 6.52 s.

Analyzing...
  Cells: 400
  Connections: 28775 (71.94 per cell)
  Spikes: 4909 (12.27 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 96.75 s
   E : 19.290 Hz
   I : 0.352 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240418_Run1_debug_run/gen_2/gen_2_cand_0_data.json ... 
Finished saving!
  Done; saving time = 6.45 s.
  Done; plotting time = 0.00 s

Total time = 115.55 s
