
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run16_debug_node_run/gen_0/gen_0_cand_105_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run16_debug_node_run/gen_0/gen_0_cand_105_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run16_debug_node_run/240505_Run16_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run16_debug_node_run/netParams_popParams.json ... 
ADLFKJAS;DLFKJ

Start time:  2024-05-05 09:10:54.842903

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 4.04 s.
Making connections...
  Number of connections on node 0: 1143 
  Done; cell connection time = 63.15 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 15000.0 ms...
  Done; run time = 2923.16 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 3.13 s.

Analyzing...
  Cells: 400
  Connections: 1143 (2.86 per cell)
  Spikes: 569 (0.09 Hz)
  Simulated time: 15.0 s; 1 workers
  Run time: 2923.16 s
   E : 0.000 Hz
   I : 2.241 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run16_debug_node_run/gen_0/gen_0_cand_105_data.json ... 
Finished saving!
  Done; saving time = 23.21 s.
  Done; plotting time = 0.00 s

Total time = 3016.95 s
first instance of v_init
first instance of tstop
