
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_5/gen_5_cand_21_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_5/gen_5_cand_21_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 23:25:17.100618

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.09 s.
Making connections...
  Number of connections on node 0: 207 
  Done; cell connection time = 90.04 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 904.01 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.60 s.

Analyzing...
  Cells: 400
  Connections: 207 (0.52 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 904.01 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_5/gen_5_cand_21_data.json ... 
Finished saving!
  Done; saving time = 15.50 s.
  Done; plotting time = 0.00 s

Total time = 1014.25 s
first instance of v_init
first instance of tstop
