
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_3/gen_3_cand_24_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_3/gen_3_cand_24_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/240430_Run1_interactive_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 14:53:11.859161

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.35 s.
Making connections...
  Number of connections on node 0: 33478 
  Done; cell connection time = 11.99 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 1505.38 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 1.62 s.

Analyzing...
  Cells: 400
  Connections: 33478 (83.69 per cell)
  Spikes: 58423 (14.61 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 1505.38 s
   E : 43.627 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_3/gen_3_cand_24_data.json ... 
Finished saving!
  Done; saving time = 4.45 s.
  Done; plotting time = 0.00 s

Total time = 1523.84 s
