
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_1/gen_1_cand_95_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_1/gen_1_cand_95_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 03:29:21.940056

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 3.51 s.
Making connections...
  Number of connections on node 0: 421 
  Done; cell connection time = 108.89 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 3.70 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1534.60 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 4.92 s.

Analyzing...
  Cells: 400
  Connections: 821 (2.05 per cell)
  Spikes: 44469 (22.23 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1534.60 s
   E : 12.968 Hz
   I : 2.287 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_1/gen_1_cand_95_data.json ... 
Finished saving!
  Done; saving time = 15.93 s.
  Done; plotting time = 0.00 s

Total time = 1676.46 s
first instance of v_init
first instance of tstop
