
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_1/gen_1_cand_98_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_1/gen_1_cand_98_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 03:28:36.535045

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.60 s.
Making connections...
  Number of connections on node 0: 446 
  Done; cell connection time = 63.13 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 2.13 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 877.49 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.83 s.

Analyzing...
  Cells: 400
  Connections: 846 (2.12 per cell)
  Spikes: 136 (0.07 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 877.49 s
   E : 0.000 Hz
   I : 0.352 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_1/gen_1_cand_98_data.json ... 
Finished saving!
  Done; saving time = 6.02 s.
  Done; plotting time = 0.00 s

Total time = 953.32 s
first instance of v_init
first instance of tstop
