
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_4/gen_4_cand_17_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_4/gen_4_cand_17_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 06:38:41.062195

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 5.13 s.
Making connections...
  Number of connections on node 0: 278 
  Done; cell connection time = 141.96 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 5.31 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1874.57 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 5.18 s.

Analyzing...
  Cells: 400
  Connections: 678 (1.70 per cell)
  Spikes: 2227 (1.11 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1874.57 s
   E : 1.579 Hz
   I : 1.139 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_4/gen_4_cand_17_data.json ... 
Finished saving!
  Done; saving time = 11.49 s.
  Done; plotting time = 0.00 s

Total time = 2043.86 s
first instance of v_init
first instance of tstop
