
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_4/gen_4_cand_40_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_4/gen_4_cand_40_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 06:37:37.007654

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.50 s.
Making connections...
  Number of connections on node 0: 8563 
  Done; cell connection time = 143.98 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 2.88 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 3199.30 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 7.84 s.

Analyzing...
  Cells: 400
  Connections: 8963 (22.41 per cell)
  Spikes: 95030 (47.51 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 3199.30 s
   E : 37.246 Hz
   I : 7.704 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_4/gen_4_cand_40_data.json ... 
Finished saving!
  Done; saving time = 15.48 s.
  Done; plotting time = 0.00 s

Total time = 3372.66 s
first instance of v_init
first instance of tstop
