
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_4/gen_4_cand_123_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_4/gen_4_cand_123_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 06:39:16.216457

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 4.29 s.
Making connections...
  Number of connections on node 0: 160 
  Done; cell connection time = 136.41 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 5.09 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1757.33 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 5.27 s.

Analyzing...
  Cells: 400
  Connections: 560 (1.40 per cell)
  Spikes: 1415 (0.71 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1757.33 s
   E : 0.671 Hz
   I : 1.028 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_4/gen_4_cand_123_data.json ... 
Finished saving!
  Done; saving time = 11.87 s.
  Done; plotting time = 0.00 s

Total time = 1920.27 s
first instance of v_init
first instance of tstop
