
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_8/gen_8_cand_85_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_8/gen_8_cand_85_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-27 02:31:53.348096

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.72 s.
Making connections...
  Number of connections on node 0: 165 
  Done; cell connection time = 20.19 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.01 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 186.45 s; real-time ratio: 0.03.

Gathering data...
  Done; gather time = 0.66 s.

Analyzing...
  Cells: 400
  Connections: 165 (0.41 per cell)
  Spikes: 70259 (35.13 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 186.45 s
   E : 50.056 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_8/gen_8_cand_85_data.json ... 
Finished saving!
  Done; saving time = 5.36 s.
  Done; plotting time = 0.00 s

Total time = 214.44 s
first instance of v_init
first instance of tstop
