
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_8/gen_8_cand_9_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_8/gen_8_cand_9_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-27 02:32:03.889988

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 3.08 s.
Making connections...
  Number of connections on node 0: 332 
  Done; cell connection time = 82.96 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 928.84 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.78 s.

Analyzing...
  Cells: 400
  Connections: 332 (0.83 per cell)
  Spikes: 92851 (46.43 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 928.84 s
   E : 55.341 Hz
   I : 22.889 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_8/gen_8_cand_9_data.json ... 
Finished saving!
  Done; saving time = 23.13 s.
  Done; plotting time = 0.00 s

Total time = 1045.43 s
first instance of v_init
first instance of tstop
