
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run2_interactive_node_run/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run2_interactive_node_run/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run2_interactive_node_run/240505_Run2_interactive_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run2_interactive_node_run/netParams_popParams.json ... 
ADLFKJAS;DLFKJ

Start time:  2024-05-05 04:13:21.529588

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.03 s.
Making connections...
  Number of connections on node 0: 10103 
  Done; cell connection time = 1.76 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 134.93 s; real-time ratio: 0.07.

Gathering data...
  Done; gather time = 0.20 s.

Analyzing...
  Cells: 400
  Connections: 10103 (25.26 per cell)
  Spikes: 70212 (17.55 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 134.93 s
   E : 1.667 Hz
   I : 23.324 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run2_interactive_node_run/gen_0/gen_0_cand_2_data.json ... 
Finished saving!
  Done; saving time = 0.66 s.
  Done; plotting time = 0.00 s

Total time = 137.60 s
first instance of v_init
first instance of tstop
