
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run2_interactive_node_run/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run2_interactive_node_run/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run2_interactive_node_run/240505_Run2_interactive_node_run_netParams.py
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run2_interactive_node_run/netParams_popParams.json ... 
ADLFKJAS;DLFKJ

Start time:  2024-05-05 04:13:21.512219

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.03 s.
Making connections...
  Number of connections on node 0: 4521 
  Done; cell connection time = 1.22 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 71.68 s; real-time ratio: 0.14.

Gathering data...
  Done; gather time = 0.15 s.

Analyzing...
  Cells: 400
  Connections: 4521 (11.30 per cell)
  Spikes: 66943 (16.74 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 71.68 s
   E : 19.468 Hz
   I : 8.917 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240505_Run2_interactive_node_run/gen_0/gen_0_cand_0_data.json ... 
Finished saving!
  Done; saving time = 0.52 s.
  Done; plotting time = 0.00 s

Total time = 73.61 s
first instance of v_init
first instance of tstop
