numprocs=8

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/gen_0/gen_0_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/240422_Run14_MPIsxOMPs_1x8x8_netParams.py
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/240422_Run14_MPIsxOMPs_1x8x8_netParams.py
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/240422_Run14_MPIsxOMPs_1x8x8_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/240422_Run14_MPIsxOMPs_1x8x8_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/240422_Run14_MPIsxOMPs_1x8x8_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/240422_Run14_MPIsxOMPs_1x8x8_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/240422_Run14_MPIsxOMPs_1x8x8_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/netParams_popParams.json ... 

Start time:  2024-04-22 14:30:51.428728
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/240422_Run14_MPIsxOMPs_1x8x8_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/netParams_popParams.json ... 

Creating network of 2 cell populations on 8 hosts...
  Number of cells on node 0: 50 
  Done; cell creation time = 0.01 s.
Making connections...
  Number of cells on node 2: 50 
  Number of cells on node 6: 50 
  Number of cells on node 5: 50 
  Number of cells on node 3: 50 
  Number of cells on node 7: 50 
  Number of cells on node 1: 50 
  Number of cells on node 4: 50 
  Number of connections on node 0: 1541 
  Number of connections on node 6: 1544 
  Number of connections on node 1: 1540 
  Number of connections on node 4: 1591 
  Number of connections on node 2: 1616 
  Number of connections on node 5: 1560 
  Number of connections on node 3: 1624 
  Number of connections on node 7: 1471 
  Done; cell connection time = 1.64 s.
Adding stims...
  Number of stims on node 4: 50 
  Number of stims on node 1: 50 
  Number of stims on node 0: 50 
  Number of stims on node 2: 50 
  Number of stims on node 7: 50 
  Number of stims on node 6: 50 
  Number of stims on node 3: 50 
  Number of stims on node 5: 50 
  Done; cell stims creation time = 0.02 s.
Recording 0 traces of 0 types on node 6
Recording 0 traces of 0 types on node 4
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 1
Recording 0 traces of 0 types on node 7
Recording 0 traces of 0 types on node 2
Recording 0 traces of 0 types on node 5
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 30000.0 ms...
  Done; run time = 141.69 s; real-time ratio: 0.21.

Gathering data...
  Done; gather time = 0.46 s.

Analyzing...
  Cells: 400
  Connections: 12887 (32.22 per cell)
  Spikes: 280 (0.02 Hz)
  Simulated time: 30.0 s; 8 workers
  Run time: 141.69 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run14_MPIsxOMPs_1x8x8/gen_0/gen_0_cand_0_data.json ... 
Finished saving!
  Done; saving time = 0.82 s.
  Done; plotting time = 0.00 s

Total time = 145.80 s
