#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q debug
#SBATCH -J multi_thread_testing_2CPUperPop
#SBATCH --mail-user=amwe@ucdavis.edu
#SBATCH --mail-type=ALL
#SBATCH -t 00:15:00
#SBATCH --ntasks-per-node 4  # Number of tasks per node
#SBATCH --cpus-per-task 2  # Number of threads per task (2 threads per core)
#SBATCH --output=job_output_%j.txt # Standard output file
#SBATCH --error=job_error_%j.txt # Standard error output file

module load python
module load conda
module load openmpi

conda activate 2DSims

# OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

#run the application: 
#srun -n 256 -c 4 --cpu_bind=cores  NERSC/batchRun.py jobscript_test 30
python3 NERSC/batchRun.py multi_thread_testing_2CPUperPop 1