Initiating Rank: 1

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/240517_Run1_best_case_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 1: 25 
  Number of connections on node 1: 1978 
  Number of stims on node 1: 0 
Recording 0 traces of 0 types on node 1
Initiating Rank: 5

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/240517_Run1_best_case_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 5: 25 
  Number of connections on node 5: 1934 
  Number of stims on node 5: 0 
Recording 0 traces of 0 types on node 5
Initiating Rank: 7

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/240517_Run1_best_case_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 7: 25 
  Number of connections on node 7: 1836 
  Number of stims on node 7: 0 
Recording 0 traces of 0 types on node 7
Initiating Rank: 9

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/240517_Run1_best_case_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 9: 25 
  Number of connections on node 9: 1816 
  Number of stims on node 9: 0 
Recording 0 traces of 0 types on node 9
Initiating Rank: 13

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/240517_Run1_best_case_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 13: 25 
  Number of connections on node 13: 1876 
  Number of stims on node 13: 0 
Recording 0 traces of 0 types on node 13
Initiating Rank: 15

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/240517_Run1_best_case_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 15: 25 
  Number of connections on node 15: 1807 
  Number of stims on node 15: 0 
Recording 0 traces of 0 types on node 15
Initiating Rank: 3

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/240517_Run1_best_case_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 3: 25 
  Number of connections on node 3: 1950 
  Number of stims on node 3: 0 
Recording 0 traces of 0 types on node 3
Initiating Rank: 11

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/240517_Run1_best_case_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 11: 25 
  Number of connections on node 11: 1967 
  Number of stims on node 11: 0 
Recording 0 traces of 0 types on node 11
Initiating Rank: 4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/240517_Run1_best_case_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 4: 25 
  Number of connections on node 4: 1822 
  Number of stims on node 4: 0 
Recording 0 traces of 0 types on node 4
Initiating Rank: 6

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/240517_Run1_best_case_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 6: 25 
  Number of connections on node 6: 1949 
  Number of stims on node 6: 0 
Recording 0 traces of 0 types on node 6
Initiating Rank: 12

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/240517_Run1_best_case_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 12: 25 
  Number of connections on node 12: 1936 
  Number of stims on node 12: 0 
Recording 0 traces of 0 types on node 12
Initiating Rank: 2

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/240517_Run1_best_case_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 2: 25 
  Number of connections on node 2: 1917 
  Number of stims on node 2: 0 
Recording 0 traces of 0 types on node 2
Initiating Rank: 8

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/240517_Run1_best_case_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 8: 25 
  Number of connections on node 8: 1893 
  Number of stims on node 8: 0 
Recording 1 traces of 1 types on node 8
Initiating Rank: 10

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/240517_Run1_best_case_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 10: 25 
  Number of connections on node 10: 2006 
  Number of stims on node 10: 0 
Recording 0 traces of 0 types on node 10
Initiating Rank: 14

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/240517_Run1_best_case_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 14: 25 
  Number of connections on node 14: 1862 
  Number of stims on node 14: 0 
Recording 0 traces of 0 types on node 14
Initiating Rank: 0

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/240517_Run1_best_case_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/netParams_popParams.json ... 
ADLFKJAS;DLFKJ

Start time:  2024-05-17 16:04:59.412561

Creating network of 2 cell populations on 16 hosts...
  Number of cells on node 0: 25 
  Done; cell creation time = 0.00 s.
Making connections...
  Number of connections on node 0: 1940 
  Done; cell connection time = 0.88 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 1 traces of 1 types on node 0

Running simulation using NEURON for 120000.0 ms...
  Done; run time = 365.70 s; real-time ratio: 0.33.

Gathering data...
  Done; gather time = 1.57 s.

Analyzing...
  Cells: 400
  Connections: 30489 (76.22 per cell)
  Spikes: 576877 (12.02 Hz)
  Simulated time: 120.0 s; 16 workers
  Run time: 365.70 s
   E : 0.579 Hz
   I : 47.787 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240517_Run1_best_case/gen_0/gen_0_cand_6_data.json ... 
Finished saving!
  Done; saving time = 5.58 s.
  Done; plotting time = 0.00 s

Total time = 373.88 s
numprocs=16
