
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_12/gen_12_cand_70_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_12/gen_12_cand_70_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/240430_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 20:43:26.289290

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.18 s.
Making connections...
  Number of connections on node 0: 23090 
  Done; cell connection time = 13.08 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 1271.99 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 1.18 s.

Analyzing...
  Cells: 400
  Connections: 23090 (57.73 per cell)
  Spikes: 321723 (80.43 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 1271.99 s
   E : 94.659 Hz
   I : 0.963 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_12/gen_12_cand_70_data.json ... 
Finished saving!
  Done; saving time = 2.92 s.
  Done; plotting time = 0.00 s

Total time = 1289.82 s
