
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_12/gen_12_cand_78_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_12/gen_12_cand_78_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/240430_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 20:43:26.309110

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.16 s.
Making connections...
  Number of connections on node 0: 7845 
  Done; cell connection time = 4.87 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 521.01 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 0.67 s.

Analyzing...
  Cells: 400
  Connections: 7845 (19.61 per cell)
  Spikes: 1610 (0.40 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 521.01 s
   E : 0.012 Hz
   I : 10.463 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_12/gen_12_cand_78_data.json ... 
Finished saving!
  Done; saving time = 3.25 s.
  Done; plotting time = 0.00 s

Total time = 529.98 s
