
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_3/gen_3_cand_4_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_3/gen_3_cand_4_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 07:34:19.180872

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.20 s.
Making connections...
  Number of connections on node 0: 36457 
  Done; cell connection time = 26.77 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.45 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1724.38 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 23.38 s.

Analyzing...
  Cells: 400
  Connections: 36857 (92.14 per cell)
  Spikes: 19920 (9.96 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1724.38 s
   E : 0.567 Hz
   I : 18.796 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_3/gen_3_cand_4_data.json ... 
Finished saving!
  Done; saving time = 30.03 s.
  Done; plotting time = 0.00 s

Total time = 1805.43 s
first instance of v_init
first instance of tstop
