
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_3/gen_3_cand_67_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_3/gen_3_cand_67_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 07:34:18.282760

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.10 s.
Making connections...
  Number of connections on node 0: 25694 
  Done; cell connection time = 8.27 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.08 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 593.90 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 1.44 s.

Analyzing...
  Cells: 400
  Connections: 26094 (65.23 per cell)
  Spikes: 5339 (2.67 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 593.90 s
   E : 0.000 Hz
   I : 10.213 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_3/gen_3_cand_67_data.json ... 
Finished saving!
  Done; saving time = 2.09 s.
  Done; plotting time = 0.00 s

Total time = 605.89 s
first instance of v_init
first instance of tstop
