
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run25_debug_run/gen_0/gen_0_cand_7_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run25_debug_run/gen_0/gen_0_cand_7_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run25_debug_run/240417_Run25_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run25_debug_run/netParams_popParams.json ... 

Start time:  2024-04-17 23:24:26.471945

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.04 s.
Making connections...
  Number of connections on node 0: 27502 
  Done; cell connection time = 4.54 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.07 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 65.59 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 0.77 s.

Analyzing...
  Cells: 400
  Connections: 27902 (69.75 per cell)
  Spikes: 7224 (18.06 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 65.59 s
   E : 22.929 Hz
   I : 2.157 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run25_debug_run/gen_0/gen_0_cand_7_data.json ... 
Finished saving!
  Done; saving time = 0.88 s.
  Done; plotting time = 0.00 s

Total time = 71.91 s
