
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run25_debug_run/gen_0/gen_0_cand_1_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run25_debug_run/gen_0/gen_0_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run25_debug_run/240417_Run25_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run25_debug_run/netParams_popParams.json ... 

Start time:  2024-04-17 23:24:18.829822

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.03 s.
Making connections...
  Number of connections on node 0: 40379 
  Done; cell connection time = 5.28 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.06 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 99.35 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 0.87 s.

Analyzing...
  Cells: 400
  Connections: 40779 (101.95 per cell)
  Spikes: 14967 (37.42 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 99.35 s
   E : 55.313 Hz
   I : 0.000 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run25_debug_run/gen_0/gen_0_cand_1_data.json ... 
Finished saving!
  Done; saving time = 1.03 s.
  Done; plotting time = 0.00 s

Total time = 106.64 s
