
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_13/gen_13_cand_27_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_13/gen_13_cand_27_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-27 07:44:01.008409

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.89 s.
Making connections...
  Number of connections on node 0: 1884 
  Done; cell connection time = 94.50 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1602.44 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 3.97 s.

Analyzing...
  Cells: 400
  Connections: 1884 (4.71 per cell)
  Spikes: 953 (0.48 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1602.44 s
   E : 0.000 Hz
   I : 5.398 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_13/gen_13_cand_27_data.json ... 
Finished saving!
  Done; saving time = 12.65 s.
  Done; plotting time = 0.00 s

Total time = 1719.06 s
first instance of v_init
first instance of tstop
