
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_13/gen_13_cand_26_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_13/gen_13_cand_26_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-27 07:43:50.035798

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.64 s.
Making connections...
  Number of connections on node 0: 248 
  Done; cell connection time = 45.84 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 544.50 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 1.75 s.

Analyzing...
  Cells: 400
  Connections: 248 (0.62 per cell)
  Spikes: 78022 (39.01 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 544.50 s
   E : 51.802 Hz
   I : 8.213 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_13/gen_13_cand_26_data.json ... 
Finished saving!
  Done; saving time = 14.03 s.
  Done; plotting time = 0.00 s

Total time = 611.71 s
first instance of v_init
first instance of tstop
