
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_13/gen_13_cand_5_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_13/gen_13_cand_5_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-27 07:43:30.407766

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.82 s.
Making connections...
  Number of connections on node 0: 174 
  Done; cell connection time = 77.62 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 850.37 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.52 s.

Analyzing...
  Cells: 400
  Connections: 174 (0.43 per cell)
  Spikes: 68035 (34.02 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 850.37 s
   E : 47.917 Hz
   I : 1.046 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_13/gen_13_cand_5_data.json ... 
Finished saving!
  Done; saving time = 20.90 s.
  Done; plotting time = 0.00 s

Total time = 958.56 s
first instance of v_init
first instance of tstop
