
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240424_Run2_test/gen_0/gen_0_cand_0_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240424_Run2_test/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240424_Run2_test/240424_Run2_test_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240424_Run2_test/netParams_popParams.json ... 

Start time:  2024-04-24 15:24:27.697395

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.03 s.
Making connections...
  Number of connections on node 0: 13760 
  Done; cell connection time = 2.56 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.03 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 142.02 s; real-time ratio: 0.04.

Gathering data...
  Done; gather time = 0.34 s.

Analyzing...
  Cells: 400
  Connections: 14160 (35.40 per cell)
  Spikes: 130101 (65.05 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 142.02 s
   E : 74.909 Hz
   I : 14.306 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240424_Run2_test/gen_0/gen_0_cand_0_data.json ... 
Finished saving!
  Done; saving time = 0.59 s.
  Done; plotting time = 0.00 s

Total time = 145.73 s
