
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run11_testing_run_name/gen_0/gen_0_cand_3_cfg.json
Loading file /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run11_testing_run_name/gen_0/gen_0_cand_3_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run11_testing_run_name/240414_Run11_testing_run_name_netParams.py
Duration: 1 seconds
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run11_testing_run_name/netParams_popParams.json ... 

Start time:  2024-04-14 01:12:03.390025

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.03 s.
Making connections...
  Number of connections on node 0: 46553 
  Done; cell connection time = 5.24 s.
Adding stims...
  Number of stims on node 0: 800 
  Done; cell stims creation time = 0.06 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 30000.0 ms...
  Done; run time = 6294.92 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 2.51 s.

Analyzing...
  Cells: 400
  Connections: 46953 (117.38 per cell)
  Synaptic contacts: 47353 (118.38 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 30.0 s; 1 workers
  Run time: 6294.92 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run11_testing_run_name/gen_0/gen_0_cand_3_data.json ... 
Finished saving!
  Done; saving time = 2.40 s.
  Done; plotting time = 0.00 s

Total time = 6305.18 s
