
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/InhibNeuronDebug/output/240430_Run1_debug_run/gen_3/gen_3_cand_7_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/InhibNeuronDebug/output/240430_Run1_debug_run/gen_3/gen_3_cand_7_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/InhibNeuronDebug/output/240430_Run1_debug_run/240430_Run1_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/InhibNeuronDebug/output/240430_Run1_debug_run/netParams_popParams.json ... 

Start time:  2024-04-30 13:44:24.649023

Creating network of 1 cell populations on 1 hosts...
  Number of cells on node 0: 1 
  Done; cell creation time = 0.00 s.
Making connections...
  Number of connections on node 0: 0 
  Done; cell connection time = 0.00 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 0.01 s; real-time ratio: 112.96.

Gathering data...
  Done; gather time = 0.00 s.

Analyzing...
  Cells: 1
  Connections: 0 (0.00 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 0.01 s
   I : 0.000 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/InhibNeuronDebug/output/240430_Run1_debug_run/gen_3/gen_3_cand_7_data.json ... 
Finished saving!
  Done; saving time = 0.02 s.
  Done; plotting time = 0.00 s

Total time = 0.04 s
