
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_75_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_75_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 02:25:38.832570

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 4.10 s.
Making connections...
  Number of connections on node 0: 5683 
  Done; cell connection time = 201.86 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 4.49 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 6150.40 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 26.54 s.

Analyzing...
  Cells: 400
  Connections: 6083 (15.21 per cell)
  Spikes: 72888 (36.44 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 6150.40 s
   E : 62.948 Hz
   I : 7.231 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_75_data.json ... 
Finished saving!
  Done; saving time = 50.79 s.
  Done; plotting time = 0.00 s

Total time = 6441.22 s
first instance of v_init
first instance of tstop
