
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_126_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_126_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 02:24:59.076309

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.82 s.
Making connections...
  Number of connections on node 0: 25225 
  Done; cell connection time = 276.68 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 2.84 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 13628.96 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 33.30 s.

Analyzing...
  Cells: 400
  Connections: 25625 (64.06 per cell)
  Spikes: 54561 (27.28 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 13628.96 s
   E : 31.282 Hz
   I : 20.565 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_126_data.json ... 
Finished saving!
  Done; saving time = 40.37 s.
  Done; plotting time = 0.00 s

Total time = 13985.80 s
first instance of v_init
first instance of tstop
