
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_52_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_52_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 02:24:23.289905

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.71 s.
Making connections...
  Number of connections on node 0: 25929 
  Done; cell connection time = 282.64 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 2.81 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 11532.57 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 48.77 s.

Analyzing...
  Cells: 400
  Connections: 26329 (65.82 per cell)
  Spikes: 469 (0.23 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 11532.57 s
   E : 0.000 Hz
   I : 0.889 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_52_data.json ... 
Finished saving!
  Done; saving time = 53.56 s.
  Done; plotting time = 0.00 s

Total time = 11922.31 s
first instance of v_init
first instance of tstop
