
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240428_Run5_interactive_debug/gen_0/gen_0_cand_52_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240428_Run5_interactive_debug/gen_0/gen_0_cand_52_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240428_Run5_interactive_debug/240428_Run5_interactive_debug_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240428_Run5_interactive_debug/netParams_popParams.json ... 

Start time:  2024-04-28 23:57:22.420586

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.07 s.
Making connections...
  Number of connections on node 0: 11203 
  Done; cell connection time = 4.21 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 153.04 s; real-time ratio: 0.03.

Gathering data...
  Done; gather time = 0.56 s.

Analyzing...
  Cells: 400
  Connections: 11203 (28.01 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 153.04 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240428_Run5_interactive_debug/gen_0/gen_0_cand_52_data.json ... 
Finished saving!
  Done; saving time = 1.04 s.
  Done; plotting time = 0.00 s

Total time = 158.94 s
first instance of v_init
first instance of tstop
