
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_3/gen_3_cand_10_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_3/gen_3_cand_10_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 07:32:45.896236

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.11 s.
Making connections...
  Number of connections on node 0: 8160 
  Done; cell connection time = 3.77 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.09 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 142.10 s; real-time ratio: 0.04.

Gathering data...
  Done; gather time = 1.16 s.

Analyzing...
  Cells: 400
  Connections: 8560 (21.40 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 142.10 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_3/gen_3_cand_10_data.json ... 
Finished saving!
  Done; saving time = 1.74 s.
  Done; plotting time = 0.00 s

Total time = 149.00 s
first instance of v_init
first instance of tstop
