
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_3/gen_3_cand_65_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_3/gen_3_cand_65_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 07:35:42.002098

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.16 s.
Making connections...
  Number of connections on node 0: 524 
  Done; cell connection time = 4.41 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.16 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 65.70 s; real-time ratio: 0.08.

Gathering data...
  Done; gather time = 0.24 s.

Analyzing...
  Cells: 400
  Connections: 924 (2.31 per cell)
  Spikes: 93021 (46.51 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 65.70 s
   E : 62.774 Hz
   I : 7.009 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_3/gen_3_cand_65_data.json ... 
Finished saving!
  Done; saving time = 1.20 s.
  Done; plotting time = 0.00 s

Total time = 72.19 s
first instance of v_init
first instance of tstop
