
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run6_test_uneven/gen_0/gen_0_cand_1_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run6_test_uneven/gen_0/gen_0_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run6_test_uneven/240424_Run6_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run6_test_uneven/netParams_popParams.json ... 

Start time:  2024-04-24 17:08:31.696222

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.04 s.
Making connections...
  Number of connections on node 0: 12412 
  Done; cell connection time = 2.07 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.03 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 93.41 s; real-time ratio: 0.05.

Gathering data...
  Done; gather time = 0.29 s.

Analyzing...
  Cells: 400
  Connections: 12812 (32.03 per cell)
  Spikes: 53492 (26.75 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 93.41 s
   E : 63.694 Hz
   I : 14.630 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run6_test_uneven/gen_0/gen_0_cand_1_data.json ... 
Finished saving!
  Done; saving time = 0.69 s.
  Done; plotting time = 0.00 s

Total time = 96.59 s
first instance of v_init
first instance of tstop
