
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run2_overnightRun24Apr_1x128/gen_0/gen_0_cand_27_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run2_overnightRun24Apr_1x128/gen_0/gen_0_cand_27_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run2_overnightRun24Apr_1x128/240425_Run2_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run2_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 02:03:38.953656

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.43 s.
Making connections...
  Number of connections on node 0: 2764 
  Done; cell connection time = 93.17 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 2.91 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 2085.32 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 11.58 s.

Analyzing...
  Cells: 400
  Connections: 3164 (7.91 per cell)
  Spikes: 86419 (43.21 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 2085.32 s
   E : 28.107 Hz
   I : 12.176 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run2_overnightRun24Apr_1x128/gen_0/gen_0_cand_27_data.json ... 
Finished saving!
  Done; saving time = 21.95 s.
  Done; plotting time = 0.00 s

Total time = 2218.57 s
first instance of v_init
first instance of tstop
