
=================================   JOB MAP   =================================
Data for JOB prterun-nid006932-2154218@1 offset 0 Total slots allocated 256
Mapper requested: NULL  Last mapper: ppr  Mapping policy: BYCORE:NOOVERSUBSCRIBE  Ranking policy: SLOT
Binding policy: CORE  Cpu set: N/A  PPR: 1:core  Cpus-per-rank: N/A  Cpu Type: HWT
Num new daemons: 0	New daemon starting vpid INVALID
Num nodes: 1

Data for node: nid006932	State: 3	Flags: DAEMON_LAUNCHED:LOCATION_VERIFIED:MAPPED:SLOTS_GIVEN
                resolved from nid006932
        Daemon: [prterun-nid006932-2154218@0,0]	Daemon launched: True
            Num slots: 256	Slots in use: 32	Oversubscribed: FALSE
            Num slots allocated: 256	Max slots: 0	Num procs: 32
        Data for proc: [prterun-nid006932-2154218@1,0]
                Pid: 0	Local rank: 0	Node rank: 0	App rank: 0
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:0,128]
        Data for proc: [prterun-nid006932-2154218@1,1]
                Pid: 0	Local rank: 1	Node rank: 1	App rank: 1
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:1,129]
        Data for proc: [prterun-nid006932-2154218@1,2]
                Pid: 0	Local rank: 2	Node rank: 2	App rank: 2
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:2,130]
        Data for proc: [prterun-nid006932-2154218@1,3]
                Pid: 0	Local rank: 3	Node rank: 3	App rank: 3
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:3,131]
        Data for proc: [prterun-nid006932-2154218@1,4]
                Pid: 0	Local rank: 4	Node rank: 4	App rank: 4
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:4,132]
        Data for proc: [prterun-nid006932-2154218@1,5]
                Pid: 0	Local rank: 5	Node rank: 5	App rank: 5
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:5,133]
        Data for proc: [prterun-nid006932-2154218@1,6]
                Pid: 0	Local rank: 6	Node rank: 6	App rank: 6
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:6,134]
        Data for proc: [prterun-nid006932-2154218@1,7]
                Pid: 0	Local rank: 7	Node rank: 7	App rank: 7
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:7,135]
        Data for proc: [prterun-nid006932-2154218@1,8]
                Pid: 0	Local rank: 8	Node rank: 8	App rank: 8
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:8,136]
        Data for proc: [prterun-nid006932-2154218@1,9]
                Pid: 0	Local rank: 9	Node rank: 9	App rank: 9
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:9,137]
        Data for proc: [prterun-nid006932-2154218@1,10]
                Pid: 0	Local rank: 10	Node rank: 10	App rank: 10
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:10,138]
        Data for proc: [prterun-nid006932-2154218@1,11]
                Pid: 0	Local rank: 11	Node rank: 11	App rank: 11
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:11,139]
        Data for proc: [prterun-nid006932-2154218@1,12]
                Pid: 0	Local rank: 12	Node rank: 12	App rank: 12
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:12,140]
        Data for proc: [prterun-nid006932-2154218@1,13]
                Pid: 0	Local rank: 13	Node rank: 13	App rank: 13
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:13,141]
        Data for proc: [prterun-nid006932-2154218@1,14]
                Pid: 0	Local rank: 14	Node rank: 14	App rank: 14
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:14,142]
        Data for proc: [prterun-nid006932-2154218@1,15]
                Pid: 0	Local rank: 15	Node rank: 15	App rank: 15
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:15,143]
        Data for proc: [prterun-nid006932-2154218@1,16]
                Pid: 0	Local rank: 16	Node rank: 16	App rank: 16
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:16,144]
        Data for proc: [prterun-nid006932-2154218@1,17]
                Pid: 0	Local rank: 17	Node rank: 17	App rank: 17
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:17,145]
        Data for proc: [prterun-nid006932-2154218@1,18]
                Pid: 0	Local rank: 18	Node rank: 18	App rank: 18
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:18,146]
        Data for proc: [prterun-nid006932-2154218@1,19]
                Pid: 0	Local rank: 19	Node rank: 19	App rank: 19
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:19,147]
        Data for proc: [prterun-nid006932-2154218@1,20]
                Pid: 0	Local rank: 20	Node rank: 20	App rank: 20
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:20,148]
        Data for proc: [prterun-nid006932-2154218@1,21]
                Pid: 0	Local rank: 21	Node rank: 21	App rank: 21
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:21,149]
        Data for proc: [prterun-nid006932-2154218@1,22]
                Pid: 0	Local rank: 22	Node rank: 22	App rank: 22
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:22,150]
        Data for proc: [prterun-nid006932-2154218@1,23]
                Pid: 0	Local rank: 23	Node rank: 23	App rank: 23
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:23,151]
        Data for proc: [prterun-nid006932-2154218@1,24]
                Pid: 0	Local rank: 24	Node rank: 24	App rank: 24
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:24,152]
        Data for proc: [prterun-nid006932-2154218@1,25]
                Pid: 0	Local rank: 25	Node rank: 25	App rank: 25
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:25,153]
        Data for proc: [prterun-nid006932-2154218@1,26]
                Pid: 0	Local rank: 26	Node rank: 26	App rank: 26
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:26,154]
        Data for proc: [prterun-nid006932-2154218@1,27]
                Pid: 0	Local rank: 27	Node rank: 27	App rank: 27
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:27,155]
        Data for proc: [prterun-nid006932-2154218@1,28]
                Pid: 0	Local rank: 28	Node rank: 28	App rank: 28
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:28,156]
        Data for proc: [prterun-nid006932-2154218@1,29]
                Pid: 0	Local rank: 29	Node rank: 29	App rank: 29
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:29,157]
        Data for proc: [prterun-nid006932-2154218@1,30]
                Pid: 0	Local rank: 30	Node rank: 30	App rank: 30
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:30,158]
        Data for proc: [prterun-nid006932-2154218@1,31]
                Pid: 0	Local rank: 31	Node rank: 31	App rank: 31
                State: INITIALIZED	App_context: 0
        	Binding: package[0][hwt:31,159]

=============================================================
numprocs=32

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Loading simConfig...
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 

Start time:  2024-04-22 17:49:55.924456

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/240422_Run27_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run27_test_uneven/netParams_popParams.json ... 

Creating network of 2 cell populations on 32 hosts...
  Number of cells on node 18: 12 
  Number of cells on node 2: 13 
  Number of cells on node 26: 12 
  Number of cells on node 13: 13 
  Number of cells on node 31: 12 
  Number of cells on node 10: 13 
  Number of cells on node 29: 12 
  Number of cells on node 25: 12 
  Number of cells on node 5: 13 
  Number of cells on node 27: 12 
  Number of cells on node 7: 13 
  Number of cells on node 23: 12 
  Number of cells on node 15: 13 
  Number of cells on node 21: 12 
  Number of cells on node 0: 13 
  Number of cells on node 17: 12 
  Number of cells on node 3: 13 
  Number of cells on node 19: 12 
  Number of cells on node 9: 13 
  Number of cells on node 20: 12 
  Number of cells on node 1: 13 
  Number of cells on node 11: 13 
  Number of cells on node 16: 12 
  Number of cells on node 30: 12 
  Number of cells on node 14: 13 
  Number of cells on node 22: 12 
  Number of cells on node 24: 12 
  Number of cells on node 28: 12 
  Number of cells on node 8: 13 
  Number of cells on node 4: 13 
  Number of cells on node 6: 13 
  Number of cells on node 12: 13 
  Done; cell creation time = 0.09 s.
Making connections...
  Number of connections on node 5: 421 
  Number of connections on node 20: 418 
  Number of connections on node 2: 482 
  Number of connections on node 27: 410 
  Number of connections on node 25: 420 
  Number of connections on node 22: 464 
  Number of connections on node 23: 453 
  Number of connections on node 4: 518 
  Number of connections on node 15: 435 
  Number of connections on node 18: 450 
  Number of connections on node 16: 482 
  Number of connections on node 13: 515 
  Number of connections on node 11: 493 
  Number of connections on node 14: 490 
  Number of connections on node 30: 410 
  Number of connections on node 29: 432 
  Number of connections on node 19: 489 
  Number of connections on node 28: 507 
  Number of connections on node 21: 519 
  Number of connections on node 8: 512 
  Number of connections on node 12: 480 
  Number of connections on node 31: 443 
  Number of connections on node 26: 469 
  Number of connections on node 24: 442 
  Number of connections on node 7: 485 
  Number of connections on node 9: 498 
  Number of connections on node 10: 527 
  Number of connections on node 17: 435 
  Number of connections on node 3: 495 
  Number of connections on node 6: 484 
  Number of connections on node 0: 511 
  Number of connections on node 1: 536 
  Done; cell connection time = 2.54 s.
Adding stims...
  Number of stims on node 27: 12 
  Number of stims on node 16: 12 
  Number of stims on node 25: 12 
  Number of stims on node 19: 12 
  Number of stims on node 20: 12 
  Number of stims on node 17: 12 
  Number of stims on node 1: 13 
  Number of stims on node 9: 13 
  Number of stims on node 0: 13 
  Number of stims on node 28: 12 
  Number of stims on node 8: 13 
  Number of stims on node 11: 13 
  Number of stims on node 3: 13 
  Number of stims on node 4: 13 
  Number of stims on node 23: 12 
  Number of stims on node 31: 12 
  Number of stims on node 7: 13 
  Number of stims on node 24: 12 
  Number of stims on node 22: 12 
  Number of stims on node 6: 13 
  Number of stims on node 21: 12 
  Number of stims on node 5: 13 
  Number of stims on node 29: 12 
  Number of stims on node 13: 13 
  Number of stims on node 12: 13 
  Number of stims on node 26: 12 
  Number of stims on node 18: 12 
  Number of stims on node 10: 13 
  Number of stims on node 2: 13 
  Number of stims on node 30: 12 
  Number of stims on node 14: 13 
  Number of stims on node 15: 13 
Recording 0 traces of 0 types on node 20
Recording 0 traces of 0 types on node 12
Recording 0 traces of 0 types on node 4
Recording 0 traces of 0 types on node 28
Recording 0 traces of 0 types on node 15
Recording 0 traces of 0 types on node 27
Recording 0 traces of 0 types on node 19
Recording 0 traces of 0 types on node 11
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 31
Recording 0 traces of 0 types on node 23
Recording 0 traces of 0 types on node 24
Recording 0 traces of 0 types on node 22
Recording 0 traces of 0 types on node 8
Recording 0 traces of 0 types on node 6
Recording 0 traces of 0 types on node 7
Recording 0 traces of 0 types on node 5
Recording 0 traces of 0 types on node 21
Recording 0 traces of 0 types on node 10
Recording 0 traces of 0 types on node 18
Recording 0 traces of 0 types on node 26
Recording 0 traces of 0 types on node 2
Recording 0 traces of 0 types on node 14
Recording 0 traces of 0 types on node 25
Recording 0 traces of 0 types on node 30
  Done; cell stims creation time = 0.12 s.
Recording 0 traces of 0 types on node 9
Recording 0 traces of 0 types on node 29
Recording 0 traces of 0 types on node 16
Recording 0 traces of 0 types on node 17
Recording 0 traces of 0 types on node 13
Recording 0 traces of 0 types on node 0
Recording 0 traces of 0 types on node 1

Running simulation using NEURON for 30000.0 ms...
