numprocs=4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_0/gen_0_cand_12_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_0/gen_0_cand_12_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_0/gen_0_cand_12_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_0/gen_0_cand_12_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_0/gen_0_cand_12_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_0/gen_0_cand_12_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_0/gen_0_cand_12_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_0/gen_0_cand_12_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 

Start time:  2024-04-22 12:56:19.590684

Creating network of 2 cell populations on 4 hosts...
  Number of cells on node 1: 100 
  Number of cells on node 3: 100 
  Number of cells on node 2: 100 
  Number of cells on node 0: 100 
  Done; cell creation time = 0.09 s.
Making connections...
  Number of connections on node 2: 1289 
  Number of connections on node 3: 1252 
  Number of connections on node 0: 1332 
  Number of connections on node 1: 1277 
  Done; cell connection time = 4.11 s.
Adding stims...
  Number of stims on node 0: 100 
  Number of stims on node 2: 100 
  Number of stims on node 3: 100 
  Number of stims on node 1: 100 
  Done; cell stims creation time = 0.14 s.
Recording 0 traces of 0 types on node 0
Recording 0 traces of 0 types on node 2
Recording 0 traces of 0 types on node 1
Recording 0 traces of 0 types on node 3

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 58.30 s; real-time ratio: 0.09.

Gathering data...
  Done; gather time = 0.87 s.

Analyzing...
  Cells: 400
  Connections: 5550 (13.88 per cell)
  Spikes: 121023 (60.51 Hz)
  Simulated time: 5.0 s; 4 workers
  Run time: 58.30 s
   E : 18.167 Hz
   I : 7.519 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_0/gen_0_cand_12_data.json ... 
Finished saving!
  Done; saving time = 1.69 s.
  Done; plotting time = 0.00 s

Total time = 65.28 s
