
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_7/gen_7_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_7/gen_7_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/240430_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 17:41:08.836793

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.48 s.
Making connections...
  Number of connections on node 0: 7650 
  Done; cell connection time = 11.06 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 554.83 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 1.00 s.

Analyzing...
  Cells: 400
  Connections: 7650 (19.12 per cell)
  Spikes: 1295 (0.32 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 554.83 s
   E : 0.000 Hz
   I : 6.935 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_7/gen_7_cand_58_data.json ... 
Finished saving!
  Done; saving time = 2.23 s.
  Done; plotting time = 0.00 s

Total time = 569.62 s
