
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_7/gen_7_cand_51_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_7/gen_7_cand_51_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/240430_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 17:40:59.108928

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.23 s.
Making connections...
  Number of connections on node 0: 15585 
  Done; cell connection time = 15.39 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 970.56 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 0.96 s.

Analyzing...
  Cells: 400
  Connections: 15585 (38.96 per cell)
  Spikes: 90346 (22.59 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 970.56 s
   E : 52.984 Hz
   I : 2.889 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_7/gen_7_cand_51_data.json ... 
Finished saving!
  Done; saving time = 3.99 s.
  Done; plotting time = 0.00 s

Total time = 991.30 s
