
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run10_testing_run_name/gen_3/gen_3_cand_0_cfg.json
Loading file /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run10_testing_run_name/gen_3/gen_3_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run10_testing_run_name/240414_Run10_testing_run_name_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run10_testing_run_name/netParams_popParams.json ... 
Duration: 1.0 seconds

Start time:  2024-04-14 01:11:38.997439

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.03 s.
Making connections...
  Number of connections on node 0: 3147 
  Done; cell connection time = 1.15 s.
Adding stims...
  Number of stims on node 0: 800 
  Done; cell stims creation time = 0.06 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 5.82 s; real-time ratio: 0.17.

Gathering data...
  Done; gather time = 0.18 s.

Analyzing...
  Cells: 400
  Connections: 3547 (8.87 per cell)
  Synaptic contacts: 3947 (9.87 per cell)
  Spikes: 405 (1.01 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 5.82 s
   E : 0.000 Hz
   I : 3.400 Hz
Saving output as /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run10_testing_run_name/gen_3/gen_3_cand_0_data.json ... 
Finished saving!
  Done; saving time = 0.16 s.
  Done; plotting time = 0.00 s

Total time = 7.40 s
