numprocs=4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/gen_1/gen_1_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/gen_1/gen_1_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/240422_Run16_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/netParams_popParams.json ... 

Start time:  2024-04-22 14:51:51.322554

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/gen_1/gen_1_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/gen_1/gen_1_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/240422_Run16_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/gen_1/gen_1_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/gen_1/gen_1_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/240422_Run16_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/gen_1/gen_1_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/gen_1/gen_1_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/240422_Run16_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/netParams_popParams.json ... 

Creating network of 2 cell populations on 4 hosts...
  Number of cells on node 0: 100 
  Done; cell creation time = 0.02 s.
Making connections...
  Number of cells on node 1: 100 
  Number of cells on node 2: 100 
  Number of cells on node 3: 100 
  Number of connections on node 3: 3554 
  Number of connections on node 0: 3674 
  Number of connections on node 2: 3632 
  Number of connections on node 1: 3587 
  Done; cell connection time = 1.21 s.
Adding stims...
  Number of stims on node 0: 100 
  Number of stims on node 1: 100 
  Number of stims on node 2: 100 
  Number of stims on node 3: 100 
  Done; cell stims creation time = 0.02 s.
Recording 0 traces of 0 types on node 0
Recording 0 traces of 0 types on node 1
Recording 0 traces of 0 types on node 2
Recording 0 traces of 0 types on node 3

Running simulation using NEURON for 30000.0 ms...
  Done; run time = 199.14 s; real-time ratio: 0.15.

Gathering data...
  Done; gather time = 0.86 s.

Analyzing...
  Cells: 400
  Connections: 14847 (37.12 per cell)
  Spikes: 498811 (41.57 Hz)
  Simulated time: 30.0 s; 4 workers
  Run time: 199.14 s
   E : 69.238 Hz
   I : 9.130 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/gen_1/gen_1_cand_0_data.json ... 
Finished saving!
  Done; saving time = 1.50 s.
  Done; plotting time = 0.00 s

Total time = 203.64 s
