numprocs=1
Warning: Could not import rxdmath module
Initiating Rank: 0

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /workspaces/2DNetworkSimulations/NERSC/output/240513_Run8_vscode_debug/gen_0/gen_0_cand_1_cfg.json
Loading file /workspaces/2DNetworkSimulations/NERSC/output/240513_Run8_vscode_debug/gen_0/gen_0_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /workspaces/2DNetworkSimulations/NERSC/output/240513_Run8_vscode_debug/240513_Run8_vscode_debug_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /workspaces/2DNetworkSimulations/NERSC/output/240513_Run8_vscode_debug/netParams_popParams.json ... 
ADLFKJAS;DLFKJ

Start time:  2024-05-13 10:06:13.286129

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.05 s.
Making connections...
  Number of connections on node 0: 23721 
  Done; cell connection time = 3.96 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0
