
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_5/gen_5_cand_5_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_5/gen_5_cand_5_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 07:39:59.526717

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.71 s.
Making connections...
  Number of connections on node 0: 133 
  Done; cell connection time = 41.88 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 1.90 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 850.31 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 3.27 s.

Analyzing...
  Cells: 400
  Connections: 533 (1.33 per cell)
  Spikes: 125454 (62.73 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 850.31 s
   E : 88.183 Hz
   I : 2.509 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_5/gen_5_cand_5_data.json ... 
Finished saving!
  Done; saving time = 18.86 s.
  Done; plotting time = 0.00 s

Total time = 924.65 s
first instance of v_init
first instance of tstop
