
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_5/gen_5_cand_114_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_5/gen_5_cand_114_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 07:42:34.592169

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 4.57 s.
Making connections...
  Number of connections on node 0: 315 
  Done; cell connection time = 130.64 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 4.80 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1686.16 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 4.99 s.

Analyzing...
  Cells: 400
  Connections: 715 (1.79 per cell)
  Spikes: 7014 (3.51 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1686.16 s
   E : 0.881 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_5/gen_5_cand_114_data.json ... 
Finished saving!
  Done; saving time = 11.70 s.
  Done; plotting time = 0.00 s

Total time = 1842.85 s
first instance of v_init
first instance of tstop
