numprocs=4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_10_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_10_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_10_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_10_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_10_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_10_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 

Start time:  2024-04-22 13:02:17.302990

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_10_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_10_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 

Creating network of 2 cell populations on 4 hosts...
  Number of cells on node 2: 100 
  Number of cells on node 0: 100 
  Number of cells on node 3: 100 
  Number of cells on node 1: 100 
  Done; cell creation time = 0.13 s.
Making connections...
  Number of connections on node 3: 1017 
  Number of connections on node 1: 1047 
  Number of connections on node 2: 1060 
  Number of connections on node 0: 1082 
  Done; cell connection time = 3.64 s.
Adding stims...
  Number of stims on node 1: 100 
  Number of stims on node 0: 100 
  Number of stims on node 3: 100 
  Number of stims on node 2: 100 
  Done; cell stims creation time = 0.14 s.
Recording 0 traces of 0 types on node 1
Recording 0 traces of 0 types on node 0
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 2

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 55.40 s; real-time ratio: 0.09.

Gathering data...
  Done; gather time = 0.77 s.

Analyzing...
  Cells: 400
  Connections: 4606 (11.52 per cell)
  Spikes: 114778 (57.39 Hz)
  Simulated time: 5.0 s; 4 workers
  Run time: 55.40 s
   E : 53.881 Hz
   I : 6.917 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_10_data.json ... 
Finished saving!
  Done; saving time = 0.88 s.
  Done; plotting time = 0.00 s

Total time = 61.58 s
