numprocs=4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_14_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_14_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_14_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_14_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_14_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_14_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_14_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_14_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 

Start time:  2024-04-22 13:02:17.498766

Creating network of 2 cell populations on 4 hosts...
  Number of cells on node 2: 100 
  Number of cells on node 0: 100 
  Done; cell creation time = 0.08 s.
Making connections...
  Number of cells on node 1: 100 
  Number of cells on node 3: 100 
  Number of connections on node 2: 2524 
  Number of connections on node 0: 2540 
  Number of connections on node 3: 2448 
  Number of connections on node 1: 2489 
  Done; cell connection time = 4.22 s.
Adding stims...
  Number of stims on node 3: 100 
  Number of stims on node 0: 100 
  Number of stims on node 1: 100 
  Number of stims on node 2: 100 
  Done; cell stims creation time = 0.13 s.
Recording 0 traces of 0 types on node 2
Recording 0 traces of 0 types on node 0
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 1

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 68.06 s; real-time ratio: 0.07.

Gathering data...
  Done; gather time = 0.58 s.

Analyzing...
  Cells: 400
  Connections: 10401 (26.00 per cell)
  Spikes: 100984 (50.49 Hz)
  Simulated time: 5.0 s; 4 workers
  Run time: 68.06 s
   E : 81.532 Hz
   I : 3.500 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_14_data.json ... 
Finished saving!
  Done; saving time = 1.10 s.
  Done; plotting time = 0.00 s

Total time = 74.33 s
