Hello from rank 0, thread 0, on nid004076. (core affinity = 0)
Hello from rank 0, thread 1, on nid004076. (core affinity = 64)
Hello from rank 10, thread 0, on nid004076. (core affinity = 0)
Hello from rank 10, thread 1, on nid004076. (core affinity = 64)
Hello from rank 11, thread 0, on nid004076. (core affinity = 0)
Hello from rank 11, thread 1, on nid004076. (core affinity = 64)
Hello from rank 12, thread 0, on nid004076. (core affinity = 0)
Hello from rank 12, thread 1, on nid004076. (core affinity = 64)
Hello from rank 13, thread 0, on nid004076. (core affinity = 0)
Hello from rank 13, thread 1, on nid004076. (core affinity = 64)
Hello from rank 14, thread 0, on nid004076. (core affinity = 0)
Hello from rank 14, thread 1, on nid004076. (core affinity = 64)
Hello from rank 15, thread 0, on nid004076. (core affinity = 0)
Hello from rank 15, thread 1, on nid004076. (core affinity = 64)
Hello from rank 16, thread 0, on nid004076. (core affinity = 0)
Hello from rank 16, thread 1, on nid004076. (core affinity = 64)
Hello from rank 17, thread 0, on nid004076. (core affinity = 0)
Hello from rank 17, thread 1, on nid004076. (core affinity = 64)
Hello from rank 18, thread 0, on nid004076. (core affinity = 0)
Hello from rank 18, thread 1, on nid004076. (core affinity = 64)
Hello from rank 19, thread 0, on nid004076. (core affinity = 0)
Hello from rank 19, thread 1, on nid004076. (core affinity = 64)
Hello from rank 1, thread 0, on nid004076. (core affinity = 0)
Hello from rank 1, thread 1, on nid004076. (core affinity = 64)
Hello from rank 20, thread 0, on nid004076. (core affinity = 0)
Hello from rank 20, thread 1, on nid004076. (core affinity = 64)
Hello from rank 21, thread 0, on nid004076. (core affinity = 0)
Hello from rank 21, thread 1, on nid004076. (core affinity = 64)
Hello from rank 22, thread 0, on nid004076. (core affinity = 0)
Hello from rank 22, thread 1, on nid004076. (core affinity = 64)
Hello from rank 23, thread 0, on nid004076. (core affinity = 0)
Hello from rank 23, thread 1, on nid004076. (core affinity = 64)
Hello from rank 24, thread 0, on nid004076. (core affinity = 0)
Hello from rank 24, thread 1, on nid004076. (core affinity = 64)
Hello from rank 25, thread 0, on nid004076. (core affinity = 0)
Hello from rank 25, thread 1, on nid004076. (core affinity = 64)
Hello from rank 26, thread 0, on nid004076. (core affinity = 0)
Hello from rank 26, thread 1, on nid004076. (core affinity = 64)
Hello from rank 27, thread 0, on nid004076. (core affinity = 0)
Hello from rank 27, thread 1, on nid004076. (core affinity = 64)
Hello from rank 28, thread 0, on nid004076. (core affinity = 0)
Hello from rank 28, thread 1, on nid004076. (core affinity = 64)
Hello from rank 29, thread 0, on nid004076. (core affinity = 0)
Hello from rank 29, thread 1, on nid004076. (core affinity = 64)
Hello from rank 2, thread 0, on nid004076. (core affinity = 0)
Hello from rank 2, thread 1, on nid004076. (core affinity = 64)
Hello from rank 30, thread 0, on nid004076. (core affinity = 0)
Hello from rank 30, thread 1, on nid004076. (core affinity = 64)
Hello from rank 31, thread 0, on nid004076. (core affinity = 0)
Hello from rank 31, thread 1, on nid004076. (core affinity = 64)
Hello from rank 3, thread 0, on nid004076. (core affinity = 0)
Hello from rank 3, thread 1, on nid004076. (core affinity = 64)
Hello from rank 4, thread 0, on nid004076. (core affinity = 0)
Hello from rank 4, thread 1, on nid004076. (core affinity = 64)
Hello from rank 5, thread 0, on nid004076. (core affinity = 0)
Hello from rank 5, thread 1, on nid004076. (core affinity = 64)
Hello from rank 6, thread 0, on nid004076. (core affinity = 0)
Hello from rank 6, thread 1, on nid004076. (core affinity = 64)
Hello from rank 7, thread 0, on nid004076. (core affinity = 0)
Hello from rank 7, thread 1, on nid004076. (core affinity = 64)
Hello from rank 8, thread 0, on nid004076. (core affinity = 0)
Hello from rank 8, thread 1, on nid004076. (core affinity = 64)
Hello from rank 9, thread 0, on nid004076. (core affinity = 0)
Hello from rank 9, thread 1, on nid004076. (core affinity = 64)
numprocs=32

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading simConfig...
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 
Loading file netParams_popParams.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 
Loading simConfig...
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_cfg.json ... 

Start time: Loading simConfig...
 2024-04-19 14:14:15.587217
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 

Creating network of 2 cell populations on 32 hosts...
  Number of cells on node 19: 12 
  Number of cells on node 3: 13 
  Number of cells on node 9: 13 
  Number of cells on node 31: 12 
  Number of cells on node 13: 13 
  Number of cells on node 15: 13 
  Number of cells on node 21: 12 
  Number of cells on node 17: 12 
  Number of cells on node 27: 12 
  Number of cells on node 23: 12 
  Number of cells on node 10: 13 
  Number of cells on node 12: 13 
  Number of cells on node 29: 12 
  Number of cells on node 6: 13 
  Number of cells on node 30: 12 
  Number of cells on node 8: 13 
  Number of cells on node 11: 13 
  Number of cells on node 7: 13 
  Number of cells on node 16: 12 
  Number of cells on node 1: 13 
  Number of cells on node 25: 12 
  Number of cells on node 28: 12 
  Number of cells on node 0: 13 
  Done; cell creation time = 0.00 s.
Making connections...
  Number of cells on node 4: 13 
  Number of cells on node 26: 12 
  Number of cells on node 2: 13 
  Number of cells on node 5: 13 
  Number of cells on node 18: 12 
  Number of cells on node 14: 13 
  Number of cells on node 24: 12 
  Number of cells on node 22: 12 
  Number of cells on node 20: 12 
  Number of connections on node 3: 248 
  Number of connections on node 19: 207 
  Number of connections on node 15: 230 
  Number of connections on node 22: 199 
  Number of connections on node 17: 183 
  Number of connections on node 16: 195 
  Number of connections on node 21: 225 
  Number of connections on node 14: 234 
  Number of connections on node 18: 210 
  Number of connections on node 23: 232 
  Number of connections on node 7: 253 
  Number of connections on node 10: 296 
  Number of connections on node 31: 232 
  Number of connections on node 9: 259 
  Number of connections on node 24: 251 
  Number of connections on node 13: 271 
  Number of connections on node 20: 198 
  Number of connections on node 4: 280 
  Number of connections on node 8: 281 
  Number of connections on node 11: 282 
  Number of connections on node 28: 266 
  Number of connections on node 29: 241 
  Number of connections on node 26: 275 
  Number of connections on node 25: 265 
  Number of connections on node 30: 270 
  Number of connections on node 2: 269 
  Number of connections on node 12: 286 
  Number of connections on node 0: 277 
  Number of connections on node 5: 269 
  Number of connections on node 1: 276 
  Number of connections on node 27: 272 
  Number of connections on node 6: 273 
  Done; cell connection time = 0.72 s.
Adding stims...
  Number of stims on node 21: 12 
  Number of stims on node 26: 12 
  Number of stims on node 23: 12 
  Number of stims on node 22: 12 
  Number of stims on node 19: 12 
  Number of stims on node 24: 12 
  Number of stims on node 18: 12 
  Number of stims on node 20: 12 
  Number of stims on node 17: 12 
  Number of stims on node 31: 12 
  Number of stims on node 28: 12 
  Number of stims on node 25: 12 
  Number of stims on node 7: 13 
  Number of stims on node 3: 13 
  Number of stims on node 6: 13 
  Number of stims on node 8: 13 
  Number of stims on node 12: 13 
  Number of stims on node 4: 13 
  Number of stims on node 0: 13 
  Number of stims on node 16: 12 
  Number of stims on node 5: 13 
  Number of stims on node 14: 13 
  Number of stims on node 9: 13 
  Number of stims on node 2: 13 
  Number of stims on node 1: 13 
  Number of stims on node 30: 12 
  Number of stims on node 11: 13 
  Number of stims on node 13: 13 
  Number of stims on node 10: 13 
  Number of stims on node 29: 12 
  Number of stims on node 27: 12 
  Number of stims on node 15: 13 
  Done; cell stims creation time = 0.01 s.
Recording 0 traces of 0 types on node 23
Recording 0 traces of 0 types on node 26
Recording 0 traces of 0 types on node 6
Recording 0 traces of 0 types on node 1
Recording 0 traces of 0 types on node 12
Recording 0 traces of 0 types on node 13
Recording 0 traces of 0 types on node 0
Recording 0 traces of 0 types on node 31
Recording 0 traces of 0 types on node 5
Recording 0 traces of 0 types on node 4
Recording 0 traces of 0 types on node 2
Recording 0 traces of 0 types on node 7
Recording 0 traces of 0 types on node 11
Recording 0 traces of 0 types on node 21
Recording 0 traces of 0 types on node 17
Recording 0 traces of 0 types on node 30
Recording 0 traces of 0 types on node 19
Recording 0 traces of 0 types on node 9
Recording 0 traces of 0 types on node 29
Recording 0 traces of 0 types on node 15
Recording 0 traces of 0 types on node 27
Recording 0 traces of 0 types on node 14
Recording 0 traces of 0 types on node 8
Recording 0 traces of 0 types on node 25
Recording 0 traces of 0 types on node 10
Recording 0 traces of 0 types on node 24
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 18
Recording 0 traces of 0 types on node 16
Recording 0 traces of 0 types on node 28
Recording 0 traces of 0 types on node 20
Recording 0 traces of 0 types on node 22

Running simulation using NEURON for 30000.0 ms...
  Done; run time = 15.11 s; real-time ratio: 1.98.

Gathering data...
  Done; gather time = 0.30 s.

Analyzing...
  Cells: 400
  Connections: 8405 (21.01 per cell)
  Spikes: 41139 (3.43 Hz)
  Simulated time: 30.0 s; 32 workers
  Run time: 15.11 s
   E : 0.857 Hz
   I : 4.704 Hz
Saving output as /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_1_data.json ... 
Finished saving!
  Done; saving time = 0.70 s.
  Done; plotting time = 0.00 s

Total time = 16.99 s
