Hello from rank 0, thread 0, on nid004076. (core affinity = 0)
Hello from rank 0, thread 1, on nid004076. (core affinity = 64)
Hello from rank 10, thread 0, on nid004076. (core affinity = 0)
Hello from rank 10, thread 1, on nid004076. (core affinity = 64)
Hello from rank 11, thread 0, on nid004076. (core affinity = 0)
Hello from rank 11, thread 1, on nid004076. (core affinity = 64)
Hello from rank 12, thread 0, on nid004076. (core affinity = 0)
Hello from rank 12, thread 1, on nid004076. (core affinity = 64)
Hello from rank 13, thread 0, on nid004076. (core affinity = 0)
Hello from rank 13, thread 1, on nid004076. (core affinity = 64)
Hello from rank 14, thread 0, on nid004076. (core affinity = 0)
Hello from rank 14, thread 1, on nid004076. (core affinity = 64)
Hello from rank 15, thread 0, on nid004076. (core affinity = 0)
Hello from rank 15, thread 1, on nid004076. (core affinity = 64)
Hello from rank 16, thread 0, on nid004076. (core affinity = 0)
Hello from rank 16, thread 1, on nid004076. (core affinity = 64)
Hello from rank 17, thread 0, on nid004076. (core affinity = 0)
Hello from rank 17, thread 1, on nid004076. (core affinity = 64)
Hello from rank 18, thread 0, on nid004076. (core affinity = 0)
Hello from rank 18, thread 1, on nid004076. (core affinity = 64)
Hello from rank 19, thread 0, on nid004076. (core affinity = 0)
Hello from rank 19, thread 1, on nid004076. (core affinity = 64)
Hello from rank 1, thread 0, on nid004076. (core affinity = 0)
Hello from rank 1, thread 1, on nid004076. (core affinity = 64)
Hello from rank 20, thread 0, on nid004076. (core affinity = 0)
Hello from rank 20, thread 1, on nid004076. (core affinity = 64)
Hello from rank 21, thread 0, on nid004076. (core affinity = 0)
Hello from rank 21, thread 1, on nid004076. (core affinity = 64)
Hello from rank 22, thread 0, on nid004076. (core affinity = 0)
Hello from rank 22, thread 1, on nid004076. (core affinity = 64)
Hello from rank 23, thread 0, on nid004076. (core affinity = 0)
Hello from rank 23, thread 1, on nid004076. (core affinity = 64)
Hello from rank 24, thread 0, on nid004076. (core affinity = 0)
Hello from rank 24, thread 1, on nid004076. (core affinity = 64)
Hello from rank 25, thread 0, on nid004076. (core affinity = 0)
Hello from rank 25, thread 1, on nid004076. (core affinity = 64)
Hello from rank 26, thread 0, on nid004076. (core affinity = 0)
Hello from rank 26, thread 1, on nid004076. (core affinity = 64)
Hello from rank 27, thread 0, on nid004076. (core affinity = 0)
Hello from rank 27, thread 1, on nid004076. (core affinity = 64)
Hello from rank 28, thread 0, on nid004076. (core affinity = 0)
Hello from rank 28, thread 1, on nid004076. (core affinity = 64)
Hello from rank 29, thread 0, on nid004076. (core affinity = 0)
Hello from rank 29, thread 1, on nid004076. (core affinity = 64)
Hello from rank 2, thread 0, on nid004076. (core affinity = 0)
Hello from rank 2, thread 1, on nid004076. (core affinity = 64)
Hello from rank 30, thread 0, on nid004076. (core affinity = 0)
Hello from rank 30, thread 1, on nid004076. (core affinity = 64)
Hello from rank 31, thread 0, on nid004076. (core affinity = 0)
Hello from rank 31, thread 1, on nid004076. (core affinity = 64)
Hello from rank 3, thread 0, on nid004076. (core affinity = 0)
Hello from rank 3, thread 1, on nid004076. (core affinity = 64)
Hello from rank 4, thread 0, on nid004076. (core affinity = 0)
Hello from rank 4, thread 1, on nid004076. (core affinity = 64)
Hello from rank 5, thread 0, on nid004076. (core affinity = 0)
Hello from rank 5, thread 1, on nid004076. (core affinity = 64)
Hello from rank 6, thread 0, on nid004076. (core affinity = 0)
Hello from rank 6, thread 1, on nid004076. (core affinity = 64)
Hello from rank 7, thread 0, on nid004076. (core affinity = 0)
Hello from rank 7, thread 1, on nid004076. (core affinity = 64)
Hello from rank 8, thread 0, on nid004076. (core affinity = 0)
Hello from rank 8, thread 1, on nid004076. (core affinity = 64)
Hello from rank 9, thread 0, on nid004076. (core affinity = 0)
Hello from rank 9, thread 1, on nid004076. (core affinity = 64)
numprocs=32

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Loading simConfig...
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 

Start time:  2024-04-19 14:13:19.766518
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading file netParams_popParams.json ... 
Loading simConfig...
Loading file netParams_popParams.json ... 
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 
Loading file netParams_popParams.json ... 
Loading simConfig...
Loading file netParams_popParams.json ... 
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/240419_Run14_mpi_interactive_test30_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/netParams_popParams.json ... 

Creating network of 2 cell populations on 32 hosts...
  Number of cells on node 0: 13 
  Number of cells on node 8: 13 
  Number of cells on node 2: 13 
  Number of cells on node 10: 13 
  Number of cells on node 12: 13 
  Number of cells on node 31: 12 
  Number of cells on node 15: 13 
  Number of cells on node 7: 13 
  Number of cells on node 1: 13 
  Number of cells on node 4: 13 
  Number of cells on node 6: 13 
  Number of cells on node 14: 13 
  Number of cells on node 11: 13 
  Number of cells on node 3: 13 
  Number of cells on node 13: 13 
  Number of cells on node 5: 13 
  Number of cells on node 9: 13 
  Number of cells on node 29: 12 
  Number of cells on node 24: 12 
  Number of cells on node 19: 12 
  Number of cells on node 28: 12 
  Number of cells on node 26: 12 
  Number of cells on node 30: 12 
  Number of cells on node 16: 12 
  Number of cells on node 20: 12 
  Number of cells on node 22: 12 
  Number of cells on node 23: 12 
  Number of cells on node 18: 12 
  Number of cells on node 17: 12 
  Number of cells on node 27: 12 
  Done; cell creation time = 0.00 s.
Making connections...
  Number of cells on node 25: 12 
  Number of cells on node 21: 12 
  Number of connections on node 15: 727 
  Number of connections on node 17: 694 
  Number of connections on node 27: 754 
  Number of connections on node 30: 665 
  Number of connections on node 31: 724 
  Number of connections on node 29: 735 
  Number of connections on node 7: 793 
  Number of connections on node 19: 779 
  Number of connections on node 13: 817 
  Number of connections on node 22: 782 
  Number of connections on node 8: 863 
  Number of connections on node 16: 767 
  Number of connections on node 1: 854 
  Number of connections on node 23: 752 
  Number of connections on node 5: 739 
  Number of connections on node 4: 827 
  Number of connections on node 9: 789 
  Number of connections on node 18: 699 
  Number of connections on node 25: 711 
  Number of connections on node 0: 857 
  Number of connections on node 10: 877 
  Number of connections on node 11: 865 
  Number of connections on node 24: 749 
  Number of connections on node 14: 800 
  Number of connections on node 6: 818 
  Number of connections on node 3: 817 
  Number of connections on node 12: 803 
  Number of connections on node 2: 828 
  Number of connections on node 20: 685 
  Number of connections on node 26: 811 
  Number of connections on node 21: 823 
  Number of connections on node 28: 835 
  Done; cell connection time = 0.77 s.
Adding stims...
  Number of stims on node 17: 12 
  Number of stims on node 22: 12 
  Number of stims on node 31: 12 
  Number of stims on node 29: 12 
  Number of stims on node 19: 12 
  Number of stims on node 0: 13 
  Number of stims on node 5: 13 
  Number of stims on node 25: 12 
  Number of stims on node 2: 13 
  Number of stims on node 10: 13 
  Number of stims on node 7: 13 
  Number of stims on node 15: 13 
  Number of stims on node 13: 13 
  Number of stims on node 18: 12 
  Number of stims on node 1: 13 
  Number of stims on node 3: 13 
  Number of stims on node 6: 13 
  Number of stims on node 11: 13 
  Number of stims on node 14: 13 
  Number of stims on node 21: 12 
  Number of stims on node 27: 12 
  Number of stims on node 30: 12 
  Number of stims on node 12: 13 
  Number of stims on node 4: 13 
  Number of stims on node 9: 13 
  Number of stims on node 26: 12 
  Number of stims on node 24: 12 
  Number of stims on node 23: 12 
  Number of stims on node 28: 12 
  Number of stims on node 20: 12 
  Number of stims on node 16: 12 
  Number of stims on node 8: 13 
  Done; cell stims creation time = 0.01 s.
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 5
Recording 0 traces of 0 types on node 19
Recording 0 traces of 0 types on node 6
Recording 0 traces of 0 types on node 17
Recording 0 traces of 0 types on node 22
Recording 0 traces of 0 types on node 1
Recording 0 traces of 0 types on node 25
Recording 0 traces of 0 types on node 31
Recording 0 traces of 0 types on node 4
Recording 0 traces of 0 types on node 0
Recording 0 traces of 0 types on node 8
Recording 0 traces of 0 types on node 10
Recording 0 traces of 0 types on node 13
Recording 0 traces of 0 types on node 2
Recording 0 traces of 0 types on node 9
Recording 0 traces of 0 types on node 12
Recording 0 traces of 0 types on node 29
Recording 0 traces of 0 types on node 11
Recording 0 traces of 0 types on node 14
Recording 0 traces of 0 types on node 21
Recording 0 traces of 0 types on node 18
Recording 0 traces of 0 types on node 28
Recording 0 traces of 0 types on node 26
Recording 0 traces of 0 types on node 23
Recording 0 traces of 0 types on node 15
Recording 0 traces of 0 types on node 27
Recording 0 traces of 0 types on node 30
Recording 0 traces of 0 types on node 7
Recording 0 traces of 0 types on node 16
Recording 0 traces of 0 types on node 20
Recording 0 traces of 0 types on node 24

Running simulation using NEURON for 30000.0 ms...
  Done; run time = 35.97 s; real-time ratio: 0.83.

Gathering data...
  Done; gather time = 0.64 s.

Analyzing...
  Cells: 400
  Connections: 25439 (63.60 per cell)
  Spikes: 85805 (7.15 Hz)
  Simulated time: 30.0 s; 32 workers
  Run time: 35.97 s
   E : 13.012 Hz
   I : 10.120 Hz
Saving output as /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240419_Run14_mpi_interactive_test30/gen_1/gen_1_cand_0_data.json ... 
Finished saving!
  Done; saving time = 1.24 s.
  Done; plotting time = 0.00 s

Total time = 38.82 s
