
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_2/gen_2_cand_77_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_2/gen_2_cand_77_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 06:52:25.730163

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.95 s.
Making connections...
  Number of connections on node 0: 1012 
  Done; cell connection time = 47.82 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 1.89 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 852.85 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.51 s.

Analyzing...
  Cells: 400
  Connections: 1412 (3.53 per cell)
  Spikes: 3666 (1.83 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 852.85 s
   E : 0.000 Hz
   I : 5.741 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_2/gen_2_cand_77_data.json ... 
Finished saving!
  Done; saving time = 5.19 s.
  Done; plotting time = 0.00 s

Total time = 913.47 s
first instance of v_init
first instance of tstop
