
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run7_testing_run_name/gen_0/gen_0_cand_3_cfg.json
Loading file /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run7_testing_run_name/gen_0/gen_0_cand_3_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run7_testing_run_name/240414_Run7_testing_run_name_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run7_testing_run_name/netParams_popParams.json ... 

Start time:  2024-04-14 00:51:02.988543

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.05 s.
Making connections...
  Number of connections on node 0: 12397 
  Done; cell connection time = 3.96 s.
Adding stims...
  Number of stims on node 0: 800 
  Done; cell stims creation time = 0.12 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 26.57 s; real-time ratio: 0.04.

Gathering data...
  Done; gather time = 0.32 s.

Analyzing...
  Cells: 400
  Connections: 12797 (31.99 per cell)
  Synaptic contacts: 13197 (32.99 per cell)
  Spikes: 20518 (51.30 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 26.57 s
   E : 73.148 Hz
   I : 0.000 Hz
Saving output as /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run7_testing_run_name/gen_0/gen_0_cand_3_data.json ... 
Finished saving!
  Done; saving time = 0.50 s.
  Done; plotting time = 0.00 s

Total time = 31.64 s
