
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run7_testing_run_name/gen_0/gen_0_cand_0_cfg.json
Loading file /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run7_testing_run_name/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run7_testing_run_name/240414_Run7_testing_run_name_netParams.py
Saving netParams to /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run7_testing_run_name/netParams_popParams.json ... 

Start time:  2024-04-14 00:50:59.789054

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.07 s.
Making connections...
  Number of connections on node 0: 14264 
  Done; cell connection time = 4.63 s.
Adding stims...
  Number of stims on node 0: 800 
  Done; cell stims creation time = 0.12 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 30.65 s; real-time ratio: 0.03.

Gathering data...
  Done; gather time = 0.36 s.

Analyzing...
  Cells: 400
  Connections: 14664 (36.66 per cell)
  Synaptic contacts: 15064 (37.66 per cell)
  Spikes: 20371 (50.93 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 30.65 s
   E : 68.389 Hz
   I : 6.011 Hz
Saving output as /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run7_testing_run_name/gen_0/gen_0_cand_0_data.json ... 
Finished saving!
  Done; saving time = 0.51 s.
  Done; plotting time = 0.00 s

Total time = 36.46 s
