
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_4/gen_4_cand_8_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_4/gen_4_cand_8_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/240430_Run1_interactive_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 15:27:57.546625

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.06 s.
Making connections...
  Number of connections on node 0: 1138 
  Done; cell connection time = 1.90 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 185.55 s; real-time ratio: 0.05.

Gathering data...
  Done; gather time = 0.37 s.

Analyzing...
  Cells: 400
  Connections: 1138 (2.85 per cell)
  Spikes: 65291 (16.32 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 185.55 s
   E : 11.052 Hz
   I : 19.343 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_4/gen_4_cand_8_data.json ... 
Finished saving!
  Done; saving time = 2.57 s.
  Done; plotting time = 0.00 s

Total time = 190.57 s
