
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_4/gen_4_cand_70_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_4/gen_4_cand_70_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/240430_Run1_interactive_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 15:28:23.651167

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.36 s.
Making connections...
  Number of connections on node 0: 6173 
  Done; cell connection time = 7.97 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 523.82 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 1.14 s.

Analyzing...
  Cells: 400
  Connections: 6173 (15.43 per cell)
  Spikes: 297293 (74.32 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 523.82 s
   E : 71.091 Hz
   I : 66.824 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_4/gen_4_cand_70_data.json ... 
Finished saving!
  Done; saving time = 4.52 s.
  Done; plotting time = 0.00 s

Total time = 538.73 s
