
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_4/gen_4_cand_33_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_4/gen_4_cand_33_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/240430_Run1_interactive_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 15:28:17.067243

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.54 s.
Making connections...
  Number of connections on node 0: 7689 
  Done; cell connection time = 12.01 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 575.14 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 1.41 s.

Analyzing...
  Cells: 400
  Connections: 7689 (19.22 per cell)
  Spikes: 281 (0.07 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 575.14 s
   E : 0.000 Hz
   I : 0.009 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_4/gen_4_cand_33_data.json ... 
Finished saving!
  Done; saving time = 3.02 s.
  Done; plotting time = 0.00 s

Total time = 592.13 s
