
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_interactive_debug/gen_0/gen_0_cand_4_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_interactive_debug/gen_0/gen_0_cand_4_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_interactive_debug/240429_Run2_interactive_debug_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_interactive_debug/netParams_popParams.json ... 

Start time:  2024-04-29 00:39:36.483765

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.04 s.
Making connections...
  Number of connections on node 0: 6781 
  Done; cell connection time = 1.70 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 44.14 s; real-time ratio: 0.11.

Gathering data...
  Done; gather time = 0.17 s.

Analyzing...
  Cells: 400
  Connections: 6781 (16.95 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 44.14 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_interactive_debug/gen_0/gen_0_cand_4_data.json ... 
Finished saving!
  Done; saving time = 0.53 s.
  Done; plotting time = 0.00 s

Total time = 46.59 s
first instance of v_init
first instance of tstop
