
========================   JOB MAP   ========================
Data for JOB prterun-nid006368-235885@1 offset 0 Total slots allocated 256
    Mapping policy: BYCORE:NOOVERSUBSCRIBE  Ranking policy: SLOT Binding policy: CORE
    Cpu set: N/A  PPR: 1:core  Cpus-per-rank: N/A  Cpu Type: HWT


Data for node: nid006368	Num slots: 256	Max slots: 0	Num procs: 4
        Process jobid: prterun-nid006368-235885@1 App: 0 Process rank: 0 Bound: package[0][hwt:0,128]
        Process jobid: prterun-nid006368-235885@1 App: 0 Process rank: 1 Bound: package[0][hwt:1,129]
        Process jobid: prterun-nid006368-235885@1 App: 0 Process rank: 2 Bound: package[0][hwt:2,130]
        Process jobid: prterun-nid006368-235885@1 App: 0 Process rank: 3 Bound: package[0][hwt:3,131]

=============================================================
numprocs=4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/gen_1/gen_1_cand_17_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/gen_1/gen_1_cand_17_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/240422_Run38_MPIsxOMPs_1x4x16_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/gen_1/gen_1_cand_17_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/gen_1/gen_1_cand_17_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/240422_Run38_MPIsxOMPs_1x4x16_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/gen_1/gen_1_cand_17_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/gen_1/gen_1_cand_17_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/240422_Run38_MPIsxOMPs_1x4x16_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/gen_1/gen_1_cand_17_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/gen_1/gen_1_cand_17_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/240422_Run38_MPIsxOMPs_1x4x16_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/netParams_popParams.json ... 

Start time:  2024-04-22 23:54:10.704740

Creating network of 2 cell populations on 4 hosts...
  Number of cells on node 0: 100 
  Number of cells on node 2: 100 
  Number of cells on node 1: 100 
  Number of cells on node 3: 100 
  Done; cell creation time = 0.70 s.
Making connections...
  Number of connections on node 3: 420 
  Number of connections on node 0: 433 
  Number of connections on node 1: 447 
  Number of connections on node 2: 453 
  Done; cell connection time = 22.35 s.
Adding stims...
  Number of stims on node 0: 100 
  Number of stims on node 2: 100 
  Number of stims on node 3: 100 
  Number of stims on node 1: 100 
  Done; cell stims creation time = 0.59 s.
Recording 0 traces of 0 types on node 0
Recording 0 traces of 0 types on node 2
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 1

Running simulation using NEURON for 30000.0 ms...
  Done; run time = 1941.05 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 2.90 s.

Analyzing...
  Cells: 400
  Connections: 2153 (5.38 per cell)
  Spikes: 51070 (4.26 Hz)
  Simulated time: 30.0 s; 4 workers
  Run time: 1941.05 s
   E : 0.746 Hz
   I : 3.306 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/gen_1/gen_1_cand_17_data.json ... 
Finished saving!
  Done; saving time = 8.42 s.
  Done; plotting time = 0.00 s

Total time = 1976.24 s
