
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_5/gen_5_cand_29_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_5/gen_5_cand_29_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 07:40:48.958124

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.54 s.
Making connections...
  Number of connections on node 0: 196 
  Done; cell connection time = 60.02 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 2.69 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 823.48 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.95 s.

Analyzing...
  Cells: 400
  Connections: 596 (1.49 per cell)
  Spikes: 12369 (6.18 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 823.48 s
   E : 5.575 Hz
   I : 7.954 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_5/gen_5_cand_29_data.json ... 
Finished saving!
  Done; saving time = 7.74 s.
  Done; plotting time = 0.00 s

Total time = 899.64 s
first instance of v_init
first instance of tstop
