
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_5/gen_5_cand_97_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_5/gen_5_cand_97_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 07:40:51.355679

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.89 s.
Making connections...
  Number of connections on node 0: 24648 
  Done; cell connection time = 111.99 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 1.16 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 2789.05 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 9.06 s.

Analyzing...
  Cells: 400
  Connections: 25048 (62.62 per cell)
  Spikes: 83306 (41.65 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 2789.05 s
   E : 3.321 Hz
   I : 9.602 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_5/gen_5_cand_97_data.json ... 
Finished saving!
  Done; saving time = 11.15 s.
  Done; plotting time = 0.00 s

Total time = 2923.58 s
first instance of v_init
first instance of tstop
