
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_11/gen_11_cand_53_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_11/gen_11_cand_53_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/240430_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 20:09:52.350827

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.56 s.
Making connections...
  Number of connections on node 0: 17581 
  Done; cell connection time = 17.74 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 943.36 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 1.53 s.

Analyzing...
  Cells: 400
  Connections: 17581 (43.95 per cell)
  Spikes: 14463 (3.62 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 943.36 s
   E : 0.020 Hz
   I : 10.611 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_11/gen_11_cand_53_data.json ... 
Finished saving!
  Done; saving time = 2.35 s.
  Done; plotting time = 0.00 s

Total time = 965.60 s
