
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_0/gen_0_cand_28_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_0/gen_0_cand_28_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/240425_Run4_25AprRunWhileWork_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 12:38:39.742250

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.27 s.
Making connections...
  Number of connections on node 0: 521 
  Done; cell connection time = 34.81 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 1.28 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 489.96 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 1.79 s.

Analyzing...
  Cells: 400
  Connections: 921 (2.30 per cell)
  Spikes: 4723 (2.36 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 489.96 s
   E : 1.766 Hz
   I : 3.981 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_0/gen_0_cand_28_data.json ... 
Finished saving!
  Done; saving time = 4.01 s.
  Done; plotting time = 0.00 s

Total time = 533.13 s
first instance of v_init
first instance of tstop
