
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_0/gen_0_cand_49_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_0/gen_0_cand_49_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/240425_Run4_25AprRunWhileWork_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 12:38:36.470235

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.35 s.
Making connections...
  Number of connections on node 0: 10762 
  Done; cell connection time = 77.21 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 1.32 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 2616.51 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 8.38 s.

Analyzing...
  Cells: 400
  Connections: 11162 (27.91 per cell)
  Spikes: 147164 (73.58 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 2616.51 s
   E : 45.460 Hz
   I : 12.093 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_0/gen_0_cand_49_data.json ... 
Finished saving!
  Done; saving time = 17.78 s.
  Done; plotting time = 0.00 s

Total time = 2723.60 s
first instance of v_init
first instance of tstop
