
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_10/gen_10_cand_32_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_10/gen_10_cand_32_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-27 04:38:24.973814

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.04 s.
Making connections...
  Number of connections on node 0: 8472 
  Done; cell connection time = 81.23 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.20 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 2020.79 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 7.38 s.

Analyzing...
  Cells: 400
  Connections: 8472 (21.18 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 2020.79 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_10/gen_10_cand_32_data.json ... 
Finished saving!
  Done; saving time = 13.49 s.
  Done; plotting time = 0.00 s

Total time = 2124.13 s
first instance of v_init
first instance of tstop
