
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_10/gen_10_cand_43_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_10/gen_10_cand_43_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-27 04:38:51.180797

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.43 s.
Making connections...
  Number of connections on node 0: 3660 
  Done; cell connection time = 125.95 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 2462.86 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 7.93 s.

Analyzing...
  Cells: 400
  Connections: 3660 (9.15 per cell)
  Spikes: 1139 (0.57 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 2462.86 s
   E : 0.000 Hz
   I : 5.556 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_10/gen_10_cand_43_data.json ... 
Finished saving!
  Done; saving time = 18.93 s.
  Done; plotting time = 0.00 s

Total time = 2618.11 s
first instance of v_init
first instance of tstop
