
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_10/gen_10_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_10/gen_10_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-27 04:39:13.713334

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 3.09 s.
Making connections...
  Number of connections on node 0: 4637 
  Done; cell connection time = 137.54 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 2672.55 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 9.09 s.

Analyzing...
  Cells: 400
  Connections: 4637 (11.59 per cell)
  Spikes: 66917 (33.46 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 2672.55 s
   E : 52.968 Hz
   I : 1.593 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_10/gen_10_cand_73_data.json ... 
Finished saving!
  Done; saving time = 25.59 s.
  Done; plotting time = 0.00 s

Total time = 2849.10 s
first instance of v_init
first instance of tstop
