
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_5/gen_5_cand_55_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_5/gen_5_cand_55_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 07:41:30.162803

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.66 s.
Making connections...
  Number of connections on node 0: 259 
  Done; cell connection time = 91.09 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 3.19 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1193.99 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 3.71 s.

Analyzing...
  Cells: 400
  Connections: 659 (1.65 per cell)
  Spikes: 76343 (38.17 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1193.99 s
   E : 36.202 Hz
   I : 42.861 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_5/gen_5_cand_55_data.json ... 
Finished saving!
  Done; saving time = 15.56 s.
  Done; plotting time = 0.00 s

Total time = 1314.90 s
first instance of v_init
first instance of tstop
