
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run1_interactive_debug/gen_3/gen_3_cand_4_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run1_interactive_debug/gen_3/gen_3_cand_4_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run1_interactive_debug/240429_Run1_interactive_debug_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run1_interactive_debug/netParams_popParams.json ... 

Start time:  2024-04-29 00:35:46.001571

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.04 s.
Making connections...
  Number of connections on node 0: 1733 
  Done; cell connection time = 1.08 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 18.72 s; real-time ratio: 0.27.

Gathering data...
  Done; gather time = 0.06 s.

Analyzing...
  Cells: 400
  Connections: 1733 (4.33 per cell)
  Spikes: 753 (0.38 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 18.72 s
   E : 0.000 Hz
   I : 3.630 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run1_interactive_debug/gen_3/gen_3_cand_4_data.json ... 
Finished saving!
  Done; saving time = 2.39 s.
  Done; plotting time = 0.00 s

Total time = 22.29 s
first instance of v_init
first instance of tstop
