
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run27_debug_run/gen_0/gen_0_cand_1_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run27_debug_run/gen_0/gen_0_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run27_debug_run/240417_Run27_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run27_debug_run/netParams_popParams.json ... 

Start time:  2024-04-17 23:27:10.260938

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.03 s.
Making connections...
  Number of connections on node 0: 21067 
  Done; cell connection time = 3.18 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.04 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 46.00 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 0.89 s.

Analyzing...
  Cells: 400
  Connections: 21467 (53.67 per cell)
  Spikes: 6160 (15.40 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 46.00 s
   E : 21.798 Hz
   I : 5.741 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run27_debug_run/gen_0/gen_0_cand_1_data.json ... 
Finished saving!
  Done; saving time = 0.79 s.
  Done; plotting time = 0.00 s

Total time = 50.95 s
