
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run27_debug_run/gen_0/gen_0_cand_4_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run27_debug_run/gen_0/gen_0_cand_4_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run27_debug_run/240417_Run27_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run27_debug_run/netParams_popParams.json ... 

Start time:  2024-04-17 23:27:13.424482

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.04 s.
Making connections...
  Number of connections on node 0: 45857 
  Done; cell connection time = 6.95 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.04 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 125.25 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 1.12 s.

Analyzing...
  Cells: 400
  Connections: 46257 (115.64 per cell)
  Spikes: 22279 (55.70 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 125.25 s
   E : 79.103 Hz
   I : 8.759 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run27_debug_run/gen_0/gen_0_cand_4_data.json ... 
Finished saving!
  Done; saving time = 1.35 s.
  Done; plotting time = 0.00 s

Total time = 134.78 s
