
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_9/gen_9_cand_43_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_9/gen_9_cand_43_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-27 03:35:40.523566

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.95 s.
Making connections...
  Number of connections on node 0: 1581 
  Done; cell connection time = 103.09 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1607.03 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 4.25 s.

Analyzing...
  Cells: 400
  Connections: 1581 (3.95 per cell)
  Spikes: 545 (0.27 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1607.03 s
   E : 0.000 Hz
   I : 1.972 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_9/gen_9_cand_43_data.json ... 
Finished saving!
  Done; saving time = 14.35 s.
  Done; plotting time = 0.00 s

Total time = 1730.68 s
first instance of v_init
first instance of tstop
