
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_9/gen_9_cand_15_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_9/gen_9_cand_15_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-27 03:34:55.509218

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.75 s.
Making connections...
  Number of connections on node 0: 8498 
  Done; cell connection time = 130.22 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 3297.71 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 11.54 s.

Analyzing...
  Cells: 400
  Connections: 8498 (21.25 per cell)
  Spikes: 67629 (33.81 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 3297.71 s
   E : 45.726 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_9/gen_9_cand_15_data.json ... 
Finished saving!
  Done; saving time = 25.18 s.
  Done; plotting time = 0.00 s

Total time = 3466.33 s
first instance of v_init
first instance of tstop
