
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_4/gen_4_cand_28_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_4/gen_4_cand_28_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 06:37:23.193366

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.84 s.
Making connections...
  Number of connections on node 0: 610 
  Done; cell connection time = 76.65 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 2.96 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1112.94 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 3.06 s.

Analyzing...
  Cells: 400
  Connections: 1010 (2.52 per cell)
  Spikes: 64145 (32.07 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1112.94 s
   E : 41.889 Hz
   I : 9.593 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_4/gen_4_cand_28_data.json ... 
Finished saving!
  Done; saving time = 11.15 s.
  Done; plotting time = 0.00 s

Total time = 1213.65 s
first instance of v_init
first instance of tstop
