
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_9/gen_9_cand_20_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_9/gen_9_cand_20_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/240430_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 18:50:17.379743

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.06 s.
Making connections...
  Number of connections on node 0: 133 
  Done; cell connection time = 1.73 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 97.05 s; real-time ratio: 0.10.

Gathering data...
  Done; gather time = 0.26 s.

Analyzing...
  Cells: 400
  Connections: 133 (0.33 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 97.05 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_9/gen_9_cand_20_data.json ... 
Finished saving!
  Done; saving time = 2.66 s.
  Done; plotting time = 0.00 s

Total time = 101.76 s
