
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_9/gen_9_cand_80_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_9/gen_9_cand_80_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/240430_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 18:50:35.323617

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.53 s.
Making connections...
  Number of connections on node 0: 9322 
  Done; cell connection time = 16.43 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 763.96 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.84 s.

Analyzing...
  Cells: 400
  Connections: 9322 (23.30 per cell)
  Spikes: 328770 (82.19 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 763.96 s
   E : 80.278 Hz
   I : 17.769 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_9/gen_9_cand_80_data.json ... 
Finished saving!
  Done; saving time = 7.77 s.
  Done; plotting time = 0.00 s

Total time = 791.95 s
