
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_9/gen_9_cand_25_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_9/gen_9_cand_25_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/240430_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 18:50:17.449296

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.06 s.
Making connections...
  Number of connections on node 0: 72762 
  Done; cell connection time = 15.52 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 2116.49 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 1.64 s.

Analyzing...
  Cells: 400
  Connections: 72762 (181.91 per cell)
  Spikes: 15640 (3.91 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 2116.49 s
   E : 0.774 Hz
   I : 20.722 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_9/gen_9_cand_25_data.json ... 
Finished saving!
  Done; saving time = 2.28 s.
  Done; plotting time = 0.00 s

Total time = 2136.00 s
