
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_9/gen_9_cand_81_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_9/gen_9_cand_81_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/240430_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 18:50:45.534556

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.34 s.
Making connections...
  Number of connections on node 0: 929 
  Done; cell connection time = 6.67 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 200.10 s; real-time ratio: 0.05.

Gathering data...
  Done; gather time = 0.31 s.

Analyzing...
  Cells: 400
  Connections: 929 (2.32 per cell)
  Spikes: 379 (0.09 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 200.10 s
   E : 0.000 Hz
   I : 0.648 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_9/gen_9_cand_81_data.json ... 
Finished saving!
  Done; saving time = 2.27 s.
  Done; plotting time = 0.00 s

Total time = 209.69 s
