
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_2/gen_2_cand_52_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_2/gen_2_cand_52_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 06:42:00.552949

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.52 s.
Making connections...
  Number of connections on node 0: 1571 
  Done; cell connection time = 23.39 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.72 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 544.82 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 4.74 s.

Analyzing...
  Cells: 400
  Connections: 1971 (4.93 per cell)
  Spikes: 16191 (8.10 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 544.82 s
   E : 14.365 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_2/gen_2_cand_52_data.json ... 
Finished saving!
  Done; saving time = 6.31 s.
  Done; plotting time = 0.00 s

Total time = 580.76 s
first instance of v_init
first instance of tstop
