
========================   JOB MAP   ========================
Data for JOB prterun-nid006368-235761@1 offset 0 Total slots allocated 256
    Mapping policy: BYCORE:NOOVERSUBSCRIBE  Ranking policy: SLOT Binding policy: CORE
    Cpu set: N/A  PPR: 1:core  Cpus-per-rank: N/A  Cpu Type: HWT


Data for node: nid006368	Num slots: 256	Max slots: 0	Num procs: 4
        Process jobid: prterun-nid006368-235761@1 App: 0 Process rank: 0 Bound: package[0][hwt:0,128]
        Process jobid: prterun-nid006368-235761@1 App: 0 Process rank: 1 Bound: package[0][hwt:1,129]
        Process jobid: prterun-nid006368-235761@1 App: 0 Process rank: 2 Bound: package[0][hwt:2,130]
        Process jobid: prterun-nid006368-235761@1 App: 0 Process rank: 3 Bound: package[0][hwt:3,131]

=============================================================
numprocs=4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/gen_1/gen_1_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/gen_1/gen_1_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/240422_Run38_MPIsxOMPs_1x4x16_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/gen_1/gen_1_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/gen_1/gen_1_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/240422_Run38_MPIsxOMPs_1x4x16_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/gen_1/gen_1_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/gen_1/gen_1_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/240422_Run38_MPIsxOMPs_1x4x16_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/gen_1/gen_1_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/gen_1/gen_1_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/240422_Run38_MPIsxOMPs_1x4x16_netParams.py
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/netParams_popParams.json ... 

Start time:  2024-04-22 23:50:41.802151
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/netParams_popParams.json ... 

Creating network of 2 cell populations on 4 hosts...
  Number of cells on node 0: 100 
  Number of cells on node 1: 100 
  Number of cells on node 2: 100 
  Number of cells on node 3: 100 
  Done; cell creation time = 0.04 s.
Making connections...
  Number of connections on node 2: 525 
  Number of connections on node 0: 566 
  Number of connections on node 1: 582 
  Number of connections on node 3: 494 
  Done; cell connection time = 1.84 s.
Adding stims...
  Number of stims on node 1: 100 
  Number of stims on node 3: 100 
  Number of stims on node 2: 100 
  Number of stims on node 0: 100 
  Done; cell stims creation time = 0.05 s.
Recording 0 traces of 0 types on node 0
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 1
Recording 0 traces of 0 types on node 2

Running simulation using NEURON for 30000.0 ms...
  Done; run time = 1350.74 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 3.72 s.

Analyzing...
  Cells: 400
  Connections: 2567 (6.42 per cell)
  Spikes: 8996 (0.75 Hz)
  Simulated time: 30.0 s; 4 workers
  Run time: 1350.74 s
   E : 0.679 Hz
   I : 1.028 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run38_MPIsxOMPs_1x4x16/gen_1/gen_1_cand_6_data.json ... 
Finished saving!
  Done; saving time = 10.17 s.
  Done; plotting time = 0.00 s

Total time = 1366.61 s
