
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_debug_node_run/gen_1/gen_1_cand_19_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_debug_node_run/gen_1/gen_1_cand_19_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_debug_node_run/240429_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 01:52:02.368448

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.78 s.
Making connections...
  Number of connections on node 0: 4149 
  Done; cell connection time = 29.04 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 1799.43 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 3.06 s.

Analyzing...
  Cells: 400
  Connections: 4149 (10.37 per cell)
  Spikes: 257730 (64.43 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 1799.43 s
   E : 64.516 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run2_debug_node_run/gen_1/gen_1_cand_19_data.json ... 
Finished saving!
  Done; saving time = 17.57 s.
  Done; plotting time = 0.00 s

Total time = 1851.95 s
