
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_0/gen_0_cand_1_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_0/gen_0_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 04:12:19.659709

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.07 s.
Making connections...
  Number of connections on node 0: 17449 
  Done; cell connection time = 6.16 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.07 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1922.59 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 24.61 s.

Analyzing...
  Cells: 400
  Connections: 17849 (44.62 per cell)
  Spikes: 22463 (11.23 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1922.59 s
   E : 18.956 Hz
   I : 7.435 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_0/gen_0_cand_1_data.json ... 
Finished saving!
  Done; saving time = 28.36 s.
  Done; plotting time = 0.00 s

Total time = 1982.22 s
first instance of v_init
first instance of tstop
