
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_0/gen_0_cand_82_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_0/gen_0_cand_82_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 04:27:04.739995

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.36 s.
Making connections...
  Number of connections on node 0: 1827 
  Done; cell connection time = 57.98 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 1.85 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1168.51 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 6.52 s.

Analyzing...
  Cells: 400
  Connections: 2227 (5.57 per cell)
  Spikes: 51385 (25.69 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1168.51 s
   E : 21.877 Hz
   I : 30.630 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_0/gen_0_cand_82_data.json ... 
Finished saving!
  Done; saving time = 10.45 s.
  Done; plotting time = 0.00 s

Total time = 1247.36 s
first instance of v_init
first instance of tstop
