
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_37_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_37_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 02:23:03.068928

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.89 s.
Making connections...
  Number of connections on node 0: 13793 
  Done; cell connection time = 189.85 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 3.06 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 7196.19 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 30.03 s.

Analyzing...
  Cells: 400
  Connections: 14193 (35.48 per cell)
  Spikes: 107977 (53.99 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 7196.19 s
   E : 13.198 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_37_data.json ... 
Finished saving!
  Done; saving time = 52.02 s.
  Done; plotting time = 0.00 s

Total time = 7474.95 s
first instance of v_init
first instance of tstop
