
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_14/gen_14_cand_72_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_14/gen_14_cand_72_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/240430_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 21:56:53.578526

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.35 s.
Making connections...
  Number of connections on node 0: 2586 
  Done; cell connection time = 2.22 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 268.15 s; real-time ratio: 0.04.

Gathering data...
  Done; gather time = 0.46 s.

Analyzing...
  Cells: 400
  Connections: 2586 (6.46 per cell)
  Spikes: 243258 (60.81 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 268.15 s
   E : 63.778 Hz
   I : 29.056 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_14/gen_14_cand_72_data.json ... 
Finished saving!
  Done; saving time = 2.67 s.
  Done; plotting time = 0.00 s

Total time = 274.50 s
