
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_14/gen_14_cand_10_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_14/gen_14_cand_10_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/240430_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 21:56:27.976950

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.05 s.
Making connections...
  Number of connections on node 0: 42843 
  Done; cell connection time = 10.44 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 1451.22 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 1.84 s.

Analyzing...
  Cells: 400
  Connections: 42843 (107.11 per cell)
  Spikes: 11495 (2.87 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 1451.22 s
   E : 0.091 Hz
   I : 9.694 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_14/gen_14_cand_10_data.json ... 
Finished saving!
  Done; saving time = 2.57 s.
  Done; plotting time = 0.00 s

Total time = 1466.14 s
