numprocs=4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_9_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_9_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_9_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_9_cfg.json ... 
Loading simConfig...

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_9_cfg.json
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_9_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_9_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_9_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 

Start time:  2024-04-22 13:02:04.170384

Creating network of 2 cell populations on 4 hosts...
  Number of cells on node 1: 100 
  Number of cells on node 0: 100 
  Done; cell creation time = 0.02 s.
  Number of cells on node 2: 100 
  Number of cells on node 3: 100 
Making connections...
  Number of connections on node 1: 103 
  Number of connections on node 3: 110 
  Number of connections on node 0: 112 
  Number of connections on node 2: 95 
  Done; cell connection time = 1.70 s.
Adding stims...
  Number of stims on node 0: 100 
  Number of stims on node 1: 100 
  Number of stims on node 2: 100 
  Number of stims on node 3: 100 
  Done; cell stims creation time = 0.05 s.
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 1
Recording 0 traces of 0 types on node 2
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 14.86 s; real-time ratio: 0.34.

Gathering data...
  Done; gather time = 0.16 s.

Analyzing...
  Cells: 400
  Connections: 820 (2.05 per cell)
  Spikes: 135 (0.07 Hz)
  Simulated time: 5.0 s; 4 workers
  Run time: 14.86 s
   E : 0.000 Hz
   I : 0.315 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_1/gen_1_cand_9_data.json ... 
Finished saving!
  Done; saving time = 0.42 s.
  Done; plotting time = 0.00 s

Total time = 17.23 s
