
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run15_testing_run_name/gen_0/gen_0_cand_0_cfg.json
Loading file /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run15_testing_run_name/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run15_testing_run_name/240414_Run15_testing_run_name_netParams.py
Duration: 1 seconds
Saving netParams to /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run15_testing_run_name/netParams_popParams.json ... 

Start time:  2024-04-14 01:35:12.354550

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.11 s.
Making connections...
  Number of connections on node 0: 29593 
  Done; cell connection time = 11.41 s.
Adding stims...
  Number of stims on node 0: 800 
  Done; cell stims creation time = 0.16 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 299.57 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 1.67 s.

Analyzing...
  Cells: 400
  Connections: 29993 (74.98 per cell)
  Synaptic contacts: 30393 (75.98 per cell)
  Spikes: 363 (0.91 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 299.57 s
   E : 1.344 Hz
   I : 0.000 Hz
Saving output as /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run15_testing_run_name/gen_0/gen_0_cand_0_data.json ... 
Finished saving!
  Done; saving time = 1.48 s.
  Done; plotting time = 0.00 s

Total time = 314.42 s
