
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_1/gen_1_cand_48_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_1/gen_1_cand_48_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 05:36:00.540683

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.75 s.
Making connections...
  Number of connections on node 0: 562 
  Done; cell connection time = 30.37 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 1.12 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 605.33 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.87 s.

Analyzing...
  Cells: 400
  Connections: 962 (2.40 per cell)
  Spikes: 108379 (54.19 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 605.33 s
   E : 62.448 Hz
   I : 26.509 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_1/gen_1_cand_48_data.json ... 
Finished saving!
  Done; saving time = 12.91 s.
  Done; plotting time = 0.00 s

Total time = 657.06 s
first instance of v_init
first instance of tstop
