
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_8/gen_8_cand_93_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_8/gen_8_cand_93_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/240430_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 18:14:24.453739

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.18 s.
Making connections...
  Number of connections on node 0: 595 
  Done; cell connection time = 3.88 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 169.21 s; real-time ratio: 0.06.

Gathering data...
  Done; gather time = 0.30 s.

Analyzing...
  Cells: 400
  Connections: 595 (1.49 per cell)
  Spikes: 194455 (48.61 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 169.21 s
   E : 57.893 Hz
   I : 17.296 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_8/gen_8_cand_93_data.json ... 
Finished saving!
  Done; saving time = 3.06 s.
  Done; plotting time = 0.00 s

Total time = 176.84 s
