Initiating Rank: 1
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/240521_Run2_overnight_reg_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/netParams_popParams.json ... 
  Number of cells on node 1: 25 
  Number of connections on node 1: 969 
  Number of stims on node 1: 0 
Initiating Rank: 3
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/240521_Run2_overnight_reg_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/netParams_popParams.json ... 
  Number of cells on node 3: 25 
  Number of connections on node 3: 950 
  Number of stims on node 3: 0 
Initiating Rank: 7
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/240521_Run2_overnight_reg_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/netParams_popParams.json ... 
  Number of cells on node 7: 25 
  Number of connections on node 7: 883 
  Number of stims on node 7: 0 
Initiating Rank: 9
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/240521_Run2_overnight_reg_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/netParams_popParams.json ... 
  Number of cells on node 9: 25 
  Number of connections on node 9: 944 
  Number of stims on node 9: 0 
Initiating Rank: 11
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/240521_Run2_overnight_reg_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/netParams_popParams.json ... 
  Number of cells on node 11: 25 
  Number of connections on node 11: 1083 
  Number of stims on node 11: 0 
Initiating Rank: 13
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/240521_Run2_overnight_reg_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/netParams_popParams.json ... 
  Number of cells on node 13: 25 
  Number of connections on node 13: 961 
  Number of stims on node 13: 0 
Initiating Rank: 15
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/240521_Run2_overnight_reg_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/netParams_popParams.json ... 
  Number of cells on node 15: 25 
  Number of connections on node 15: 876 
  Number of stims on node 15: 0 
Initiating Rank: 4
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/240521_Run2_overnight_reg_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/netParams_popParams.json ... 
  Number of cells on node 4: 25 
  Number of connections on node 4: 925 
  Number of stims on node 4: 0 
Initiating Rank: 5
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/240521_Run2_overnight_reg_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/netParams_popParams.json ... 
  Number of cells on node 5: 25 
  Number of connections on node 5: 948 
  Number of stims on node 5: 0 
Initiating Rank: 2
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/240521_Run2_overnight_reg_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/netParams_popParams.json ... 
  Number of cells on node 2: 25 
  Number of connections on node 2: 959 
  Number of stims on node 2: 0 
Initiating Rank: 6
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/240521_Run2_overnight_reg_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/netParams_popParams.json ... 
  Number of cells on node 6: 25 
  Number of connections on node 6: 988 
  Number of stims on node 6: 0 
Initiating Rank: 8
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/240521_Run2_overnight_reg_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/netParams_popParams.json ... 
  Number of cells on node 8: 25 
  Number of connections on node 8: 990 
  Number of stims on node 8: 0 
Initiating Rank: 10
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/240521_Run2_overnight_reg_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/netParams_popParams.json ... 
  Number of cells on node 10: 25 
  Number of connections on node 10: 1056 
  Number of stims on node 10: 0 
Initiating Rank: 12
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/240521_Run2_overnight_reg_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/netParams_popParams.json ... 
  Number of cells on node 12: 25 
  Number of connections on node 12: 1014 
  Number of stims on node 12: 0 
Initiating Rank: 14
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/240521_Run2_overnight_reg_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/netParams_popParams.json ... 
  Number of cells on node 14: 25 
  Number of connections on node 14: 953 
  Number of stims on node 14: 0 
Initiating Rank: 0
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/240521_Run2_overnight_reg_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/netParams_popParams.json ... 

Start time:  2024-05-21 04:16:21.315877

Creating network of 2 cell populations on 16 hosts...
  Number of cells on node 0: 25 
  Done; cell creation time = 0.00 s.
Making connections...
  Number of connections on node 0: 934 
  Done; cell connection time = 0.78 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.

Running simulation using NEURON for 15000.0 ms...
  Done; run time = 16.54 s; real-time ratio: 0.91.

Gathering data...
  Done; gather time = 0.26 s.

Analyzing...
  Cells: 400
  Connections: 15433 (38.58 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 15.0 s; 16 workers
  Run time: 16.54 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240521_Run2_overnight_reg/gen_6/gen_6_cand_35_data.json ... 
Finished saving!
  Done; saving time = 0.44 s.
  Done; plotting time = 0.00 s

Total time = 18.05 s
numprocs=16
