
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run7_scaling_up/gen_0/gen_0_cand_7_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run7_scaling_up/gen_0/gen_0_cand_7_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run7_scaling_up/240424_Run7_scaling_up_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run7_scaling_up/netParams_popParams.json ... 

Start time:  2024-04-24 17:16:52.403186

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.04 s.
Making connections...
  Number of connections on node 0: 9295 
  Done; cell connection time = 2.02 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.04 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 30000.0 ms...
  Done; run time = 539.14 s; real-time ratio: 0.06.

Gathering data...
  Done; gather time = 0.31 s.

Analyzing...
  Cells: 400
  Connections: 9695 (24.24 per cell)
  Spikes: 770441 (64.20 Hz)
  Simulated time: 30.0 s; 1 workers
  Run time: 539.14 s
   E : 13.278 Hz
   I : 12.537 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run7_scaling_up/gen_0/gen_0_cand_7_data.json ... 
Finished saving!
  Done; saving time = 1.93 s.
  Done; plotting time = 0.00 s

Total time = 543.56 s
first instance of v_init
first instance of tstop
