
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run25_debug_node_run/gen_0/gen_0_cand_26_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run25_debug_node_run/gen_0/gen_0_cand_26_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run25_debug_node_run/240429_Run25_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run25_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-29 21:02:39.610030

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.06 s.
Making connections...
  Number of connections on node 0: 8806 
  Done; cell connection time = 3.24 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 575.52 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 1.42 s.

Analyzing...
  Cells: 400
  Connections: 8806 (22.02 per cell)
  Spikes: 206574 (51.64 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 575.52 s
   E : 89.361 Hz
   I : 0.407 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run25_debug_node_run/gen_0/gen_0_cand_26_data.json ... 
Finished saving!
  Done; saving time = 3.34 s.
  Done; plotting time = 0.00 s

Total time = 583.75 s
first instance of v_init
first instance of tstop
