
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run25_debug_node_run/gen_0/gen_0_cand_65_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run25_debug_node_run/gen_0/gen_0_cand_65_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run25_debug_node_run/240429_Run25_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run25_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-29 21:04:04.154804

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.20 s.
Making connections...
  Number of connections on node 0: 15789 
  Done; cell connection time = 13.77 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 821.08 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 1.69 s.

Analyzing...
  Cells: 400
  Connections: 15789 (39.47 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 821.08 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run25_debug_node_run/gen_0/gen_0_cand_65_data.json ... 
Finished saving!
  Done; saving time = 2.13 s.
  Done; plotting time = 0.00 s

Total time = 838.88 s
first instance of v_init
first instance of tstop
