Initiating Rank: 2
TEST CWD: /workspaces/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /workspaces/2DNetworkSimulations/NERSC/output/240521_Run5_more_docker_testing/gen_0/gen_0_cand_1_cfg.json
Loading file /workspaces/2DNetworkSimulations/NERSC/output/240521_Run5_more_docker_testing/gen_0/gen_0_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /workspaces/2DNetworkSimulations/NERSC/output/240521_Run5_more_docker_testing/240521_Run5_more_docker_testing_netParams.py
im here second
no simConfig found
Flag -d not found.
Saving netParams to /workspaces/2DNetworkSimulations/NERSC/output/240521_Run5_more_docker_testing/netParams_popParams.json ... 

Start time:  2024-05-21 18:32:04.484336

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.13 s.
Making connections...
  Number of connections on node 0: 39218 
  Done; cell connection time = 7.80 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 56.07 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 1.52 s.

Analyzing...
  Cells: 400
  Connections: 39218 (98.05 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 56.07 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /workspaces/2DNetworkSimulations/NERSC/output/240521_Run5_more_docker_testing/gen_0/gen_0_cand_1_data.json ... 
Finished saving!
  Done; saving time = 2.54 s.
  Done; plotting time = 0.00 s

Total time = 68.06 s
