Initiating Rank: 1
TEST CWD: /app/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /app/NERSC/output/240520_Run1_more_docker_testing/gen_0/gen_0_cand_3_cfg.json
Loading file /app/NERSC/output/240520_Run1_more_docker_testing/gen_0/gen_0_cand_3_cfg.json ... 
Loading simConfig...
Importing netParams from /app/NERSC/output/240520_Run1_more_docker_testing/240520_Run1_more_docker_testing_netParams.py
im here second
no simConfig found
Flag -d not found.
Saving netParams to /app/NERSC/output/240520_Run1_more_docker_testing/netParams_popParams.json ... 

Start time:  2024-05-20 03:28:08.600740

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.10 s.
Making connections...
  Number of connections on node 0: 6312 
  Done; cell connection time = 4.81 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 17.84 s; real-time ratio: 0.06.

Gathering data...
  Done; gather time = 0.32 s.

Analyzing...
  Cells: 400
  Connections: 6312 (15.78 per cell)
  Spikes: 24620 (61.55 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 17.84 s
   E : 92.127 Hz
   I : 3.685 Hz
Saving output as /app/NERSC/output/240520_Run1_more_docker_testing/gen_0/gen_0_cand_3_data.json ... 
Finished saving!
  Done; saving time = 0.65 s.
  Done; plotting time = 0.00 s

Total time = 23.78 s
