Initiating Rank: 1
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 1: 13 
  Number of connections on node 1: 1081 
  Number of stims on node 1: 0 
Recording 0 traces of 0 types on node 1
Initiating Rank: 3
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 3: 13 
  Number of connections on node 3: 1060 
  Number of stims on node 3: 0 
Initiating Rank: 28
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 28: 12 
  Number of connections on node 28: 1008 
  Number of stims on node 28: 0 
Initiating Rank: 16
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 16: 12 
  Number of connections on node 16: 892 
  Number of stims on node 16: 0 
Initiating Rank: 8
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 8: 13 
  Number of connections on node 8: 1062 
  Number of stims on node 8: 0 
Initiating Rank: 25
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 25: 12 
  Number of connections on node 25: 976 
  Number of stims on node 25: 0 
Initiating Rank: 23
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 23: 12 
  Number of connections on node 23: 913 
  Number of stims on node 23: 0 
Initiating Rank: 5
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 5: 13 
  Number of connections on node 5: 978 
  Number of stims on node 5: 0 
Initiating Rank: 13
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 13: 13 
  Number of connections on node 13: 1007 
  Number of stims on node 13: 0 
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 28
Recording 0 traces of 0 types on node 16
Recording 0 traces of 0 types on node 8
Recording 0 traces of 0 types on node 25
Recording 1 traces of 1 types on node 23
Recording 0 traces of 0 types on node 5
Recording 0 traces of 0 types on node 13
Initiating Rank: 2
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 2: 13 
  Number of connections on node 2: 1066 
  Number of stims on node 2: 0 
Initiating Rank: 29
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 29: 12 
  Number of connections on node 29: 964 
  Number of stims on node 29: 0 
Initiating Rank: 17
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 17: 12 
  Number of connections on node 17: 890 
  Number of stims on node 17: 0 
Initiating Rank: 9
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 9: 13 
  Number of connections on node 9: 966 
  Number of stims on node 9: 0 
Initiating Rank: 27
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 27: 12 
  Number of connections on node 27: 948 
  Number of stims on node 27: 0 
Initiating Rank: 20
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 20: 12 
  Number of connections on node 20: 883 
  Number of stims on node 20: 0 
Initiating Rank: 6
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 6: 13 
  Number of connections on node 6: 1017 
  Number of stims on node 6: 0 
Initiating Rank: 14
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 14: 13 
  Number of connections on node 14: 997 
  Number of stims on node 14: 0 
Recording 0 traces of 0 types on node 2
Recording 0 traces of 0 types on node 29
Recording 0 traces of 0 types on node 17
Recording 0 traces of 0 types on node 9
Recording 0 traces of 0 types on node 27
Recording 0 traces of 0 types on node 20
Recording 0 traces of 0 types on node 6
Recording 0 traces of 0 types on node 14
Initiating Rank: 30
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 30: 12 
  Number of connections on node 30: 988 
  Number of stims on node 30: 0 
Initiating Rank: 18
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 18: 12 
  Number of connections on node 18: 905 
  Number of stims on node 18: 0 
Initiating Rank: 11
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 11: 13 
  Number of connections on node 11: 1025 
  Number of stims on node 11: 0 
Initiating Rank: 24
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 24: 12 
  Number of connections on node 24: 984 
  Number of stims on node 24: 0 
Initiating Rank: 21
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 21: 12 
  Number of connections on node 21: 969 
  Number of stims on node 21: 0 
Initiating Rank: 7
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 7: 13 
  Number of connections on node 7: 1023 
  Number of stims on node 7: 0 
Initiating Rank: 15
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 15: 13 
  Number of connections on node 15: 991 
  Number of stims on node 15: 0 
Recording 0 traces of 0 types on node 30
Recording 0 traces of 0 types on node 18
Recording 0 traces of 0 types on node 11
Recording 1 traces of 1 types on node 24
Recording 0 traces of 0 types on node 21
Recording 0 traces of 0 types on node 7
Recording 1 traces of 1 types on node 15
Initiating Rank: 31
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 31: 12 
  Number of connections on node 31: 952 
  Number of stims on node 31: 0 
Initiating Rank: 19
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 19: 12 
  Number of connections on node 19: 946 
  Number of stims on node 19: 0 
Initiating Rank: 10
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 10: 13 
  Number of connections on node 10: 1092 
  Number of stims on node 10: 0 
Initiating Rank: 26
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 26: 12 
  Number of connections on node 26: 1002 
  Number of stims on node 26: 0 
Initiating Rank: 22
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 22: 12 
  Number of connections on node 22: 956 
  Number of stims on node 22: 0 
Initiating Rank: 4
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 4: 13 
  Number of connections on node 4: 1076 
  Number of stims on node 4: 0 
Initiating Rank: 12
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 
  Number of cells on node 12: 13 
  Number of connections on node 12: 1085 
  Number of stims on node 12: 0 
Recording 0 traces of 0 types on node 31
Recording 0 traces of 0 types on node 19
Recording 0 traces of 0 types on node 10
Recording 0 traces of 0 types on node 26
Recording 1 traces of 1 types on node 22
Recording 0 traces of 0 types on node 4
Recording 0 traces of 0 types on node 12
Initiating Rank: 0
TEST CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/240523_Run9_it_srun_sims_8nodes_netParams.py
im here second
no simConfig found
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/netParams_popParams.json ... 

Start time:  2024-05-23 04:42:49.692942

Creating network of 2 cell populations on 32 hosts...
  Number of cells on node 0: 13 
  Done; cell creation time = 0.00 s.
Making connections...
  Number of connections on node 0: 1031 
  Done; cell connection time = 0.97 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 15000.0 ms...
  Done; run time = 19.39 s; real-time ratio: 0.77.

Gathering data...
  Done; gather time = 0.50 s.

Analyzing...
  Cells: 400
  Connections: 31733 (79.33 per cell)
  Spikes: 23191 (3.87 Hz)
  Simulated time: 15.0 s; 32 workers
  Run time: 19.39 s
   E : 9.849 Hz
   I : 0.954 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240523_Run9_it_srun_sims_8nodes/gen_0/gen_0_cand_58_data.json ... 
Finished saving!
  Done; saving time = 1.64 s.
  Done; plotting time = 0.00 s

Total time = 22.51 s
numprocs=32
