numprocs=4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/gen_0/gen_0_cand_3_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/gen_0/gen_0_cand_3_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/240422_Run16_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/gen_0/gen_0_cand_3_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/gen_0/gen_0_cand_3_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/240422_Run16_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/gen_0/gen_0_cand_3_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/gen_0/gen_0_cand_3_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/240422_Run16_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/gen_0/gen_0_cand_3_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/gen_0/gen_0_cand_3_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/240422_Run16_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/netParams_popParams.json ... 

Start time:  2024-04-22 14:44:49.780542

Creating network of 2 cell populations on 4 hosts...
  Number of cells on node 0: 100 
  Done; cell creation time = 0.01 s.
Making connections...
  Number of cells on node 2: 100 
  Number of cells on node 1: 100 
  Number of cells on node 3: 100 
  Number of connections on node 3: 7087 
  Number of connections on node 1: 7238 
  Number of connections on node 2: 7354 
  Number of connections on node 0: 7220 
  Done; cell connection time = 1.57 s.
Adding stims...
  Number of stims on node 2: 100 
  Number of stims on node 1: 100 
  Number of stims on node 0: 100 
  Number of stims on node 3: 100 
  Done; cell stims creation time = 0.02 s.
Recording 0 traces of 0 types on node 0
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 2
Recording 0 traces of 0 types on node 1

Running simulation using NEURON for 30000.0 ms...
  Done; run time = 352.05 s; real-time ratio: 0.09.

Gathering data...
  Done; gather time = 0.60 s.

Analyzing...
  Cells: 400
  Connections: 29299 (73.25 per cell)
  Spikes: 34485 (2.87 Hz)
  Simulated time: 30.0 s; 4 workers
  Run time: 352.05 s
   E : 2.651 Hz
   I : 25.731 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run16_test_uneven/gen_0/gen_0_cand_3_data.json ... 
Finished saving!
  Done; saving time = 1.18 s.
  Done; plotting time = 0.00 s

Total time = 355.45 s
