
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_1/gen_1_cand_13_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_1/gen_1_cand_13_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/240425_Run4_25AprRunWhileWork_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 13:39:46.485298

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.07 s.
Making connections...
  Number of connections on node 0: 3252 
  Done; cell connection time = 44.46 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 1.33 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1003.40 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 5.13 s.

Analyzing...
  Cells: 400
  Connections: 3652 (9.13 per cell)
  Spikes: 24545 (12.27 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1003.40 s
   E : 37.956 Hz
   I : 0.028 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_1/gen_1_cand_13_data.json ... 
Finished saving!
  Done; saving time = 6.48 s.
  Done; plotting time = 0.00 s

Total time = 1062.08 s
first instance of v_init
first instance of tstop
