
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_1/gen_1_cand_15_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_1/gen_1_cand_15_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/240425_Run4_25AprRunWhileWork_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 13:39:44.623863

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.61 s.
Making connections...
  Number of connections on node 0: 165 
  Done; cell connection time = 31.69 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 1.32 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 475.30 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 1.46 s.

Analyzing...
  Cells: 400
  Connections: 565 (1.41 per cell)
  Spikes: 3536 (1.77 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 475.30 s
   E : 1.187 Hz
   I : 0.204 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_1/gen_1_cand_15_data.json ... 
Finished saving!
  Done; saving time = 3.75 s.
  Done; plotting time = 0.00 s

Total time = 514.26 s
first instance of v_init
first instance of tstop
