
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_2/gen_2_cand_16_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_2/gen_2_cand_16_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 04:29:31.737828

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.69 s.
Making connections...
  Number of connections on node 0: 215 
  Done; cell connection time = 22.75 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.70 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 786.19 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.52 s.

Analyzing...
  Cells: 400
  Connections: 615 (1.54 per cell)
  Spikes: 351 (0.18 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 786.19 s
   E : 0.000 Hz
   I : 0.287 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_2/gen_2_cand_16_data.json ... 
Finished saving!
  Done; saving time = 5.98 s.
  Done; plotting time = 0.00 s

Total time = 818.85 s
first instance of v_init
first instance of tstop
