
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_2/gen_2_cand_110_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_2/gen_2_cand_110_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 04:31:43.190008

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.93 s.
Making connections...
  Number of connections on node 0: 173 
  Done; cell connection time = 61.39 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 2.18 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 759.80 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.68 s.

Analyzing...
  Cells: 400
  Connections: 573 (1.43 per cell)
  Spikes: 71977 (35.99 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 759.80 s
   E : 44.286 Hz
   I : 16.602 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_2/gen_2_cand_110_data.json ... 
Finished saving!
  Done; saving time = 11.22 s.
  Done; plotting time = 0.00 s

Total time = 842.54 s
first instance of v_init
first instance of tstop
