
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_2/gen_2_cand_95_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_2/gen_2_cand_95_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 04:31:10.510609

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.68 s.
Making connections...
  Number of connections on node 0: 5191 
  Done; cell connection time = 86.97 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 2.16 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1624.78 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 5.18 s.

Analyzing...
  Cells: 400
  Connections: 5591 (13.98 per cell)
  Spikes: 8339 (4.17 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1624.78 s
   E : 5.762 Hz
   I : 0.398 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_2/gen_2_cand_95_data.json ... 
Finished saving!
  Done; saving time = 5.99 s.
  Done; plotting time = 0.00 s

Total time = 1726.85 s
first instance of v_init
first instance of tstop
