
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_6/gen_6_cand_51_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_6/gen_6_cand_51_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-27 00:28:52.368346

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.86 s.
Making connections...
  Number of connections on node 0: 2282 
  Done; cell connection time = 112.71 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1774.40 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 9.44 s.

Analyzing...
  Cells: 400
  Connections: 2282 (5.71 per cell)
  Spikes: 157182 (78.59 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1774.40 s
   E : 96.095 Hz
   I : 15.630 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_6/gen_6_cand_51_data.json ... 
Finished saving!
  Done; saving time = 33.22 s.
  Done; plotting time = 0.00 s

Total time = 1935.27 s
first instance of v_init
first instance of tstop
