
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_6/gen_6_cand_12_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_6/gen_6_cand_12_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-27 00:27:36.357569

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.98 s.
Making connections...
  Number of connections on node 0: 246 
  Done; cell connection time = 39.02 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 585.00 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 1.96 s.

Analyzing...
  Cells: 400
  Connections: 246 (0.61 per cell)
  Spikes: 82993 (41.50 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 585.00 s
   E : 59.183 Hz
   I : 0.130 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_6/gen_6_cand_12_data.json ... 
Finished saving!
  Done; saving time = 15.26 s.
  Done; plotting time = 0.00 s

Total time = 647.19 s
first instance of v_init
first instance of tstop
