
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_6/gen_6_cand_50_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_6/gen_6_cand_50_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-27 00:28:30.634351

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.12 s.
Making connections...
  Number of connections on node 0: 2654 
  Done; cell connection time = 67.90 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1123.40 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 5.39 s.

Analyzing...
  Cells: 400
  Connections: 2654 (6.63 per cell)
  Spikes: 31007 (15.50 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1123.40 s
   E : 6.444 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_6/gen_6_cand_50_data.json ... 
Finished saving!
  Done; saving time = 10.58 s.
  Done; plotting time = 0.00 s

Total time = 1209.87 s
first instance of v_init
first instance of tstop
