numprocs=4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/gen_2/gen_2_cand_1_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/gen_2/gen_2_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/240422_Run19_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/gen_2/gen_2_cand_1_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/gen_2/gen_2_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/240422_Run19_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/gen_2/gen_2_cand_1_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/gen_2/gen_2_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/240422_Run19_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/gen_2/gen_2_cand_1_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/gen_2/gen_2_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/240422_Run19_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/netParams_popParams.json ... 

Start time:  2024-04-22 15:42:10.416747
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/netParams_popParams.json ... 

Creating network of 2 cell populations on 4 hosts...
  Number of cells on node 0: 100 
  Number of cells on node 2: 100 
  Number of cells on node 1: 100 
  Number of cells on node 3: 100 
  Done; cell creation time = 0.01 s.
Making connections...
  Number of connections on node 3: 264 
  Number of connections on node 0: 252 
  Number of connections on node 2: 249 
  Number of connections on node 1: 253 
  Done; cell connection time = 0.79 s.
Adding stims...
  Number of stims on node 1: 100 
  Number of stims on node 2: 100 
  Number of stims on node 0: 100 
  Number of stims on node 3: 100 
  Done; cell stims creation time = 0.02 s.
Recording 0 traces of 0 types on node 1
Recording 0 traces of 0 types on node 2
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 30000.0 ms...
  Done; run time = 29.02 s; real-time ratio: 1.03.

Gathering data...
  Done; gather time = 0.11 s.

Analyzing...
  Cells: 400
  Connections: 1418 (3.54 per cell)
  Spikes: 2483 (0.21 Hz)
  Simulated time: 30.0 s; 4 workers
  Run time: 29.02 s
   E : 0.000 Hz
   I : 0.056 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/gen_2/gen_2_cand_1_data.json ... 
Finished saving!
  Done; saving time = 0.48 s.
  Done; plotting time = 0.00 s

Total time = 30.46 s
