
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240429_Run22_debug_run/gen_0/gen_0_cand_2_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240429_Run22_debug_run/gen_0/gen_0_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240429_Run22_debug_run/240429_Run22_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240429_Run22_debug_run/netParams_popParams.json ... 

Start time:  2024-04-29 16:38:55.280790

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.04 s.
Making connections...
  Number of connections on node 0: 3800 
  Done; cell connection time = 1.56 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 22.73 s; real-time ratio: 0.22.

Gathering data...
  Done; gather time = 0.09 s.

Analyzing...
  Cells: 400
  Connections: 3800 (9.50 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 22.73 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240429_Run22_debug_run/gen_0/gen_0_cand_2_data.json ... 
Finished saving!
  Done; saving time = 0.23 s.
  Done; plotting time = 0.00 s

Total time = 24.67 s
