numprocs=4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/gen_2/gen_2_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/gen_2/gen_2_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/240422_Run19_test_uneven_netParams.py
Loading file netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/gen_2/gen_2_cand_2_cfg.json
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/netParams_popParams.json ... 
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/gen_2/gen_2_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/240422_Run19_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/gen_2/gen_2_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/gen_2/gen_2_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/240422_Run19_test_uneven_netParams.py
Loading file netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/gen_2/gen_2_cand_2_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/gen_2/gen_2_cand_2_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/240422_Run19_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/netParams_popParams.json ... 

Start time:  2024-04-22 15:42:10.467434

Creating network of 2 cell populations on 4 hosts...
  Number of cells on node 0: 100 
  Number of cells on node 1: 100 
  Number of cells on node 3: 100 
  Number of cells on node 2: 100 
  Done; cell creation time = 0.02 s.
Making connections...
  Number of connections on node 1: 5493 
  Number of connections on node 3: 5500 
  Number of connections on node 2: 5677 
  Number of connections on node 0: 5533 
  Done; cell connection time = 1.45 s.
Adding stims...
  Number of stims on node 2: 100 
  Number of stims on node 3: 100 
  Number of stims on node 1: 100 
  Number of stims on node 0: 100 
  Done; cell stims creation time = 0.02 s.
Recording 0 traces of 0 types on node 0
Recording 0 traces of 0 types on node 1
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 2

Running simulation using NEURON for 30000.0 ms...
  Done; run time = 235.43 s; real-time ratio: 0.13.

Gathering data...
  Done; gather time = 1.32 s.

Analyzing...
  Cells: 400
  Connections: 22603 (56.51 per cell)
  Spikes: 788288 (65.69 Hz)
  Simulated time: 30.0 s; 4 workers
  Run time: 235.43 s
   E : 29.960 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run19_test_uneven/gen_2/gen_2_cand_2_data.json ... 
Finished saving!
  Done; saving time = 2.28 s.
  Done; plotting time = 0.00 s

Total time = 240.62 s
