
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_3/gen_3_cand_12_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_3/gen_3_cand_12_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 05:34:00.064172

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.86 s.
Making connections...
  Number of connections on node 0: 986 
  Done; cell connection time = 81.56 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 2.75 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1253.01 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 4.24 s.

Analyzing...
  Cells: 400
  Connections: 1386 (3.46 per cell)
  Spikes: 126888 (63.44 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1253.01 s
   E : 65.040 Hz
   I : 7.509 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_3/gen_3_cand_12_data.json ... 
Finished saving!
  Done; saving time = 18.58 s.
  Done; plotting time = 0.00 s

Total time = 1368.34 s
first instance of v_init
first instance of tstop
