
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_3/gen_3_cand_59_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_3/gen_3_cand_59_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 05:34:00.098873

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 3.19 s.
Making connections...
  Number of connections on node 0: 196 
  Done; cell connection time = 99.77 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 3.57 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1304.00 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 4.18 s.

Analyzing...
  Cells: 400
  Connections: 596 (1.49 per cell)
  Spikes: 7359 (3.68 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1304.00 s
   E : 3.667 Hz
   I : 3.333 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_3/gen_3_cand_59_data.json ... 
Finished saving!
  Done; saving time = 10.78 s.
  Done; plotting time = 0.00 s

Total time = 1425.87 s
first instance of v_init
first instance of tstop
