
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_3/gen_3_cand_52_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_3/gen_3_cand_52_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 05:33:57.112069

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 3.59 s.
Making connections...
  Number of connections on node 0: 1854 
  Done; cell connection time = 117.06 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 3.88 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 2095.92 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 9.03 s.

Analyzing...
  Cells: 400
  Connections: 2254 (5.63 per cell)
  Spikes: 101704 (50.85 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 2095.92 s
   E : 63.238 Hz
   I : 26.991 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_3/gen_3_cand_52_data.json ... 
Finished saving!
  Done; saving time = 19.83 s.
  Done; plotting time = 0.00 s

Total time = 2251.08 s
first instance of v_init
first instance of tstop
