
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_3/gen_3_cand_47_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_3/gen_3_cand_47_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 05:34:18.718907

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.99 s.
Making connections...
  Number of connections on node 0: 169 
  Done; cell connection time = 73.45 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 2.98 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 887.66 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.98 s.

Analyzing...
  Cells: 400
  Connections: 569 (1.42 per cell)
  Spikes: 15034 (7.52 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 887.66 s
   E : 7.770 Hz
   I : 7.602 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_3/gen_3_cand_47_data.json ... 
Finished saving!
  Done; saving time = 8.48 s.
  Done; plotting time = 0.00 s

Total time = 979.00 s
first instance of v_init
first instance of tstop
