
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_7/gen_7_cand_64_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_7/gen_7_cand_64_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 09:47:30.073677

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.71 s.
Making connections...
  Number of connections on node 0: 305 
  Done; cell connection time = 77.53 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 3.15 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1018.41 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 3.75 s.

Analyzing...
  Cells: 400
  Connections: 705 (1.76 per cell)
  Spikes: 24879 (12.44 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1018.41 s
   E : 11.762 Hz
   I : 3.398 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_7/gen_7_cand_64_data.json ... 
Finished saving!
  Done; saving time = 10.68 s.
  Done; plotting time = 0.00 s

Total time = 1120.82 s
first instance of v_init
first instance of tstop
