
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run10_debug_run/gen_0/gen_0_cand_3_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run10_debug_run/gen_0/gen_0_cand_3_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run10_debug_run/240426_Run10_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run10_debug_run/netParams_popParams.json ... 

Start time:  2024-04-26 11:33:00.886903

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.06 s.
Making connections...
  Number of connections on node 0: 16720 
  Done; cell connection time = 3.26 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.03 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 115.46 s; real-time ratio: 0.04.

Gathering data...
  Done; gather time = 0.41 s.

Analyzing...
  Cells: 400
  Connections: 17120 (42.80 per cell)
  Spikes: 110715 (55.36 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 115.46 s
   E : 67.940 Hz
   I : 7.148 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run10_debug_run/gen_0/gen_0_cand_3_data.json ... 
Finished saving!
  Done; saving time = 0.64 s.
  Done; plotting time = 0.00 s

Total time = 119.91 s
