
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_3/gen_3_cand_22_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_3/gen_3_cand_22_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 05:32:39.212517

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.94 s.
Making connections...
  Number of connections on node 0: 371 
  Done; cell connection time = 28.01 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 1.06 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 674.78 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.58 s.

Analyzing...
  Cells: 400
  Connections: 771 (1.93 per cell)
  Spikes: 8165 (4.08 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 674.78 s
   E : 3.528 Hz
   I : 3.954 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_3/gen_3_cand_22_data.json ... 
Finished saving!
  Done; saving time = 6.42 s.
  Done; plotting time = 0.00 s

Total time = 713.90 s
first instance of v_init
first instance of tstop
