/pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC
Current gen: 5
Incoming gen: 5
Arguments have been appended to commands.txt
Initiating Rank: 11
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 11: 3 
  Number of connections on node 11: 140 
  Number of stims on node 11: 0 
Recording 0 traces of 0 types on node 11
Initiating Rank: 13
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 13: 3 
  Number of connections on node 13: 153 
  Number of stims on node 13: 0 
Recording 1 traces of 1 types on node 13
Initiating Rank: 17
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 17: 3 
  Number of connections on node 17: 166 
  Number of stims on node 17: 0 
Recording 0 traces of 0 types on node 17
Initiating Rank: 19
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 19: 3 
  Number of connections on node 19: 132 
  Number of stims on node 19: 0 
Recording 0 traces of 0 types on node 19
Initiating Rank: 21
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 21: 3 
  Number of connections on node 21: 150 
  Number of stims on node 21: 0 
Recording 0 traces of 0 types on node 21
Initiating Rank: 23
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 23: 3 
  Number of connections on node 23: 146 
  Number of stims on node 23: 0 
Recording 0 traces of 0 types on node 23
Initiating Rank: 25
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 25: 3 
  Number of connections on node 25: 152 
  Number of stims on node 25: 0 
Recording 0 traces of 0 types on node 25
Initiating Rank: 27
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 27: 3 
  Number of connections on node 27: 142 
  Number of stims on node 27: 0 
Recording 0 traces of 0 types on node 27
Initiating Rank: 29
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 29: 3 
  Number of connections on node 29: 170 
  Number of stims on node 29: 0 
Recording 0 traces of 0 types on node 29
Initiating Rank: 31
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 31: 3 
  Number of connections on node 31: 149 
  Number of stims on node 31: 0 
Recording 0 traces of 0 types on node 31
Initiating Rank: 32
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 32: 3 
  Number of connections on node 32: 161 
  Number of stims on node 32: 0 
Recording 0 traces of 0 types on node 32
Initiating Rank: 33
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 33: 3 
  Number of connections on node 33: 185 
  Number of stims on node 33: 0 
Recording 0 traces of 0 types on node 33
Initiating Rank: 34
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 34: 3 
  Number of connections on node 34: 151 
  Number of stims on node 34: 0 
Recording 0 traces of 0 types on node 34
Initiating Rank: 35
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 35: 3 
  Number of connections on node 35: 160 
  Number of stims on node 35: 0 
Recording 0 traces of 0 types on node 35
Initiating Rank: 36
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 36: 3 
  Number of connections on node 36: 156 
  Number of stims on node 36: 0 
Recording 0 traces of 0 types on node 36
Initiating Rank: 37
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 37: 3 
  Number of connections on node 37: 168 
  Number of stims on node 37: 0 
Recording 0 traces of 0 types on node 37
Initiating Rank: 38
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 38: 3 
  Number of connections on node 38: 157 
  Number of stims on node 38: 0 
Recording 0 traces of 0 types on node 38
Initiating Rank: 39
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 39: 3 
  Number of connections on node 39: 134 
  Number of stims on node 39: 0 
Recording 0 traces of 0 types on node 39
Initiating Rank: 40
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 40: 3 
  Number of connections on node 40: 174 
  Number of stims on node 40: 0 
Recording 0 traces of 0 types on node 40
Initiating Rank: 41
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 41: 3 
  Number of connections on node 41: 158 
  Number of stims on node 41: 0 
Recording 0 traces of 0 types on node 41
Initiating Rank: 42
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 42: 3 
  Number of connections on node 42: 164 
  Number of stims on node 42: 0 
Recording 0 traces of 0 types on node 42
Initiating Rank: 43
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 43: 3 
  Number of connections on node 43: 170 
  Number of stims on node 43: 0 
Recording 0 traces of 0 types on node 43
Initiating Rank: 44
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 44: 3 
  Number of connections on node 44: 135 
  Number of stims on node 44: 0 
Recording 0 traces of 0 types on node 44
Initiating Rank: 45
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 45: 3 
  Number of connections on node 45: 170 
  Number of stims on node 45: 0 
Recording 0 traces of 0 types on node 45
Initiating Rank: 46
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 46: 3 
  Number of connections on node 46: 167 
  Number of stims on node 46: 0 
Recording 0 traces of 0 types on node 46
Initiating Rank: 47
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 47: 2 
  Number of connections on node 47: 119 
  Number of stims on node 47: 0 
Recording 0 traces of 0 types on node 47
Initiating Rank: 1
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 1: 3 
  Number of connections on node 1: 172 
  Number of stims on node 1: 0 
Recording 0 traces of 0 types on node 1
Initiating Rank: 2
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 2: 3 
  Number of connections on node 2: 202 
  Number of stims on node 2: 0 
Recording 0 traces of 0 types on node 2
Initiating Rank: 3
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 3: 3 
  Number of connections on node 3: 191 
  Number of stims on node 3: 0 
Recording 0 traces of 0 types on node 3
Initiating Rank: 4
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 4: 3 
  Number of connections on node 4: 142 
  Number of stims on node 4: 0 
Recording 0 traces of 0 types on node 4
Initiating Rank: 5
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 5: 3 
  Number of connections on node 5: 156 
  Number of stims on node 5: 0 
Recording 0 traces of 0 types on node 5
Initiating Rank: 6
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 6: 3 
  Number of connections on node 6: 151 
  Number of stims on node 6: 0 
Recording 0 traces of 0 types on node 6
Initiating Rank: 7
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 7: 3 
  Number of connections on node 7: 190 
  Number of stims on node 7: 0 
Recording 0 traces of 0 types on node 7
Initiating Rank: 8
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 8: 3 
  Number of connections on node 8: 173 
  Number of stims on node 8: 0 
Recording 1 traces of 1 types on node 8
Initiating Rank: 9
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 9: 3 
  Number of connections on node 9: 183 
  Number of stims on node 9: 0 
Recording 1 traces of 1 types on node 9
Initiating Rank: 10
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 10: 3 
  Number of connections on node 10: 158 
  Number of stims on node 10: 0 
Recording 0 traces of 0 types on node 10
Initiating Rank: 12
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 12: 3 
  Number of connections on node 12: 171 
  Number of stims on node 12: 0 
Recording 0 traces of 0 types on node 12
Initiating Rank: 14
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 14: 3 
  Number of connections on node 14: 171 
  Number of stims on node 14: 0 
Recording 0 traces of 0 types on node 14
Initiating Rank: 15
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 15: 3 
  Number of connections on node 15: 156 
  Number of stims on node 15: 0 
Recording 0 traces of 0 types on node 15
Initiating Rank: 16
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 16: 3 
  Number of connections on node 16: 152 
  Number of stims on node 16: 0 
Recording 0 traces of 0 types on node 16
Initiating Rank: 18
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 18: 3 
  Number of connections on node 18: 176 
  Number of stims on node 18: 0 
Recording 0 traces of 0 types on node 18
Initiating Rank: 20
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 20: 3 
  Number of connections on node 20: 169 
  Number of stims on node 20: 0 
Recording 1 traces of 1 types on node 20
Initiating Rank: 22
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 22: 3 
  Number of connections on node 22: 190 
  Number of stims on node 22: 0 
Recording 0 traces of 0 types on node 22
Initiating Rank: 24
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 24: 3 
  Number of connections on node 24: 161 
  Number of stims on node 24: 0 
Recording 0 traces of 0 types on node 24
Initiating Rank: 26
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 26: 3 
  Number of connections on node 26: 161 
  Number of stims on node 26: 0 
Recording 0 traces of 0 types on node 26
Initiating Rank: 28
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 28: 3 
  Number of connections on node 28: 179 
  Number of stims on node 28: 0 
Recording 0 traces of 0 types on node 28
Initiating Rank: 30
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 
  Number of cells on node 30: 3 
  Number of connections on node 30: 179 
  Number of stims on node 30: 0 
Recording 0 traces of 0 types on node 30
Initiating Rank: 0
CWD: /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/240604_Run1_24n24hr_netParams.py
im here second
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/netParams_popParams.json ... 

Start time:  2024-06-05 13:28:20.758050

Creating network of 2 cell populations on 48 hosts...
  Number of cells on node 0: 3 
  Done; cell creation time = 0.00 s.
Making connections...
  Number of connections on node 0: 183 
  Done; cell connection time = 0.15 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 330000.0 ms...
  Done; run time = 88.65 s; real-time ratio: 3.72.

Gathering data...
  Done; gather time = 4.53 s.

Analyzing...
  Cells: 143
  Connections: 7795 (54.51 per cell)
  Spikes: 1296430 (27.47 Hz)
  Simulated time: 330.0 s; 48 workers
  Run time: 88.65 s
   E : 16.533 Hz
   I : 12.687 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240604_Run1_24n24hr/gen_5/gen_5_cand_328_data.json ... 
Finished saving!
  Done; saving time = 20.62 s.
  Done; plotting time = 0.00 s

Total time = 114.29 s
numprocs=48
