
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_1/gen_1_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_1/gen_1_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/240430_Run1_interactive_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 13:31:38.079460

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.47 s.
Making connections...
  Number of connections on node 0: 8346 
  Done; cell connection time = 9.91 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 625.43 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 1.98 s.

Analyzing...
  Cells: 400
  Connections: 8346 (20.86 per cell)
  Spikes: 137288 (34.32 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 625.43 s
   E : 47.159 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_1/gen_1_cand_73_data.json ... 
Finished saving!
  Done; saving time = 4.65 s.
  Done; plotting time = 0.00 s

Total time = 642.67 s
