
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_3/gen_3_cand_31_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_3/gen_3_cand_31_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/240430_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 15:08:14.966366

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.74 s.
Making connections...
  Number of connections on node 0: 43033 
  Done; cell connection time = 30.67 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 1525.63 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 1.08 s.

Analyzing...
  Cells: 400
  Connections: 43033 (107.58 per cell)
  Spikes: 1590 (0.40 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 1525.63 s
   E : 0.000 Hz
   I : 7.500 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_3/gen_3_cand_31_data.json ... 
Finished saving!
  Done; saving time = 1.71 s.
  Done; plotting time = 0.00 s

Total time = 1559.84 s
