
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_3/gen_3_cand_98_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_3/gen_3_cand_98_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/240430_Run2_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 15:08:26.690708

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.30 s.
Making connections...
  Number of connections on node 0: 1477 
  Done; cell connection time = 6.04 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 212.98 s; real-time ratio: 0.05.

Gathering data...
  Done; gather time = 0.36 s.

Analyzing...
  Cells: 400
  Connections: 1477 (3.69 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 212.98 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run2_debug_node_run/gen_3/gen_3_cand_98_data.json ... 
Finished saving!
  Done; saving time = 1.67 s.
  Done; plotting time = 0.00 s

Total time = 221.36 s
