numprocs=4
numprocs=4
numprocs=4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json
Loading file /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json
Loading file /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json
Loading file /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json
Loading file /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /app/NERSC/output/240510_Run1_local_debug/240510_Run1_local_debug_netParams.py
[Errno 2] No such file or directory: '/app/NERSC/output/240510_Run1_local_debug/batch_config.json'

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json
Loading file /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /app/NERSC/output/240510_Run1_local_debug/240510_Run1_local_debug_netParams.py
[Errno 2] No such file or directory: '/app/NERSC/output/240510_Run1_local_debug/batch_config.json'

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json
Loading file /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /app/NERSC/output/240510_Run1_local_debug/240510_Run1_local_debug_netParams.py
[Errno 2] No such file or directory: '/app/NERSC/output/240510_Run1_local_debug/batch_config.json'

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json
Loading file /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /app/NERSC/output/240510_Run1_local_debug/240510_Run1_local_debug_netParams.py
[Errno 2] No such file or directory: '/app/NERSC/output/240510_Run1_local_debug/batch_config.json'

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json
Loading file /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /app/NERSC/output/240510_Run1_local_debug/240510_Run1_local_debug_netParams.py
[Errno 2] No such file or directory: '/app/NERSC/output/240510_Run1_local_debug/batch_config.json'

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json
Loading file /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /app/NERSC/output/240510_Run1_local_debug/240510_Run1_local_debug_netParams.py
[Errno 2] No such file or directory: '/app/NERSC/output/240510_Run1_local_debug/batch_config.json'

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json
Loading file /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /app/NERSC/output/240510_Run1_local_debug/240510_Run1_local_debug_netParams.py
[Errno 2] No such file or directory: '/app/NERSC/output/240510_Run1_local_debug/batch_config.json'

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json
Loading file /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /app/NERSC/output/240510_Run1_local_debug/240510_Run1_local_debug_netParams.py
[Errno 2] No such file or directory: '/app/NERSC/output/240510_Run1_local_debug/batch_config.json'

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json
Loading file /app/NERSC/output/240510_Run1_local_debug/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /app/NERSC/output/240510_Run1_local_debug/240510_Run1_local_debug_netParams.py
[Errno 2] No such file or directory: '/app/NERSC/output/240510_Run1_local_debug/batch_config.json'
