
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/gen_0/gen_0_cand_76_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/gen_0/gen_0_cand_76_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/240426_Run2_scaling_up_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/netParams_popParams.json ... 

Start time:  2024-04-26 10:19:13.902318

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.08 s.
Making connections...
  Number of connections on node 0: 22312 
  Done; cell connection time = 4.42 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.05 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 235.80 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 0.65 s.

Analyzing...
  Cells: 400
  Connections: 22712 (56.78 per cell)
  Spikes: 34057 (17.03 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 235.80 s
   E : 28.179 Hz
   I : 10.537 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/gen_0/gen_0_cand_76_data.json ... 
Finished saving!
  Done; saving time = 0.81 s.
  Done; plotting time = 0.00 s

Total time = 241.82 s
first instance of v_init
first instance of tstop
