
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/gen_0/gen_0_cand_89_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/gen_0/gen_0_cand_89_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/240426_Run2_scaling_up_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/netParams_popParams.json ... 

Start time:  2024-04-26 10:19:15.415870

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.07 s.
Making connections...
  Number of connections on node 0: 36220 
  Done; cell connection time = 10.10 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.08 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 339.37 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 0.91 s.

Analyzing...
  Cells: 400
  Connections: 36620 (91.55 per cell)
  Spikes: 36642 (18.32 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 339.37 s
   E : 44.218 Hz
   I : 7.204 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/gen_0/gen_0_cand_89_data.json ... 
Finished saving!
  Done; saving time = 1.16 s.
  Done; plotting time = 0.00 s

Total time = 351.72 s
first instance of v_init
first instance of tstop
