
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/gen_0/gen_0_cand_32_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/gen_0/gen_0_cand_32_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/240426_Run2_scaling_up_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/netParams_popParams.json ... 

Start time:  2024-04-26 10:19:10.505808

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.05 s.
Making connections...
  Number of connections on node 0: 25292 
  Done; cell connection time = 4.52 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.08 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 294.67 s; real-time ratio: 0.02.

Gathering data...
  Done; gather time = 0.69 s.

Analyzing...
  Cells: 400
  Connections: 25692 (64.23 per cell)
  Spikes: 89396 (44.70 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 294.67 s
   E : 36.234 Hz
   I : 15.509 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/gen_0/gen_0_cand_32_data.json ... 
Finished saving!
  Done; saving time = 0.95 s.
  Done; plotting time = 0.00 s

Total time = 300.98 s
first instance of v_init
first instance of tstop
