
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run10_debug_run/gen_0/gen_0_cand_0_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run10_debug_run/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run10_debug_run/240426_Run10_debug_run_netParams.py
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run10_debug_run/netParams_popParams.json ... 

Start time:  2024-04-26 11:32:56.860408

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.03 s.
Making connections...
  Number of connections on node 0: 25345 
  Done; cell connection time = 4.36 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.06 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 130.75 s; real-time ratio: 0.04.

Gathering data...
  Done; gather time = 0.55 s.

Analyzing...
  Cells: 400
  Connections: 25745 (64.36 per cell)
  Spikes: 172 (0.09 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 130.75 s
   E : 0.000 Hz
   I : 0.454 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240426_Run10_debug_run/gen_0/gen_0_cand_0_data.json ... 
Finished saving!
  Done; saving time = 0.64 s.
  Done; plotting time = 0.00 s

Total time = 136.41 s
