
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run12_testing_run_name/gen_0/gen_0_cand_1_cfg.json
Loading file /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run12_testing_run_name/gen_0/gen_0_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run12_testing_run_name/240414_Run12_testing_run_name_netParams.py
Duration: 1 seconds
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run12_testing_run_name/netParams_popParams.json ... 

Start time:  2024-04-14 01:13:34.345650

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.05 s.
Making connections...
  Number of connections on node 0: 53455 
  Done; cell connection time = 7.65 s.
Adding stims...
  Number of stims on node 0: 800 
  Done; cell stims creation time = 0.08 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 30000.0 ms...
  Done; run time = 7463.60 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 1.87 s.

Analyzing...
  Cells: 400
  Connections: 53855 (134.64 per cell)
  Synaptic contacts: 54255 (135.64 per cell)
  Spikes: 189397 (15.78 Hz)
  Simulated time: 30.0 s; 1 workers
  Run time: 7463.60 s
   E : 46.085 Hz
   I : 15.656 Hz
Saving output as /mnt/c/Users/adamm/Documents/.repos/2DNetworkSimulations/NERSC/output/240414_Run12_testing_run_name/gen_0/gen_0_cand_1_data.json ... 
Finished saving!
  Done; saving time = 2.46 s.
  Done; plotting time = 0.00 s

Total time = 7475.88 s
