
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run25_debug_node_run/gen_0/gen_0_cand_49_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run25_debug_node_run/gen_0/gen_0_cand_49_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run25_debug_node_run/240429_Run25_debug_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run25_debug_node_run/netParams_popParams.json ... 

Start time:  2024-04-29 21:03:05.587421

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.32 s.
Making connections...
  Number of connections on node 0: 18630 
  Done; cell connection time = 7.54 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 947.48 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 1.19 s.

Analyzing...
  Cells: 400
  Connections: 18630 (46.58 per cell)
  Spikes: 103315 (25.83 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 947.48 s
   E : 61.429 Hz
   I : 7.657 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run25_debug_node_run/gen_0/gen_0_cand_49_data.json ... 
Finished saving!
  Done; saving time = 2.97 s.
  Done; plotting time = 0.00 s

Total time = 959.55 s
first instance of v_init
first instance of tstop
