
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run1_interactive_debug/gen_2/gen_2_cand_6_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run1_interactive_debug/gen_2/gen_2_cand_6_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run1_interactive_debug/240429_Run1_interactive_debug_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run1_interactive_debug/netParams_popParams.json ... 

Start time:  2024-04-29 00:25:30.523808

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.04 s.
Making connections...
  Number of connections on node 0: 71926 
  Done; cell connection time = 7.89 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 347.39 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 1.58 s.

Analyzing...
  Cells: 400
  Connections: 71926 (179.81 per cell)
  Spikes: 20501 (10.25 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 347.39 s
   E : 39.504 Hz
   I : 3.352 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run1_interactive_debug/gen_2/gen_2_cand_6_data.json ... 
Finished saving!
  Done; saving time = 2.54 s.
  Done; plotting time = 0.00 s

Total time = 359.46 s
first instance of v_init
first instance of tstop
