numprocs=4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run21_test_uneven/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run21_test_uneven/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run21_test_uneven/240422_Run21_test_uneven_netParams.py
Loading file netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run21_test_uneven/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run21_test_uneven/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run21_test_uneven/240422_Run21_test_uneven_netParams.py
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run21_test_uneven/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run21_test_uneven/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run21_test_uneven/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run21_test_uneven/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run21_test_uneven/240422_Run21_test_uneven_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run21_test_uneven/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run21_test_uneven/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run21_test_uneven/240422_Run21_test_uneven_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run21_test_uneven/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run21_test_uneven/netParams_popParams.json ... 

Start time:  2024-04-22 15:53:00.321563

Creating network of 2 cell populations on 4 hosts...
  Number of cells on node 0: 100 
  Number of cells on node 1: 100 
  Number of cells on node 2: 100 
  Number of cells on node 3: 100 
  Done; cell creation time = 0.01 s.
Making connections...
  Number of connections on node 2: 11832 
  Number of connections on node 3: 11697 
  Number of connections on node 1: 11748 
  Number of connections on node 0: 11823 
  Done; cell connection time = 1.88 s.
Adding stims...
  Number of stims on node 2: 100 
  Number of stims on node 3: 100 
  Number of stims on node 0: 100 
  Number of stims on node 1: 100 
  Done; cell stims creation time = 0.01 s.
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 2
Recording 0 traces of 0 types on node 1
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 30000.0 ms...
  Done; run time = 721.03 s; real-time ratio: 0.04.

Gathering data...
  Done; gather time = 1.11 s.

Analyzing...
  Cells: 400
  Connections: 47500 (118.75 per cell)
  Spikes: 164192 (13.68 Hz)
  Simulated time: 30.0 s; 4 workers
  Run time: 721.03 s
   E : 41.750 Hz
   I : 3.046 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run21_test_uneven/gen_0/gen_0_cand_0_data.json ... 
Finished saving!
  Done; saving time = 1.82 s.
  Done; plotting time = 0.00 s

Total time = 725.90 s
