Initiating Rank: 3

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 3: 4 
  Number of connections on node 3: 407 
  Number of stims on node 3: 0 
Recording 0 traces of 0 types on node 3
Initiating Rank: 9

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 9: 4 
  Number of connections on node 9: 403 
  Number of stims on node 9: 0 
Recording 0 traces of 0 types on node 9
Initiating Rank: 16

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 16: 3 
  Number of connections on node 16: 340 
  Number of stims on node 16: 0 
Recording 0 traces of 0 types on node 16
Initiating Rank: 18

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 18: 3 
  Number of connections on node 18: 259 
  Number of stims on node 18: 0 
Recording 0 traces of 0 types on node 18
Initiating Rank: 19

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 19: 3 
  Number of connections on node 19: 322 
  Number of stims on node 19: 0 
Recording 0 traces of 0 types on node 19
Initiating Rank: 21

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 21: 3 
  Number of connections on node 21: 306 
  Number of stims on node 21: 0 
Recording 0 traces of 0 types on node 21
Initiating Rank: 22

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 22: 3 
  Number of connections on node 22: 312 
  Number of stims on node 22: 0 
Recording 0 traces of 0 types on node 22
Initiating Rank: 23

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 23: 3 
  Number of connections on node 23: 265 
  Number of stims on node 23: 0 
Recording 0 traces of 0 types on node 23
Initiating Rank: 24

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 24: 3 
  Number of connections on node 24: 287 
  Number of stims on node 24: 0 
Recording 1 traces of 1 types on node 24
Initiating Rank: 25

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 25: 3 
  Number of connections on node 25: 320 
  Number of stims on node 25: 0 
Recording 0 traces of 0 types on node 25
Initiating Rank: 26

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 26: 3 
  Number of connections on node 26: 332 
  Number of stims on node 26: 0 
Recording 0 traces of 0 types on node 26
Initiating Rank: 27

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 27: 3 
  Number of connections on node 27: 300 
  Number of stims on node 27: 0 
Recording 0 traces of 0 types on node 27
Initiating Rank: 29

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 29: 3 
  Number of connections on node 29: 336 
  Number of stims on node 29: 0 
Recording 0 traces of 0 types on node 29
Initiating Rank: 32

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 32: 3 
  Number of connections on node 32: 307 
  Number of stims on node 32: 0 
Recording 0 traces of 0 types on node 32
Initiating Rank: 33

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 33: 3 
  Number of connections on node 33: 318 
  Number of stims on node 33: 0 
Recording 0 traces of 0 types on node 33
Initiating Rank: 34

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 34: 3 
  Number of connections on node 34: 310 
  Number of stims on node 34: 0 
Recording 0 traces of 0 types on node 34
Initiating Rank: 35

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 35: 3 
  Number of connections on node 35: 294 
  Number of stims on node 35: 0 
Recording 0 traces of 0 types on node 35
Initiating Rank: 36

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 36: 3 
  Number of connections on node 36: 289 
  Number of stims on node 36: 0 
Recording 0 traces of 0 types on node 36
Initiating Rank: 37

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 37: 3 
  Number of connections on node 37: 341 
  Number of stims on node 37: 0 
Recording 0 traces of 0 types on node 37
Initiating Rank: 38

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 38: 3 
  Number of connections on node 38: 318 
  Number of stims on node 38: 0 
Recording 0 traces of 0 types on node 38
Initiating Rank: 39

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 39: 3 
  Number of connections on node 39: 290 
  Number of stims on node 39: 0 
Recording 0 traces of 0 types on node 39
Initiating Rank: 40

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 40: 3 
  Number of connections on node 40: 388 
  Number of stims on node 40: 0 
Recording 0 traces of 0 types on node 40
Initiating Rank: 41

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 41: 3 
  Number of connections on node 41: 285 
  Number of stims on node 41: 0 
Recording 0 traces of 0 types on node 41
Initiating Rank: 42

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 42: 3 
  Number of connections on node 42: 299 
  Number of stims on node 42: 0 
Recording 0 traces of 0 types on node 42
Initiating Rank: 43

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 43: 3 
  Number of connections on node 43: 342 
  Number of stims on node 43: 0 
Recording 0 traces of 0 types on node 43
Initiating Rank: 44

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 44: 3 
  Number of connections on node 44: 322 
  Number of stims on node 44: 0 
Recording 0 traces of 0 types on node 44
Initiating Rank: 45

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 45: 3 
  Number of connections on node 45: 337 
  Number of stims on node 45: 0 
Recording 0 traces of 0 types on node 45
Initiating Rank: 46

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 46: 3 
  Number of connections on node 46: 271 
  Number of stims on node 46: 0 
Recording 0 traces of 0 types on node 46
Initiating Rank: 47

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 47: 3 
  Number of connections on node 47: 239 
  Number of stims on node 47: 0 
Recording 0 traces of 0 types on node 47
Initiating Rank: 48

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 48: 3 
  Number of connections on node 48: 316 
  Number of stims on node 48: 0 
Recording 0 traces of 0 types on node 48
Initiating Rank: 49

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 49: 3 
  Number of connections on node 49: 313 
  Number of stims on node 49: 0 
Recording 0 traces of 0 types on node 49
Initiating Rank: 50

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 50: 3 
  Number of connections on node 50: 349 
  Number of stims on node 50: 0 
Recording 0 traces of 0 types on node 50
Initiating Rank: 51

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 51: 3 
  Number of connections on node 51: 317 
  Number of stims on node 51: 0 
Recording 0 traces of 0 types on node 51
Initiating Rank: 52

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 52: 3 
  Number of connections on node 52: 321 
  Number of stims on node 52: 0 
Recording 0 traces of 0 types on node 52
Initiating Rank: 53

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 53: 3 
  Number of connections on node 53: 327 
  Number of stims on node 53: 0 
Recording 0 traces of 0 types on node 53
Initiating Rank: 54

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 54: 3 
  Number of connections on node 54: 295 
  Number of stims on node 54: 0 
Recording 0 traces of 0 types on node 54
Initiating Rank: 55

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 55: 3 
  Number of connections on node 55: 285 
  Number of stims on node 55: 0 
Recording 0 traces of 0 types on node 55
Initiating Rank: 56

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 56: 3 
  Number of connections on node 56: 277 
  Number of stims on node 56: 0 
Recording 0 traces of 0 types on node 56
Initiating Rank: 57

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 57: 3 
  Number of connections on node 57: 348 
  Number of stims on node 57: 0 
Recording 0 traces of 0 types on node 57
Initiating Rank: 58

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 58: 3 
  Number of connections on node 58: 317 
  Number of stims on node 58: 0 
Recording 0 traces of 0 types on node 58
Initiating Rank: 59

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 59: 3 
  Number of connections on node 59: 345 
  Number of stims on node 59: 0 
Recording 0 traces of 0 types on node 59
Initiating Rank: 60

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 60: 3 
  Number of connections on node 60: 309 
  Number of stims on node 60: 0 
Recording 0 traces of 0 types on node 60
Initiating Rank: 61

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 61: 3 
  Number of connections on node 61: 290 
  Number of stims on node 61: 0 
Recording 0 traces of 0 types on node 61
Initiating Rank: 62

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 62: 3 
  Number of connections on node 62: 320 
  Number of stims on node 62: 0 
Recording 0 traces of 0 types on node 62
Initiating Rank: 63

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 63: 3 
  Number of connections on node 63: 303 
  Number of stims on node 63: 0 
Recording 0 traces of 0 types on node 63
Initiating Rank: 64

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 64: 3 
  Number of connections on node 64: 300 
  Number of stims on node 64: 0 
Recording 0 traces of 0 types on node 64
Initiating Rank: 65

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 65: 3 
  Number of connections on node 65: 306 
  Number of stims on node 65: 0 
Recording 0 traces of 0 types on node 65
Initiating Rank: 66

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 66: 3 
  Number of connections on node 66: 347 
  Number of stims on node 66: 0 
Recording 0 traces of 0 types on node 66
Initiating Rank: 67

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 67: 3 
  Number of connections on node 67: 353 
  Number of stims on node 67: 0 
Recording 0 traces of 0 types on node 67
Initiating Rank: 68

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 68: 3 
  Number of connections on node 68: 356 
  Number of stims on node 68: 0 
Recording 0 traces of 0 types on node 68
Initiating Rank: 69

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 69: 3 
  Number of connections on node 69: 267 
  Number of stims on node 69: 0 
Recording 0 traces of 0 types on node 69
Initiating Rank: 70

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 70: 3 
  Number of connections on node 70: 319 
  Number of stims on node 70: 0 
Recording 0 traces of 0 types on node 70
Initiating Rank: 71

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 71: 3 
  Number of connections on node 71: 316 
  Number of stims on node 71: 0 
Recording 0 traces of 0 types on node 71
Initiating Rank: 72

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 72: 3 
  Number of connections on node 72: 285 
  Number of stims on node 72: 0 
Recording 0 traces of 0 types on node 72
Initiating Rank: 73

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 73: 3 
  Number of connections on node 73: 288 
  Number of stims on node 73: 0 
Recording 0 traces of 0 types on node 73
Initiating Rank: 74

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 74: 3 
  Number of connections on node 74: 374 
  Number of stims on node 74: 0 
Recording 0 traces of 0 types on node 74
Initiating Rank: 75

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 75: 3 
  Number of connections on node 75: 355 
  Number of stims on node 75: 0 
Recording 0 traces of 0 types on node 75
Initiating Rank: 76

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 76: 3 
  Number of connections on node 76: 322 
  Number of stims on node 76: 0 
Recording 0 traces of 0 types on node 76
Initiating Rank: 77

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 77: 3 
  Number of connections on node 77: 296 
  Number of stims on node 77: 0 
Recording 0 traces of 0 types on node 77
Initiating Rank: 78

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 78: 3 
  Number of connections on node 78: 338 
  Number of stims on node 78: 0 
Recording 0 traces of 0 types on node 78
Initiating Rank: 79

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 79: 3 
  Number of connections on node 79: 261 
  Number of stims on node 79: 0 
Recording 0 traces of 0 types on node 79
Initiating Rank: 80

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 80: 3 
  Number of connections on node 80: 287 
  Number of stims on node 80: 0 
Recording 0 traces of 0 types on node 80
Initiating Rank: 81

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 81: 3 
  Number of connections on node 81: 300 
  Number of stims on node 81: 0 
Recording 0 traces of 0 types on node 81
Initiating Rank: 82

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 82: 3 
  Number of connections on node 82: 302 
  Number of stims on node 82: 0 
Recording 0 traces of 0 types on node 82
Initiating Rank: 83

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 83: 3 
  Number of connections on node 83: 347 
  Number of stims on node 83: 0 
Recording 0 traces of 0 types on node 83
Initiating Rank: 84

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 84: 3 
  Number of connections on node 84: 237 
  Number of stims on node 84: 0 
Recording 0 traces of 0 types on node 84
Initiating Rank: 85

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 85: 3 
  Number of connections on node 85: 343 
  Number of stims on node 85: 0 
Recording 0 traces of 0 types on node 85
Initiating Rank: 86

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 86: 3 
  Number of connections on node 86: 323 
  Number of stims on node 86: 0 
Recording 0 traces of 0 types on node 86
Initiating Rank: 87

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 87: 3 
  Number of connections on node 87: 346 
  Number of stims on node 87: 0 
Recording 0 traces of 0 types on node 87
Initiating Rank: 88

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 88: 3 
  Number of connections on node 88: 310 
  Number of stims on node 88: 0 
Recording 0 traces of 0 types on node 88
Initiating Rank: 89

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 89: 3 
  Number of connections on node 89: 261 
  Number of stims on node 89: 0 
Recording 0 traces of 0 types on node 89
Initiating Rank: 90

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 90: 3 
  Number of connections on node 90: 315 
  Number of stims on node 90: 0 
Recording 0 traces of 0 types on node 90
Initiating Rank: 91

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 91: 3 
  Number of connections on node 91: 310 
  Number of stims on node 91: 0 
Recording 0 traces of 0 types on node 91
Initiating Rank: 92

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 92: 3 
  Number of connections on node 92: 318 
  Number of stims on node 92: 0 
Recording 0 traces of 0 types on node 92
Initiating Rank: 93

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 93: 3 
  Number of connections on node 93: 288 
  Number of stims on node 93: 0 
Recording 0 traces of 0 types on node 93
Initiating Rank: 94

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 94: 3 
  Number of connections on node 94: 317 
  Number of stims on node 94: 0 
Recording 0 traces of 0 types on node 94
Initiating Rank: 95

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 95: 3 
  Number of connections on node 95: 360 
  Number of stims on node 95: 0 
Recording 0 traces of 0 types on node 95
Initiating Rank: 96

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 96: 3 
  Number of connections on node 96: 347 
  Number of stims on node 96: 0 
Recording 0 traces of 0 types on node 96
Initiating Rank: 97

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 97: 3 
  Number of connections on node 97: 301 
  Number of stims on node 97: 0 
Recording 0 traces of 0 types on node 97
Initiating Rank: 98

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 98: 3 
  Number of connections on node 98: 306 
  Number of stims on node 98: 0 
Recording 0 traces of 0 types on node 98
Initiating Rank: 99

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 99: 3 
  Number of connections on node 99: 305 
  Number of stims on node 99: 0 
Recording 0 traces of 0 types on node 99
Initiating Rank: 100

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 100: 3 
  Number of connections on node 100: 317 
  Number of stims on node 100: 0 
Recording 0 traces of 0 types on node 100
Initiating Rank: 101

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 101: 3 
  Number of connections on node 101: 269 
  Number of stims on node 101: 0 
Recording 0 traces of 0 types on node 101
Initiating Rank: 102

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 102: 3 
  Number of connections on node 102: 354 
  Number of stims on node 102: 0 
Recording 0 traces of 0 types on node 102
Initiating Rank: 103

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 103: 3 
  Number of connections on node 103: 322 
  Number of stims on node 103: 0 
Recording 0 traces of 0 types on node 103
Initiating Rank: 104

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 104: 3 
  Number of connections on node 104: 288 
  Number of stims on node 104: 0 
Recording 0 traces of 0 types on node 104
Initiating Rank: 105

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 105: 3 
  Number of connections on node 105: 345 
  Number of stims on node 105: 0 
Recording 0 traces of 0 types on node 105
Initiating Rank: 106

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 106: 3 
  Number of connections on node 106: 346 
  Number of stims on node 106: 0 
Recording 0 traces of 0 types on node 106
Initiating Rank: 107

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 107: 3 
  Number of connections on node 107: 333 
  Number of stims on node 107: 0 
Recording 0 traces of 0 types on node 107
Initiating Rank: 108

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 108: 3 
  Number of connections on node 108: 336 
  Number of stims on node 108: 0 
Recording 0 traces of 0 types on node 108
Initiating Rank: 109

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 109: 3 
  Number of connections on node 109: 340 
  Number of stims on node 109: 0 
Recording 0 traces of 0 types on node 109
Initiating Rank: 110

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 110: 3 
  Number of connections on node 110: 346 
  Number of stims on node 110: 0 
Recording 0 traces of 0 types on node 110
Initiating Rank: 111

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 111: 3 
  Number of connections on node 111: 289 
  Number of stims on node 111: 0 
Recording 0 traces of 0 types on node 111
Initiating Rank: 112

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 112: 3 
  Number of connections on node 112: 301 
  Number of stims on node 112: 0 
Recording 0 traces of 0 types on node 112
Initiating Rank: 113

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 113: 3 
  Number of connections on node 113: 314 
  Number of stims on node 113: 0 
Recording 0 traces of 0 types on node 113
Initiating Rank: 114

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 114: 3 
  Number of connections on node 114: 300 
  Number of stims on node 114: 0 
Recording 0 traces of 0 types on node 114
Initiating Rank: 115

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 115: 3 
  Number of connections on node 115: 287 
  Number of stims on node 115: 0 
Recording 0 traces of 0 types on node 115
Initiating Rank: 116

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 116: 3 
  Number of connections on node 116: 272 
  Number of stims on node 116: 0 
Recording 0 traces of 0 types on node 116
Initiating Rank: 117

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 117: 3 
  Number of connections on node 117: 337 
  Number of stims on node 117: 0 
Recording 0 traces of 0 types on node 117
Initiating Rank: 118

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 118: 3 
  Number of connections on node 118: 318 
  Number of stims on node 118: 0 
Recording 0 traces of 0 types on node 118
Initiating Rank: 119

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 119: 3 
  Number of connections on node 119: 314 
  Number of stims on node 119: 0 
Recording 0 traces of 0 types on node 119
Initiating Rank: 120

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 120: 3 
  Number of connections on node 120: 343 
  Number of stims on node 120: 0 
Recording 0 traces of 0 types on node 120
Initiating Rank: 121

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 121: 3 
  Number of connections on node 121: 299 
  Number of stims on node 121: 0 
Recording 0 traces of 0 types on node 121
Initiating Rank: 122

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 122: 3 
  Number of connections on node 122: 349 
  Number of stims on node 122: 0 
Recording 0 traces of 0 types on node 122
Initiating Rank: 123

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 123: 3 
  Number of connections on node 123: 285 
  Number of stims on node 123: 0 
Recording 0 traces of 0 types on node 123
Initiating Rank: 124

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 124: 3 
  Number of connections on node 124: 308 
  Number of stims on node 124: 0 
Recording 0 traces of 0 types on node 124
Initiating Rank: 125

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 125: 3 
  Number of connections on node 125: 296 
  Number of stims on node 125: 0 
Recording 0 traces of 0 types on node 125
Initiating Rank: 126

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 126: 3 
  Number of connections on node 126: 301 
  Number of stims on node 126: 0 
Recording 0 traces of 0 types on node 126
Initiating Rank: 127

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 127: 3 
  Number of connections on node 127: 264 
  Number of stims on node 127: 0 
Recording 0 traces of 0 types on node 127
Initiating Rank: 1

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 1: 4 
  Number of connections on node 1: 494 
  Number of stims on node 1: 0 
Recording 0 traces of 0 types on node 1
Initiating Rank: 2

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 2: 4 
  Number of connections on node 2: 399 
  Number of stims on node 2: 0 
Recording 0 traces of 0 types on node 2
Initiating Rank: 4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 4: 4 
  Number of connections on node 4: 393 
  Number of stims on node 4: 0 
Recording 0 traces of 0 types on node 4
Initiating Rank: 5

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 5: 4 
  Number of connections on node 5: 418 
  Number of stims on node 5: 0 
Recording 0 traces of 0 types on node 5
Initiating Rank: 6

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 6: 4 
  Number of connections on node 6: 381 
  Number of stims on node 6: 0 
Recording 0 traces of 0 types on node 6
Initiating Rank: 7

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 7: 4 
  Number of connections on node 7: 391 
  Number of stims on node 7: 0 
Recording 0 traces of 0 types on node 7
Initiating Rank: 8

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 8: 4 
  Number of connections on node 8: 435 
  Number of stims on node 8: 0 
Recording 0 traces of 0 types on node 8
Initiating Rank: 10

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 10: 4 
  Number of connections on node 10: 399 
  Number of stims on node 10: 0 
Recording 0 traces of 0 types on node 10
Initiating Rank: 11

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 11: 4 
  Number of connections on node 11: 387 
  Number of stims on node 11: 0 
Recording 0 traces of 0 types on node 11
Initiating Rank: 12

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 12: 4 
  Number of connections on node 12: 394 
  Number of stims on node 12: 0 
Recording 0 traces of 0 types on node 12
Initiating Rank: 13

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 13: 4 
  Number of connections on node 13: 364 
  Number of stims on node 13: 0 
Recording 0 traces of 0 types on node 13
Initiating Rank: 14

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 14: 4 
  Number of connections on node 14: 403 
  Number of stims on node 14: 0 
Recording 0 traces of 0 types on node 14
Initiating Rank: 15

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 15: 4 
  Number of connections on node 15: 465 
  Number of stims on node 15: 0 
Recording 0 traces of 0 types on node 15
Initiating Rank: 17

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 17: 3 
  Number of connections on node 17: 282 
  Number of stims on node 17: 0 
Recording 0 traces of 0 types on node 17
Initiating Rank: 20

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 20: 3 
  Number of connections on node 20: 284 
  Number of stims on node 20: 0 
Recording 0 traces of 0 types on node 20
Initiating Rank: 28

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 28: 3 
  Number of connections on node 28: 347 
  Number of stims on node 28: 0 
Recording 0 traces of 0 types on node 28
Initiating Rank: 30

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 30: 3 
  Number of connections on node 30: 283 
  Number of stims on node 30: 0 
Recording 0 traces of 0 types on node 30
Initiating Rank: 31

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ
  Number of cells on node 31: 3 
  Number of connections on node 31: 275 
  Number of stims on node 31: 0 
Recording 0 traces of 0 types on node 31
Initiating Rank: 0

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/240511_Run28_32proc_netParams.py
Flag -d not found.
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/netParams_popParams.json ... 
ADLFKJAS;DLFKJ

Start time:  2024-05-12 01:55:59.188242

Creating network of 2 cell populations on 128 hosts...
  Number of cells on node 0: 4 
  Done; cell creation time = 0.00 s.
Making connections...
  Number of connections on node 0: 399 
  Done; cell connection time = 0.84 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 1 traces of 1 types on node 0

Running simulation using NEURON for 15000.0 ms...
  Done; run time = 15.99 s; real-time ratio: 0.94.

Gathering data...
  Done; gather time = 0.79 s.

Analyzing...
  Cells: 400
  Connections: 41443 (103.61 per cell)
  Spikes: 956 (0.16 Hz)
  Simulated time: 15.0 s; 128 workers
  Run time: 15.99 s
   E : 0.000 Hz
   I : 2.750 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240511_Run28_32proc/gen_0/gen_0_cand_73_data.json ... 
Finished saving!
  Done; saving time = 1.82 s.
  Done; plotting time = 0.00 s

Total time = 19.46 s
numprocs=128
