numprocs=4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 

Start time:  2024-04-22 12:56:12.318441
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/240422_Run9_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/netParams_popParams.json ... 

Creating network of 2 cell populations on 4 hosts...
  Number of cells on node 1: 100 
  Number of cells on node 0: 100 
  Done; cell creation time = 0.09 s.
  Number of cells on node 2: 100 
  Number of cells on node 3: 100 
Making connections...
  Number of connections on node 1: 2439 
  Number of connections on node 2: 2468 
  Number of connections on node 0: 2438 
  Number of connections on node 3: 2386 
  Done; cell connection time = 4.22 s.
Adding stims...
  Number of stims on node 1: 100 
  Number of stims on node 0: 100 
  Number of stims on node 3: 100 
  Number of stims on node 2: 100 
  Done; cell stims creation time = 0.13 s.
Recording 0 traces of 0 types on node 0
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 1
Recording 0 traces of 0 types on node 2

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 87.69 s; real-time ratio: 0.06.

Gathering data...
  Done; gather time = 0.81 s.

Analyzing...
  Cells: 400
  Connections: 10131 (25.33 per cell)
  Spikes: 105758 (52.88 Hz)
  Simulated time: 5.0 s; 4 workers
  Run time: 87.69 s
   E : 11.266 Hz
   I : 30.056 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run9_debug_run/gen_0/gen_0_cand_0_data.json ... 
Finished saving!
  Done; saving time = 1.09 s.
  Done; plotting time = 0.00 s

Total time = 99.50 s
