
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_11/gen_11_cand_47_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_11/gen_11_cand_47_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-27 05:40:58.917952

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.48 s.
Making connections...
  Number of connections on node 0: 608 
  Done; cell connection time = 46.26 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 668.23 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.40 s.

Analyzing...
  Cells: 400
  Connections: 608 (1.52 per cell)
  Spikes: 56560 (28.28 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 668.23 s
   E : 41.111 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_11/gen_11_cand_47_data.json ... 
Finished saving!
  Done; saving time = 14.24 s.
  Done; plotting time = 0.00 s

Total time = 736.31 s
first instance of v_init
first instance of tstop
