
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_1/gen_1_cand_48_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_1/gen_1_cand_48_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/240425_Run4_25AprRunWhileWork_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 13:40:04.656559

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.20 s.
Making connections...
  Number of connections on node 0: 8116 
  Done; cell connection time = 67.67 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 1.32 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1890.21 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 5.44 s.

Analyzing...
  Cells: 400
  Connections: 8516 (21.29 per cell)
  Spikes: 81942 (40.97 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1890.21 s
   E : 46.401 Hz
   I : 9.833 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_1/gen_1_cand_48_data.json ... 
Finished saving!
  Done; saving time = 10.46 s.
  Done; plotting time = 0.00 s

Total time = 1976.77 s
first instance of v_init
first instance of tstop
