
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240414_Run1_test/gen_0/gen_0_cand_3_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240414_Run1_test/gen_0/gen_0_cand_3_cfg.json ... 
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240414_Run1_test/240414_Run1_test_netParams.py
Duration: 1 seconds
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240414_Run1_test/netParams_popParams.json ... 

Start time:  2024-04-14 02:03:00.288968

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.03 s.
Making connections...
  Number of connections on node 0: 9873 
  Done; cell connection time = 1.84 s.
Adding stims...
  Number of stims on node 0: 800 
  Done; cell stims creation time = 0.07 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 63.85 s; real-time ratio: 0.08.

Gathering data...
  Done; gather time = 0.25 s.

Analyzing...
  Cells: 400
  Connections: 10273 (25.68 per cell)
  Synaptic contacts: 10673 (26.68 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 63.85 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240414_Run1_test/gen_0/gen_0_cand_3_data.json ... 
Finished saving!
  Done; saving time = 0.46 s.
  Done; plotting time = 0.00 s

Total time = 66.51 s
first instance of v_init
first instance of tstop
