
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_2/gen_2_cand_53_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_2/gen_2_cand_53_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/240425_Run4_25AprRunWhileWork_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 14:43:38.741623

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.30 s.
Making connections...
  Number of connections on node 0: 3016 
  Done; cell connection time = 45.58 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 1.45 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 975.80 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 4.41 s.

Analyzing...
  Cells: 400
  Connections: 3416 (8.54 per cell)
  Spikes: 124711 (62.36 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 975.80 s
   E : 15.032 Hz
   I : 4.898 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_2/gen_2_cand_53_data.json ... 
Finished saving!
  Done; saving time = 9.26 s.
  Done; plotting time = 0.00 s

Total time = 1038.28 s
first instance of v_init
first instance of tstop
