
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_2/gen_2_cand_22_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_2/gen_2_cand_22_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/240425_Run4_25AprRunWhileWork_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 14:42:52.323746

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.23 s.
Making connections...
  Number of connections on node 0: 2621 
  Done; cell connection time = 32.06 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 1.32 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1154.19 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 4.62 s.

Analyzing...
  Cells: 400
  Connections: 3021 (7.55 per cell)
  Spikes: 280 (0.14 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1154.19 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_2/gen_2_cand_22_data.json ... 
Finished saving!
  Done; saving time = 4.89 s.
  Done; plotting time = 0.00 s

Total time = 1198.42 s
first instance of v_init
first instance of tstop
