
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_4/gen_4_cand_102_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_4/gen_4_cand_102_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 06:39:16.322356

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 4.53 s.
Making connections...
  Number of connections on node 0: 461 
  Done; cell connection time = 143.34 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 5.20 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 2009.90 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 5.19 s.

Analyzing...
  Cells: 400
  Connections: 861 (2.15 per cell)
  Spikes: 1499 (0.75 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 2009.90 s
   E : 1.052 Hz
   I : 3.361 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_4/gen_4_cand_102_data.json ... 
Finished saving!
  Done; saving time = 11.66 s.
  Done; plotting time = 0.00 s

Total time = 2180.30 s
first instance of v_init
first instance of tstop
