
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_2/gen_2_cand_25_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_2/gen_2_cand_25_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/240425_Run4_25AprRunWhileWork_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 14:43:18.735682

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.08 s.
Making connections...
  Number of connections on node 0: 7424 
  Done; cell connection time = 65.73 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 1.33 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1362.19 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 4.40 s.

Analyzing...
  Cells: 400
  Connections: 7824 (19.56 per cell)
  Spikes: 33156 (16.58 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1362.19 s
   E : 18.813 Hz
   I : 14.611 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_2/gen_2_cand_25_data.json ... 
Finished saving!
  Done; saving time = 7.11 s.
  Done; plotting time = 0.00 s

Total time = 1442.02 s
first instance of v_init
first instance of tstop
