
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run28_debug_run/gen_0/gen_0_cand_5_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run28_debug_run/gen_0/gen_0_cand_5_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run28_debug_run/240417_Run28_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run28_debug_run/netParams_popParams.json ... 

Start time:  2024-04-17 23:38:51.445043

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.04 s.
Making connections...
  Number of connections on node 0: 3458 
  Done; cell connection time = 1.93 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.04 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 8.11 s; real-time ratio: 0.12.

Gathering data...
  Done; gather time = 0.16 s.

Analyzing...
  Cells: 400
  Connections: 3858 (9.64 per cell)
  Spikes: 27687 (69.22 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 8.11 s
   E : 102.246 Hz
   I : 4.870 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run28_debug_run/gen_0/gen_0_cand_5_data.json ... 
Finished saving!
  Done; saving time = 0.24 s.
  Done; plotting time = 0.00 s

Total time = 10.56 s
