
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_12/gen_12_cand_17_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_12/gen_12_cand_17_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-27 06:41:17.518546

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.86 s.
Making connections...
  Number of connections on node 0: 8723 
  Done; cell connection time = 88.51 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 2464.26 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 6.98 s.

Analyzing...
  Cells: 400
  Connections: 8723 (21.81 per cell)
  Spikes: 107957 (53.98 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 2464.26 s
   E : 86.746 Hz
   I : 16.676 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_12/gen_12_cand_17_data.json ... 
Finished saving!
  Done; saving time = 17.51 s.
  Done; plotting time = 0.00 s

Total time = 2580.25 s
first instance of v_init
first instance of tstop
