
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_12/gen_12_cand_82_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_12/gen_12_cand_82_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/240426_Run12_26AprSAFE_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/netParams_popParams.json ... 

Start time:  2024-04-27 06:41:41.319368

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.22 s.
Making connections...
  Number of connections on node 0: 38800 
  Done; cell connection time = 168.41 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 2800.61 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 5.01 s.

Analyzing...
  Cells: 400
  Connections: 38800 (97.00 per cell)
  Spikes: 2965 (1.48 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 2800.61 s
   E : 5.480 Hz
   I : 0.019 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run12_26AprSAFE_1x100/gen_12/gen_12_cand_82_data.json ... 
Finished saving!
  Done; saving time = 6.03 s.
  Done; plotting time = 0.00 s

Total time = 2981.31 s
first instance of v_init
first instance of tstop
