
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/gen_0/gen_0_cand_3_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/gen_0/gen_0_cand_3_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/240426_Run2_scaling_up_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/netParams_popParams.json ... 

Start time:  2024-04-26 10:18:40.591455

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.04 s.
Making connections...
  Number of connections on node 0: 11384 
  Done; cell connection time = 2.28 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.04 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 112.86 s; real-time ratio: 0.04.

Gathering data...
  Done; gather time = 0.41 s.

Analyzing...
  Cells: 400
  Connections: 11784 (29.46 per cell)
  Spikes: 26767 (13.38 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 112.86 s
   E : 16.413 Hz
   I : 25.213 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run2_scaling_up/gen_0/gen_0_cand_3_data.json ... 
Finished saving!
  Done; saving time = 0.99 s.
  Done; plotting time = 0.00 s

Total time = 116.63 s
first instance of v_init
first instance of tstop
