numprocs=4

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run8_MPIsxOMPs_1x4x4/gen_0/gen_0_cand_1_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run8_MPIsxOMPs_1x4x4/gen_0/gen_0_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run8_MPIsxOMPs_1x4x4/240422_Run8_MPIsxOMPs_1x4x4_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run8_MPIsxOMPs_1x4x4/gen_0/gen_0_cand_1_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run8_MPIsxOMPs_1x4x4/gen_0/gen_0_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run8_MPIsxOMPs_1x4x4/240422_Run8_MPIsxOMPs_1x4x4_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run8_MPIsxOMPs_1x4x4/netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run8_MPIsxOMPs_1x4x4/netParams_popParams.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run8_MPIsxOMPs_1x4x4/gen_0/gen_0_cand_1_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run8_MPIsxOMPs_1x4x4/gen_0/gen_0_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run8_MPIsxOMPs_1x4x4/240422_Run8_MPIsxOMPs_1x4x4_netParams.py

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run8_MPIsxOMPs_1x4x4/gen_0/gen_0_cand_1_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run8_MPIsxOMPs_1x4x4/gen_0/gen_0_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run8_MPIsxOMPs_1x4x4/240422_Run8_MPIsxOMPs_1x4x4_netParams.py
Loading file netParams_popParams.json ... 
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run8_MPIsxOMPs_1x4x4/netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run8_MPIsxOMPs_1x4x4/netParams_popParams.json ... 

Start time:  2024-04-22 12:38:30.837140

Creating network of 2 cell populations on 4 hosts...
  Number of cells on node 0: 100 
  Number of cells on node 1: 100 
  Number of cells on node 2: 100 
  Number of cells on node 3: 100 
  Done; cell creation time = 0.01 s.
Making connections...
  Number of connections on node 3: 854 
  Number of connections on node 0: 919 
  Number of connections on node 1: 870 
  Number of connections on node 2: 895 
  Done; cell connection time = 1.10 s.
Adding stims...
  Number of stims on node 1: 100 
  Number of stims on node 2: 100 
  Number of stims on node 3: 100 
  Number of stims on node 0: 100 
  Done; cell stims creation time = 0.02 s.
Recording 0 traces of 0 types on node 1
Recording 0 traces of 0 types on node 3
Recording 0 traces of 0 types on node 0
Recording 0 traces of 0 types on node 2

Running simulation using NEURON for 30000.0 ms...
  Done; run time = 132.50 s; real-time ratio: 0.23.

Gathering data...
  Done; gather time = 1.38 s.

Analyzing...
  Cells: 400
  Connections: 3938 (9.85 per cell)
  Spikes: 258168 (21.51 Hz)
  Simulated time: 30.0 s; 4 workers
  Run time: 132.50 s
   E : 17.893 Hz
   I : 13.352 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240422_Run8_MPIsxOMPs_1x4x4/gen_0/gen_0_cand_1_data.json ... 
Finished saving!
  Done; saving time = 3.12 s.
  Done; plotting time = 0.00 s

Total time = 138.27 s
