
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_2/gen_2_cand_30_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_2/gen_2_cand_30_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 04:30:12.073199

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.42 s.
Making connections...
  Number of connections on node 0: 10053 
  Done; cell connection time = 99.10 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 2.11 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 2200.27 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 5.87 s.

Analyzing...
  Cells: 400
  Connections: 10453 (26.13 per cell)
  Spikes: 12973 (6.49 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 2200.27 s
   E : 1.083 Hz
   I : 16.333 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_2/gen_2_cand_30_data.json ... 
Finished saving!
  Done; saving time = 7.73 s.
  Done; plotting time = 0.00 s

Total time = 2316.62 s
first instance of v_init
first instance of tstop
