
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_2/gen_2_cand_90_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_2/gen_2_cand_90_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 04:32:11.978953

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 3.37 s.
Making connections...
  Number of connections on node 0: 4331 
  Done; cell connection time = 151.60 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 3.82 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 3095.14 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 9.52 s.

Analyzing...
  Cells: 400
  Connections: 4731 (11.83 per cell)
  Spikes: 78125 (39.06 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 3095.14 s
   E : 36.754 Hz
   I : 11.824 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_2/gen_2_cand_90_data.json ... 
Finished saving!
  Done; saving time = 20.60 s.
  Done; plotting time = 0.00 s

Total time = 3285.43 s
first instance of v_init
first instance of tstop
