
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_2/gen_2_cand_49_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_2/gen_2_cand_49_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 04:32:01.720905

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 3.43 s.
Making connections...
  Number of connections on node 0: 831 
  Done; cell connection time = 94.95 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 3.56 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 1330.59 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 5.23 s.

Analyzing...
  Cells: 400
  Connections: 1231 (3.08 per cell)
  Spikes: 94126 (47.06 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 1330.59 s
   E : 50.433 Hz
   I : 30.676 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_2/gen_2_cand_49_data.json ... 
Finished saving!
  Done; saving time = 20.25 s.
  Done; plotting time = 0.00 s

Total time = 1464.32 s
first instance of v_init
first instance of tstop
