
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/240425_Run4_25AprRunWhileWork_1x128_netParams.py
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 12:37:33.450151

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.10 s.
Making connections...
  Number of connections on node 0: 872 
  Done; cell connection time = 3.68 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.12 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 56.59 s; real-time ratio: 0.09.

Gathering data...
  Done; gather time = 0.22 s.

Analyzing...
  Cells: 400
  Connections: 1272 (3.18 per cell)
  Spikes: 18480 (9.24 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 56.59 s
   E : 5.750 Hz
   I : 4.259 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run4_25AprRunWhileWork_1x128/gen_0/gen_0_cand_0_data.json ... 
Finished saving!
  Done; saving time = 0.86 s.
  Done; plotting time = 0.00 s

Total time = 61.70 s
first instance of v_init
first instance of tstop
