
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run30_debug_run/gen_0/gen_0_cand_4_cfg.json
Loading file /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run30_debug_run/gen_0/gen_0_cand_4_cfg.json ... 
Loading simConfig...
Importing netParams from /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run30_debug_run/240417_Run30_debug_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run30_debug_run/netParams_popParams.json ... 

Start time:  2024-04-17 23:49:12.890919

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.07 s.
Making connections...
  Number of connections on node 0: 30202 
  Done; cell connection time = 6.68 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.05 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 1000.0 ms...
  Done; run time = 70.45 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 0.81 s.

Analyzing...
  Cells: 400
  Connections: 30602 (76.50 per cell)
  Spikes: 13043 (32.61 Hz)
  Simulated time: 1.0 s; 1 workers
  Run time: 70.45 s
   E : 51.718 Hz
   I : 0.000 Hz
Saving output as /mnt/c/Users/adamm/Documents/GithubRepositories/2DNetworkSimulations/NERSC/output/240417_Run30_debug_run/gen_0/gen_0_cand_4_data.json ... 
Finished saving!
  Done; saving time = 0.97 s.
  Done; plotting time = 0.00 s

Total time = 79.17 s
