
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_103_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_103_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 02:25:29.391980

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 3.94 s.
Making connections...
  Number of connections on node 0: 17408 
  Done; cell connection time = 339.13 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 4.19 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 15115.48 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 63.92 s.

Analyzing...
  Cells: 400
  Connections: 17808 (44.52 per cell)
  Spikes: 125880 (62.94 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 15115.48 s
   E : 42.575 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_103_data.json ... 
Finished saving!
  Done; saving time = 93.22 s.
  Done; plotting time = 0.00 s

Total time = 15622.85 s
first instance of v_init
first instance of tstop
