
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_0_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_0_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 02:21:32.323032

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.13 s.
Making connections...
  Number of connections on node 0: 23636 
  Done; cell connection time = 12.22 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.13 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 521.78 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.32 s.

Analyzing...
  Cells: 400
  Connections: 24036 (60.09 per cell)
  Spikes: 78491 (39.25 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 521.78 s
   E : 64.369 Hz
   I : 5.787 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_0_data.json ... 
Finished saving!
  Done; saving time = 3.02 s.
  Done; plotting time = 0.00 s

Total time = 539.71 s
first instance of v_init
first instance of tstop
