
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_42_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_42_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 02:23:32.707930

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 4.67 s.
Making connections...
  Number of connections on node 0: 16112 
  Done; cell connection time = 319.33 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 4.35 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 14747.77 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 58.20 s.

Analyzing...
  Cells: 400
  Connections: 16512 (41.28 per cell)
  Spikes: 71878 (35.94 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 14747.77 s
   E : 30.869 Hz
   I : 22.519 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_42_data.json ... 
Finished saving!
  Done; saving time = 71.57 s.
  Done; plotting time = 0.00 s

Total time = 15208.29 s
first instance of v_init
first instance of tstop
