
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_35_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_35_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 02:23:24.804738

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 3.02 s.
Making connections...
  Number of connections on node 0: 47287 
  Done; cell connection time = 451.19 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 3.13 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 19933.53 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 49.66 s.

Analyzing...
  Cells: 400
  Connections: 47687 (119.22 per cell)
  Spikes: 18999 (9.50 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 19933.53 s
   E : 14.365 Hz
   I : 10.204 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_35_data.json ... 
Finished saving!
  Done; saving time = 54.53 s.
  Done; plotting time = 0.00 s

Total time = 20495.64 s
first instance of v_init
first instance of tstop
