
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_68_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_68_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/240425_Run3_overnightRun24Apr_1x128_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/netParams_popParams.json ... 

Start time:  2024-04-25 02:24:47.152297

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 2.83 s.
Making connections...
  Number of connections on node 0: 26109 
  Done; cell connection time = 284.99 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 3.07 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 13446.17 s; real-time ratio: 0.00.

Gathering data...
  Done; gather time = 34.82 s.

Analyzing...
  Cells: 400
  Connections: 26509 (66.27 per cell)
  Spikes: 13587 (6.79 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 13446.17 s
   E : 9.198 Hz
   I : 3.037 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240425_Run3_overnightRun24Apr_1x128/gen_0/gen_0_cand_68_data.json ... 
Finished saving!
  Done; saving time = 39.69 s.
  Done; plotting time = 0.00 s

Total time = 13812.07 s
first instance of v_init
first instance of tstop
