#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;
#if defined(__cplusplus)
extern "C" {
#endif

extern void _A_reg(void);
extern void _AMPA_reg(void);
extern void _ar_reg(void);
extern void _beforestep_py_reg(void);
extern void _cadad_reg(void);
extern void _cad_reg(void);
extern void _cadyn_reg(void);
extern void _cagk_reg(void);
extern void _cal_mh_reg(void);
extern void _cal_mig_reg(void);
extern void _ca_reg(void);
extern void _canin_reg(void);
extern void _can_mig_reg(void);
extern void _catcb_reg(void);
extern void _cat_mig_reg(void);
extern void _cat_reg(void);
extern void _cat_traub_reg(void);
extern void _dipole_reg(void);
extern void _dipole_pp_reg(void);
extern void _ElectSyn_reg(void);
extern void _expsynstdp_reg(void);
extern void _GABAa_reg(void);
extern void _gabab_reg(void);
extern void _h_BS_reg(void);
extern void _HCN1_reg(void);
extern void _hh2_reg(void);
extern void _hh3_reg(void);
extern void _h_harnett_reg(void);
extern void _hin_reg(void);
extern void _h_kole_reg(void);
extern void _h_migliore_reg(void);
extern void _ican_sidi_reg(void);
extern void _IC_reg(void);
extern void _iholmw_reg(void);
extern void _IKsin_reg(void);
extern void _izhi2003a_reg(void);
extern void _izhi2003b_reg(void);
extern void _izhi2007a_reg(void);
extern void _izhi2007b_reg(void);
extern void _k2_reg(void);
extern void _kacurrent_reg(void);
extern void _kahp_reg(void);
extern void _ka_reg(void);
extern void _kap_BS_reg(void);
extern void _kapcb_reg(void);
extern void _kapin_reg(void);
extern void _kBK_reg(void);
extern void _kca_reg(void);
extern void _kc_reg(void);
extern void _kctin_reg(void);
extern void _kdmc_BS_reg(void);
extern void _kdr_BS_reg(void);
extern void _kdrcurrent_reg(void);
extern void _kdrin_reg(void);
extern void _km2_reg(void);
extern void _km_reg(void);
extern void _kv_reg(void);
extern void _lfp_reg(void);
extern void _mea_reg(void);
extern void _MyExp2SynBB_reg(void);
extern void _MyExp2SynNMDABB_reg(void);
extern void _nacurrent_reg(void);
extern void _naf_reg(void);
extern void _nafx_reg(void);
extern void _nap_reg(void);
extern void _nax_BS_reg(void);
extern void _naz_reg(void);
extern void _Nca_reg(void);
extern void _NMDA_reg(void);
extern void _OFThpo_reg(void);
extern void _OFThresh_reg(void);
extern void _savedist_reg(void);
extern void _vecevent_reg(void);
extern void _vecstim_reg(void);

void modl_reg() {
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");
    fprintf(stderr, " \"mod/A.mod\"");
    fprintf(stderr, " \"mod/AMPA.mod\"");
    fprintf(stderr, " \"mod/ar.mod\"");
    fprintf(stderr, " \"mod/beforestep_py.mod\"");
    fprintf(stderr, " \"mod/cadad.mod\"");
    fprintf(stderr, " \"mod/cad.mod\"");
    fprintf(stderr, " \"mod/cadyn.mod\"");
    fprintf(stderr, " \"mod/cagk.mod\"");
    fprintf(stderr, " \"mod/cal_mh.mod\"");
    fprintf(stderr, " \"mod/cal_mig.mod\"");
    fprintf(stderr, " \"mod/ca.mod\"");
    fprintf(stderr, " \"mod/canin.mod\"");
    fprintf(stderr, " \"mod/can_mig.mod\"");
    fprintf(stderr, " \"mod/catcb.mod\"");
    fprintf(stderr, " \"mod/cat_mig.mod\"");
    fprintf(stderr, " \"mod/cat.mod\"");
    fprintf(stderr, " \"mod/cat_traub.mod\"");
    fprintf(stderr, " \"mod/dipole.mod\"");
    fprintf(stderr, " \"mod/dipole_pp.mod\"");
    fprintf(stderr, " \"mod/ElectSyn.mod\"");
    fprintf(stderr, " \"mod/expsynstdp.mod\"");
    fprintf(stderr, " \"mod/GABAa.mod\"");
    fprintf(stderr, " \"mod/gabab.mod\"");
    fprintf(stderr, " \"mod/h_BS.mod\"");
    fprintf(stderr, " \"mod/HCN1.mod\"");
    fprintf(stderr, " \"mod/hh2.mod\"");
    fprintf(stderr, " \"mod/hh3.mod\"");
    fprintf(stderr, " \"mod/h_harnett.mod\"");
    fprintf(stderr, " \"mod/hin.mod\"");
    fprintf(stderr, " \"mod/h_kole.mod\"");
    fprintf(stderr, " \"mod/h_migliore.mod\"");
    fprintf(stderr, " \"mod/ican_sidi.mod\"");
    fprintf(stderr, " \"mod/IC.mod\"");
    fprintf(stderr, " \"mod/iholmw.mod\"");
    fprintf(stderr, " \"mod/IKsin.mod\"");
    fprintf(stderr, " \"mod/izhi2003a.mod\"");
    fprintf(stderr, " \"mod/izhi2003b.mod\"");
    fprintf(stderr, " \"mod/izhi2007a.mod\"");
    fprintf(stderr, " \"mod/izhi2007b.mod\"");
    fprintf(stderr, " \"mod/k2.mod\"");
    fprintf(stderr, " \"mod/kacurrent.mod\"");
    fprintf(stderr, " \"mod/kahp.mod\"");
    fprintf(stderr, " \"mod/ka.mod\"");
    fprintf(stderr, " \"mod/kap_BS.mod\"");
    fprintf(stderr, " \"mod/kapcb.mod\"");
    fprintf(stderr, " \"mod/kapin.mod\"");
    fprintf(stderr, " \"mod/kBK.mod\"");
    fprintf(stderr, " \"mod/kca.mod\"");
    fprintf(stderr, " \"mod/kc.mod\"");
    fprintf(stderr, " \"mod/kctin.mod\"");
    fprintf(stderr, " \"mod/kdmc_BS.mod\"");
    fprintf(stderr, " \"mod/kdr_BS.mod\"");
    fprintf(stderr, " \"mod/kdrcurrent.mod\"");
    fprintf(stderr, " \"mod/kdrin.mod\"");
    fprintf(stderr, " \"mod/km2.mod\"");
    fprintf(stderr, " \"mod/km.mod\"");
    fprintf(stderr, " \"mod/kv.mod\"");
    fprintf(stderr, " \"mod/lfp.mod\"");
    fprintf(stderr, " \"mod/mea.mod\"");
    fprintf(stderr, " \"mod/MyExp2SynBB.mod\"");
    fprintf(stderr, " \"mod/MyExp2SynNMDABB.mod\"");
    fprintf(stderr, " \"mod/nacurrent.mod\"");
    fprintf(stderr, " \"mod/naf.mod\"");
    fprintf(stderr, " \"mod/nafx.mod\"");
    fprintf(stderr, " \"mod/nap.mod\"");
    fprintf(stderr, " \"mod/nax_BS.mod\"");
    fprintf(stderr, " \"mod/naz.mod\"");
    fprintf(stderr, " \"mod/Nca.mod\"");
    fprintf(stderr, " \"mod/NMDA.mod\"");
    fprintf(stderr, " \"mod/OFThpo.mod\"");
    fprintf(stderr, " \"mod/OFThresh.mod\"");
    fprintf(stderr, " \"mod/savedist.mod\"");
    fprintf(stderr, " \"mod/vecevent.mod\"");
    fprintf(stderr, " \"mod/vecstim.mod\"");
    fprintf(stderr, "\n");
  }
  _A_reg();
  _AMPA_reg();
  _ar_reg();
  _beforestep_py_reg();
  _cadad_reg();
  _cad_reg();
  _cadyn_reg();
  _cagk_reg();
  _cal_mh_reg();
  _cal_mig_reg();
  _ca_reg();
  _canin_reg();
  _can_mig_reg();
  _catcb_reg();
  _cat_mig_reg();
  _cat_reg();
  _cat_traub_reg();
  _dipole_reg();
  _dipole_pp_reg();
  _ElectSyn_reg();
  _expsynstdp_reg();
  _GABAa_reg();
  _gabab_reg();
  _h_BS_reg();
  _HCN1_reg();
  _hh2_reg();
  _hh3_reg();
  _h_harnett_reg();
  _hin_reg();
  _h_kole_reg();
  _h_migliore_reg();
  _ican_sidi_reg();
  _IC_reg();
  _iholmw_reg();
  _IKsin_reg();
  _izhi2003a_reg();
  _izhi2003b_reg();
  _izhi2007a_reg();
  _izhi2007b_reg();
  _k2_reg();
  _kacurrent_reg();
  _kahp_reg();
  _ka_reg();
  _kap_BS_reg();
  _kapcb_reg();
  _kapin_reg();
  _kBK_reg();
  _kca_reg();
  _kc_reg();
  _kctin_reg();
  _kdmc_BS_reg();
  _kdr_BS_reg();
  _kdrcurrent_reg();
  _kdrin_reg();
  _km2_reg();
  _km_reg();
  _kv_reg();
  _lfp_reg();
  _mea_reg();
  _MyExp2SynBB_reg();
  _MyExp2SynNMDABB_reg();
  _nacurrent_reg();
  _naf_reg();
  _nafx_reg();
  _nap_reg();
  _nax_BS_reg();
  _naz_reg();
  _Nca_reg();
  _NMDA_reg();
  _OFThpo_reg();
  _OFThresh_reg();
  _savedist_reg();
  _vecevent_reg();
  _vecstim_reg();
}

#if defined(__cplusplus)
}
#endif
