
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_2/gen_2_cand_18_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_2/gen_2_cand_18_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/240430_Run1_interactive_node_run_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/netParams_popParams.json ... 

Start time:  2024-04-30 14:11:29.880440

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.46 s.
Making connections...
  Number of connections on node 0: 25063 
  Done; cell connection time = 15.22 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 10000.0 ms...
  Done; run time = 1341.56 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 1.55 s.

Analyzing...
  Cells: 400
  Connections: 25063 (62.66 per cell)
  Spikes: 280 (0.07 Hz)
  Simulated time: 10.0 s; 1 workers
  Run time: 1341.56 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240430_Run1_interactive_node_run/gen_2/gen_2_cand_18_data.json ... 
Finished saving!
  Done; saving time = 3.87 s.
  Done; plotting time = 0.00 s

Total time = 1362.67 s
