
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240414_Run1_test/gen_2/gen_2_cand_1_cfg.json
Loading file /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240414_Run1_test/gen_2/gen_2_cand_1_cfg.json ... 
Loading simConfig...
Importing netParams from /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240414_Run1_test/240414_Run1_test_netParams.py
Duration: 1 seconds
Loading file netParams_popParams.json ... 
Saving netParams to /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240414_Run1_test/netParams_popParams.json ... 

Start time:  2024-04-14 02:09:54.771339

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.04 s.
Making connections...
  Number of connections on node 0: 1518 
  Done; cell connection time = 1.19 s.
Adding stims...
  Number of stims on node 0: 800 
  Done; cell stims creation time = 0.08 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 23.97 s; real-time ratio: 0.21.

Gathering data...
  Done; gather time = 0.13 s.

Analyzing...
  Cells: 400
  Connections: 1918 (4.79 per cell)
  Synaptic contacts: 2318 (5.79 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 23.97 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /global/u2/a/adammwea/2DNetworkSimulations/NERSC/output/240414_Run1_test/gen_2/gen_2_cand_1_data.json ... 
Finished saving!
  Done; saving time = 0.26 s.
  Done; plotting time = 0.00 s

Total time = 25.67 s
first instance of v_init
first instance of tstop
