
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_1/gen_1_cand_73_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_1/gen_1_cand_73_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 05:40:53.888373

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.17 s.
Making connections...
  Number of connections on node 0: 1053 
  Done; cell connection time = 46.15 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 1.83 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 850.26 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.66 s.

Analyzing...
  Cells: 400
  Connections: 1453 (3.63 per cell)
  Spikes: 481 (0.24 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 850.26 s
   E : 0.000 Hz
   I : 0.852 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_1/gen_1_cand_73_data.json ... 
Finished saving!
  Done; saving time = 5.91 s.
  Done; plotting time = 0.00 s

Total time = 907.98 s
first instance of v_init
first instance of tstop
