
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run3_interactive_debug/gen_0/gen_0_cand_42_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run3_interactive_debug/gen_0/gen_0_cand_42_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run3_interactive_debug/240429_Run3_interactive_debug_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run3_interactive_debug/netParams_popParams.json ... 

Start time:  2024-04-29 01:03:19.195387

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.06 s.
Making connections...
  Number of connections on node 0: 34311 
  Done; cell connection time = 4.81 s.
  Number of stims on node 0: 0 
  Done; cell stims creation time = 0.00 s.
Recording 2 traces of 1 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 197.76 s; real-time ratio: 0.03.

Gathering data...
  Done; gather time = 0.86 s.

Analyzing...
  Cells: 400
  Connections: 34311 (85.78 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 197.76 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240429_Run3_interactive_debug/gen_0/gen_0_cand_42_data.json ... 
Finished saving!
  Done; saving time = 1.18 s.
  Done; plotting time = 0.00 s

Total time = 204.69 s
first instance of v_init
first instance of tstop
