
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_0/gen_0_cand_69_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_0/gen_0_cand_69_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/240426_Run1_Apr25safety_1x100_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/netParams_popParams.json ... 

Start time:  2024-04-26 04:27:02.043549

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 1.58 s.
Making connections...
  Number of connections on node 0: 710 
  Done; cell connection time = 56.26 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 2.20 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 827.87 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 2.76 s.

Analyzing...
  Cells: 400
  Connections: 1110 (2.77 per cell)
  Spikes: 0 (0.00 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 827.87 s
   E : 0.000 Hz
   I : 0.000 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240426_Run1_Apr25safety_1x100/gen_0/gen_0_cand_69_data.json ... 
Finished saving!
  Done; saving time = 6.23 s.
  Done; plotting time = 0.00 s

Total time = 896.90 s
first instance of v_init
first instance of tstop
