
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/gen_0/gen_0_cand_19_cfg.json
Loading file /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/gen_0/gen_0_cand_19_cfg.json ... 
Loading simConfig...
Importing netParams from /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/240424_Run9_scaling_up_netParams.py
Loading file netParams_popParams.json ... 
Saving netParams to /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/netParams_popParams.json ... 

Start time:  2024-04-24 23:17:12.416364

Creating network of 2 cell populations on 1 hosts...
  Number of cells on node 0: 400 
  Done; cell creation time = 0.06 s.
Making connections...
  Number of connections on node 0: 28673 
  Done; cell connection time = 5.58 s.
Adding stims...
  Number of stims on node 0: 400 
  Done; cell stims creation time = 0.05 s.
Recording 0 traces of 0 types on node 0

Running simulation using NEURON for 5000.0 ms...
  Done; run time = 535.09 s; real-time ratio: 0.01.

Gathering data...
  Done; gather time = 0.89 s.

Analyzing...
  Cells: 400
  Connections: 29073 (72.68 per cell)
  Spikes: 91997 (46.00 Hz)
  Simulated time: 5.0 s; 1 workers
  Run time: 535.09 s
   E : 49.940 Hz
   I : 3.083 Hz
Saving output as /pscratch/sd/a/adammwea/2DNetworkSimulations/NERSC/output/240424_Run9_scaling_up/gen_0/gen_0_cand_19_data.json ... 
Finished saving!
  Done; saving time = 1.81 s.
  Done; plotting time = 0.00 s

Total time = 543.62 s
first instance of v_init
first instance of tstop
